### PR TITLE
[eventMacro.pl] Added &strip()

### PR DESCRIPTION
**Pull request by Mortimal**
Added &strip() as temporary fix for #1123.

### CODE REVIEW

**Comment by lututui** [comment]
This takes away the () from the match?

**Comment by Mortimal** [comment]
this ads &strip() function which can be used to remove ( ) from $. vars like

```
automacro monster {
 SimpleHookEvent target_died
 call monster2 
 } 
macro monster2 {
	if (&strip($.SimpleHookEventLastMonster) =~ /Poring/) {
	 log yes
	 stop
	}
	log not
	stop 
}
```

Because normal fix is just impossible... now

**Comment by lututui** [comment]
Doesn't this have the same behavior
`if (&strip($.SimpleHookEventLastMonster) =~ /Poring/) {`
as this
`if ($.SimpleHookEventLastMonster =~ /Poring/) {`
?

**Comment by Mortimal** [comment]
`if ($.SimpleHookEventLastMonster =~ /Poring/) {`

this will be error because of #1123 

**$.SimpleHookEventLastMonster** contains **Poring (\d)** and if \d not 0 or 1 condition parser gives error...

**Comment by Nipodemos** [comment]
i've noticed something similar to what happened to you
i've tried this:
```
               $name = name: Nipo lastname: demos
		log $name
		if ($name =~ /name: (\w+) lastname: (\w+)/) {
			log it worked 
		}
```
the intereresting part is , the code removes the parentesis: 

image

so `/name: (\w+) lastname: (\w+)/` is changed to `/name: \w+ lastname: \w+/`
and i don't know why, do you know what sub is doing this thing?
I think is whenever the `sub parse_command` is called
which calls `parse_keywords`
which calls `extract_brackted` which is meant to remove `()`

**Comment by Nipodemos** [comment]
@Mortimal do you have irc or discord? i would like to discuss some improvements on eventMacro, and two heads think better than one 😄

**Comment by Nipodemos** [comment]
just tested and is working fine

**Pull request merged**
