### PR TITLE
Dunstle os patch 9

### PR DESCRIPTION
**Pull request by zuroba**
del

### CODE REVIEW

**Comment by systeman** [comment]
อ้อ อย่าลืม edit หัวเรื่องด้วยนะว่าจะ pull อะไร

**Comment by scream1ng** [comment]
@thekickass
disassemble ragexe, reverse engineering

**Comment by kotenarak** [comment]
I appreciate @DunstleOS support everything.
I need to know how i can solve this problem if i found any updates on server. I will solve myself if i can do.

@scream1ng How i do the $msg .= hmac_md5($msg, pack('H*','EDB9D10AB84C9A2E05E38997C2F64A29')); if i need to find myself.

Please guide  steps by steps for first thing if i found any issues from updated on RO server.

Thank you very much all your sharing.
My apologize for English poor. Sorry again!! :)

**Comment by Cozzie** [comment]
Not up to date. PR closed.

**Pull request closed without merging**
