### PR TITLE
Updated packet data for iRO Re:Start

### PR DESCRIPTION
**Pull request by gudoh**
Just in case, I hope that @allanon is coming back soon because I have no plans to become a contributor.

### CODE REVIEW

**Comment by kiko3290** [comment]
thanks! I copied all and past to tables/iRO/Restart but still not working. did I do it right?

**Comment by gudoh** [comment]
@kiko3290 
Not exactly. The files recvpackets.txt, shuffle.txt and sync.txt need to be copied to tables/iRO/Restart/, and the remaining file servers.txt - to tables/.

**Comment by poaepoae** [comment]
@gudoh thanks it works ! Btw can I get your email ? I have a few questions and I’ve been trying to update the packets but failed ...

**Comment by ZaskarAlpha** [comment]
working thanks!

**Comment by Zelecktor** [comment]
Just for educational purposes. How did you make the "old_recvpackets" and the "old_shuffle" to shuffle new packets?

**Comment by alisonrag** [comment]
"Educational"
^^
Check #2407 second post

**Comment by gudoh** [comment]
@ Zelecktor
I left my explanations of how I did things in commetns to the script.

@poaepoae
Does my comment to the script answers your questions or there is something more?

**Comment by kiko3290** [comment]
@gudoh thank you very much!! Now it’s working!

**Comment by Zelecktor** [comment]
@alisonrag I know, and apreciate that. But at this case, client got 13 new packets that they arent shuffled, so suffle.txt will be wrong. Adding them manually to the old_recvpackets makes a shuffle like with 1300-700 lines where the correct shuffle is about 60-70 lines.

My question specifically is: how to add correctly the new packets to get the correct shuffle.txt?

**Comment by alisonrag** [comment]
the correct shuffle have 29 lines.

this script dont get only the correct as you can see here:
List:
https://gitlab.com/4144/peek/blob/master/Input/packet_names.ini#L1

examples:

with packet name:
https://github.com/alisonrag/openkore/blob/aceeeaddbc32d930d9f988598e5892326eb8ef3f/tables/kRO/Sakray/shuffle.txt

without:
https://github.com/OpenKore/openkore/blob/master/tables/bRO/shuffle.txt

**Comment by mrryanlittle** [comment]
It's working for me. I am still learning how to use Github, hoping to get the time to learn Perl and be more than just a leech. Thank you for the update @gudoh

**Comment by poaepoae** [comment]
@gudoh i got all right by extracting the recvpackets.txt , the only thing i that i can't is the suffle.txt. Tried to use peek it doesnt work...

**Comment by AgentOso** [comment]
Need updated file for 10/17 maintenance. Thanks.

**Comment by gudoh** [comment]
@poaepoae
Did you try to follow instructions I left in comments for extract_recvpackets.pl ? I did a fix for current post-maintenance and it's working (just in case, I didn't commited it).

@AgentOso
What's the point? :) Even this pull request wasn't merged anyway while it was still actual.

**Comment by poaepoae** [comment]
@gudoh did i missed something? i followed post #2407 second post, tried to use peek but i failed to extract shuffle.txt...

**Comment by gudoh** [comment]
@poaepoae 
I was talking about [this comment](https://gist.github.com/allanon/d8181ceaf6380da6d8fa4fddf1885706#gistcomment-2278599).

**Comment by poaepoae** [comment]
@gudoh oh i see! what if when i got to step 5 , and i've got no errors?. all 4 got generated but it doesnt work

**Comment by poaepoae** [comment]
@gudoh this is the files
[recvpackets.zip](https://github.com/OpenKore/openkore/files/2494831/recvpackets.zip)

**Comment by kiko3290** [comment]
@poaepoae did you used PEEK to get recvpackets for restart as what alisonrag instructed?

**Comment by poaepoae** [comment]
@kiko3290 @gudoh  I’ve already generated recvpackets , sync , shuffle and servers . But it doesn’t seems to work ,I guess some of the lines I got it wrong . I  tried peek by following tutorial but I keep failing too. As you can see 2 posts before this I uploaded the recvpackets I generated

**Comment by poaepoae** [comment]
@gudoh 

1) You’re right I’m using windows, I extracted the files according to the steps and tutorials I got online. As for the script I use the same ( as what you commented in ) 

2) will it work if I manually change all 8B00000A back to 0A0D ? 

I tried my best to extract all the files but I just don’t know where I did wrong .

**Comment by poaepoae** [comment]
@gudoh sorry to bother you , I will try all I can before I comment , was too rush to find a solution and I commented right away

**Comment by poaepoae** [comment]
@gudoh yes sir i did, i extracted recvpaclets.txt using extract_recvpackets.pl

I try removing and manually add what you've told me and it works! I guess in C++ some coding is different. Anyway thank you so much for sharing!!! really appreciate it.

**Comment by gudoh** [comment]
@poaepoae 
Still, I'm a bit interested to figure out why it didn't work for you (and it seems, for other users as well). Do you have some time for Discord?

**Comment by poaepoae** [comment]
@gudoh sure! my discord ID is the same poaepoae or #7159.

**Pull request merged**
