### PR TITLE
(2015_05_13a) + (2015_11_04a  + tables + recvpackets of AnkRO(1104a_a) /RakkiRO(1104a_b) ) + (2015_10_01b + recvpackets of mIRO)

### PR DESCRIPTION
**Pull request by moneyisgod**
Tested in AnkRO / RakkiRO / mIRO

### CODE REVIEW

**Comment by Slipxxliose** [comment]
09/06 : mIRO according with : 

https://github.com/OpenKore/openkore/issues/614

**Comment by sctnightcore** [comment]
link server mlRO ? @Slipxxliose

**Comment by Slipxxliose** [comment]
@MingFaiYau

**Comment by sctnightcore** [comment]
I updated RagexeRE_2015_09_16 and RagexeRE_2015_11_18a.

Not sure if it will work. 

github.com/sctnightcore/openkore

**Comment by Slipxxliose** [comment]
Well i hope you made it good. 'cause i 've just edited it for you.

**Comment by sctnightcore** [comment]
I'm a newbie, lol,

**Comment by sctnightcore** [comment]
packet parser : unknow switch :09CA @Slipxxliose  
0X97F and 0980

**Comment by Slipxxliose** [comment]
Hey bro is you inside some server with these packets ? Can u sniff it and check it when it's used ? 
Well.

**Comment by sctnightcore** [comment]
1. attack Monster Not show damage 
LOG: You are now attacking Monster Poporing (2)
You are now level 24
You gained a level!
You are now job level 20
= I think there is a missing Receive. 


2. 09CA = 09CA' => ['area_spell_multiple3', 'v a*', [qw(len spellInfo)]]
3.New packet, which I can not 

I have a passion in the bot. And no knowledge of perl. 
Trying to study

**Comment by Slipxxliose** [comment]
Now try setting debug mode to 2.
There's some kind of packet that does this. :O it's normal it not showing the damage. The only thing you can note is when you receive the XP.

```
You are now attacking Monster Poporing (2)
You gained X EXP
```

It's normal.
0x9CA, 0x97F, 0x980 are bugs.

**Comment by sctnightcore** [comment]
EX : Monster ****** (*)(Dmg:9999)(Delay:999ms) 
I updated my RagexeRE_2015_12_02.pm 
But I think Receive is not complete. 

I'm waiting for feedback Then fix it. 
thank you very much @Slipxxliose  <3

**Comment by sctnightcore** [comment]
Do you have a discord or facebook? @Slipxxliose 
I have something to talk about

**Comment by Slipxxliose** [comment]
fbid=127704037815063

**Comment by sctnightcore** [comment]
I can not find you
 add me https://www.facebook.com/profile.php?id=100012804336013 
my fb : maytichai saowa  
@Slipxxliose

**Comment by smallvill3** [comment]
May i know, does the 2015 client works for this patch?
I do run bottable server, which is currently using 2013 client.

**Comment by kaliwanagan** [comment]
@Slipxxliose this is really good, just need to address the review by @sctnightcore :) Then we can merge.

**Comment by sctnightcore** [comment]
@kaliwanagan  ty sir 
I write servertybe 2015+, but the new packet does not.

**Comment by kaliwanagan** [comment]
@sctnightcore you'll have to tell me if this PR is good enough to merge :) We're counting on you to make the right decision!

**Comment by sctnightcore** [comment]
https://github.com/sctnightcore/openkore/blob/master/src/Network/Send/kRO/RagexeRE_2015_12_02.pm 

update

**Comment by kaliwanagan** [comment]
@sctnightcore you're gonna have to resolve the conflicts first. See above (don't click on resolve conflicts but instead click on web editor, it's preferable to resolve the conflicts manually)

**Comment by sctnightcore** [comment]
I gradually came to the updated later. @kaliwanagan  
Single I forget

**Comment by kaliwanagan** [comment]
@Henrybk i think we'll need your eyes to confirm this at least is an improvement

**Comment by Slipxxliose** [comment]
but the new packet does not.

@sctnightcore

**Comment by Slipxxliose** [comment]
bRO is using 09CB with arguments provided here.

2015 looks like incomplete. I guess it wont work good since is missing two packets about cart.

**Comment by Henrybk** [comment]
So guys, is this working? Do you think it should be merged? What implications does these changes have?

**Comment by sctnightcore** [comment]
I do not know what effect it has. @Henrybk

**Comment by moneyisgod** [comment]
1 - Now able to bot in 2015 private servers.
1.1 - Already tested
1.2 - Missing two packets related to cart, but i believe is only client-side ! 

2 - It only make changes in Sakexe0.pm, then i believe we won't have problem,
because the change was needed.

3 - Moved some packets to correct serverType, then i believe it will help
to reorder the packet time add. (09CA = 2013_08_07a)

4 - Provide to the community the respective files to be used by them.

**Comment by moneyisgod** [comment]
isn sir.

**Comment by moneyisgod** [comment]
sir about idRO it is not a fix.

**Comment by moneyisgod** [comment]
Missing 

http://herc.ws/board/topic/432-pushcart-decoration/

Implementation

**Comment by hendra814** [comment]
@kaliwangan, No sir it's still not connect.
To connect you need sniiff and put the code into packetparser.pm and send.pm to decrypt password
here example edited packetparser.pm from last i've got https://pastebin.com/jFmTNXyA
and this is for send.pm https://pastebin.com/5H4NWe9S

For send.pm you must edit line 406 and line 413.
For packetparser.pm edit line 230-320

**Comment by kaliwanagan** [comment]
@moneyisgod thanks. @Henrybk fixed a small bug introduced in this commit, but it's all good now.

@hendra814 these are really good stuff, but you really need to start learning git so you can officially contribute to the project :( can't wait to see your pull requests merged.

**Comment by moneyisgod** [comment]
@kaliwanagan yeah sir, he is sure.
I've done the comparison of rAthena, and now i have sure that it's true what @smallvill3 talked.

**Pull request merged**
