### PR TITLE
Updated idRO table files until maintenance on June 7 and 21, 2016.

### PR DESCRIPTION
**Pull request by cydh**
- [x] Code review

Signed-off-by: Cydh Ramdh <cydh@pservero.com>

### CODE REVIEW

**Comment by allanon** [comment]
Looks good to me. There are a few broken characters (looks like they were windows charset 1252?) but it's valid utf8, which is all openkore really cares about.

Are you using a version of my `patch.pl` (https://github.com/OpenKore/openkore/pull/49/files) to process the files? If so, can you think of a good way to catch both the windows charset 1252 stuff (like the curly quotes) and not break the existing UTF-8 and UCS-2 (Korean)? I struggled with it and still haven't come up with anything I'm happy with.

**Comment by Ax3l210817** [comment]
Just added for items.txt idRO because sometimes get stuck for openkore
7978#Kartu_Imlek1#
7979#Kartu_Imlek2#
7980#Kartu_Imlek3#
7981#Kartu_Imlek4#
7982#Kartu_Imlek5#
7983#Kartu_Imlek6#
7984#Kartu_Imlek7#
7985#Kartu_Imlek8#
7986#Kartu_Imlek9#
7987#Kartu_Imlek10#
7988#Kartu_Imlek11#
7989#Kartu_Imlek12#
7990#Kartu_Imlek13#
7991#Kartu_Imlek14#
7992#Kartu_Imlek15#
7993#Kartu_Imlek16#
7994#Kartu_Imlek17#
7995#Kartu_Imlek18#
7996#Kartu_Imlek19#
7997#Kartu_Imlek20#
7998#Kartu_Imlek21#
7999#Kartu_Imlek22#
12114#Elemental_Fire_Converter#
12115#Elemental_Water_Converter#
12116#Elemental_Earth_Converter#
12117#Elemental_Wind_Converter#

**Comment by cydh** [comment]
For kartu imlek, for good pactice, wrap it by quotes in items_control.txt
"Kartu Imlek 1" 0 0 0

**Comment by Ax3l210817** [comment]
If use old openkore it still got stucked when bot used storage, Elemental Converter too because we did not know where is fire wind earth and water.....just added may help the other :D  Thx's before....

**Comment by Ax3l210817** [comment]
@cydh can i ask u something about Research New Potion for GX job ? Why always disconnect when used skill to cook some potion even the send packet write on macro is true ? and the disconnect always happened after make one potion ex Leech End after make one always disconnected .....thx for your answer...

**Comment by cydh** [comment]
@Ax3l210817 sorry, I don't have char & materials to test.

**Comment by cydh** [comment]
@allanon how can u expect someone to use ur tool without any documentation?
And... 
* it needs to download the patch file (redownloading that downloaded already, it's something), 
* the base link and command used is FTP, that idRO doesn't
* idRO has more than 1 patch urls
* again, no documentation (I'm not an esper)

**Pull request merged**
