### PR TITLE
feat: innitial 2021_11_03 ragexe support

### LINKED ISSUE #3679: [Feature Request] new packet to use skill id 2036 GC_ROLLINGCUTTER
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: latest

* **Server**: all

* **Bug Report / Feature Request**:
new packet to use skill 2036
'0B10' => ['start_skill_use', 'v2 a4', [qw(skillID lv targetID)]],
'0B11' => ['stop_skill_use', 'v', [qw(skillID)]],
in ragexe client , press key and hold it , '0B10' will be sent then skill id 2036 keep rolling ,  release the key ,  '0B11' will be sent ,then skill id 2036 stop rolling

```
send 10 0b f4 07 05 00 00 00 00 00
send 11 0b f4 07
```
it's tested, can cast skill 2036 and stop it.

* **Summary**:

can anyone add a new way to cast this skill?

### PR DESCRIPTION
**Pull request by alisonrag**
Features:
- Added support to hotkey macro (skill start/end) [tested only in rolling cutter] https://www.youtube.com/watch?v=NSXSH6XmLxk
- added sss and sst command to hotkey macro
- Added function to auto select Poisonous Weapon
- Added poison command to select Poisonous Weapon https://irowiki.org/wiki/Poisonous_Weapon
- Added support to reputation UI https://www.youtube.com/watch?v=NDn7b1zdOe0
- Added basic support to 4th job name
- Added parse to 4th new stats
- Added new servertypes (RagexeRE_2020_07_23 and RagexeRE_2021_11_03.pm)
- Added new recvpackets (RagexeRE_2020_07_23 and RagexeRE_2021_11_03.pm)
- Added new sendMapLogin (23 bytes)
- Added support to captcha at wx interface and fixed some issues https://youtu.be/_5h3xqE6-lQ
- Fixed 09BB (storage_opened) unpack string

examples:
Rolling Cutter:
```
attackSkillSlot GC_ROLLINGCUTTER {
    lvl 5
    dist 1
    maxDist 2
    sp > 10
    aggressives
    stopWhenHit 0
    inLockOnly 0
    notInTown 0
    timeout 0
    disabled 0
    monsters
    notMonsters
    monstersCount
    maxAttempts 0
    maxUses 0
    target_hp
    isStartSkill 1
    target_whenStatusActive
    target_whenStatusInactive
    target_deltaHp
    isSelfSkill 0
    manualAI 0
}
```

autoPoison:
```
autoPoison 麻醉之毒

useSelf_skill GC_POISONINGWEAPON {
    lvl 5
    maxCastTime 0
    minCastTime 0
    sp > 50
    whenStatusInactive EFST_POISONINGWEAPON
    stopWhenHit 0
    inLockOnly 0
    notWhileSitting 0
    notInTown 0
    timeout 0
    disabled 0
    inInventory 麻醉之毒 > 0
    manualAI 0
}
```
image

reputation:
image

4th:
image
image

this fixes #3679

### CODE REVIEW

**Comment by alisonrag** [comment]
this fixes #3679

**Review by sctnightcore — APPROVED** [review]
LGTM

**Comment by ya4ept** [comment]
>  Added support to hotkey macro (skill start/end) [tested only in rolling cutter] https://www.youtube.com/watch?v=NSXSH6XmLxk

is this the correct link? I don't see anything about macro

**Comment by ya4ept** [comment]
need to update documentation:
https://openkore.com/wiki/autoPoison
https://openkore.com/wiki/attackSkillSlot (add `isStartSkill` condition)

**Comment by ya4ept** [comment]
@alisonrag let's replace `sss` command  with `ss start <id>` and `ss stop` ?

**Review by ya4ept — APPROVED** [review]

**Pull request merged**
