### PR TITLE
Compile perl 5.22

### PR DESCRIPTION
**Pull request by ya4ept**
this pull request - continues #2855:

> https://www.activestate.com/blog/faqs/what-is-the-status-of-perl-dev-kit-and-activeperl-pro-studio/
> ActiveState will not be updating PDK to work with versions of ActivePerl newer than 5.22.

Trying to compile openkore to use perl 5.22
We need:
- [x] compile start.exe
- [ ] compile wxstart.exe
- [x] compile XSTools.dll
- [x] compile NetRedirect.dll
- [ ] change logo ??
- [ ] change dll version number?

I use:
- Windows 10 x32
- ActivePerl-5.22.1.2201-MSWin32-x86-64int-299574
- ActiveState.Perl.Dev.Kit.Pro.v9.5.1.300018.x86

Unresolved issues:
1. XSTools.dll and NetRedirect.dll compiled with ActivePerl-5.22 - not working. We can compile them using Strawberry Perl.
2. Compiled wxstart.exe - does not work

### CODE REVIEW

**Comment by alisonrag** [comment]
now only miss to update the dlls based in pathfind and compile a wxstart

**Comment by ya4ept** [comment]
> now only miss to update the dlls based in pathfind and compile a wxstart

why?

**Comment by alisonrag** [comment]
> > now only miss to update the dlls based in pathfind and compile a wxstart
> 
> why?

the dlls from pull request dont use the new pathfind algo, also they are not compiled using the libflag so exes dont work if perl is not installed

**Comment by ya4ept** [comment]
I propose to add russian encode to start.exe: #2600

**Comment by alisonrag** [comment]
> I propose to add russian encode to start.exe: #2600

seems ok to me, we need to check if the following encodes are in start.exe:
China
Russia
Thailand

**Comment by alisonrag** [comment]
wx still running after close:
https://metacpan.org/pod/Wx::Perl::Packager#For-PerlApp-on-MS-Windows

**Comment by ya4ept** [comment]
Just run wxstart.exe and press the right button
изображение

**Comment by ya4ept** [comment]
> seems ok to me, we need to check if the following encodes are in start.exe:
1) sys.txt :  locale en start.exe:
изображение

2) sys.txt :  locale en wsstart.exe:
изображение

3) sys.txt :  locale ru start.exe:
изображение

4) sys.txt :  locale ru wxstart.exe:
изображение

**Comment by alisonrag** [comment]
thanks for the test, i will see what i can do

**Comment by alisonrag** [comment]
assert error in inventoryList shoud be fixed

**Comment by ya4ept** [comment]
> fix language in wx

nothing changed

**Comment by ya4ept** [comment]
The first press of the right button still shows an error:
изображение

the second press already shows the menu without errors

**Comment by ya4ept** [comment]
@alisonrag can you find a way to add a monospaced font to wxstart?

**Comment by ya4ept** [comment]
I suggest doing a `rebase onto master`
for testing new github actions

**Comment by ya4ept** [comment]
@alisonrag  can you run start.exe and close the window with a cross?
I get an error:
изображение

**Comment by alisonrag** [comment]
sorry i'm kind afk these days, maybe we will need to update deps/base

**Comment by alisonrag** [comment]
@ya4ept 
can u test language in wx?
my test:
image

**Comment by alisonrag** [comment]
here after last start update i can close in cross can u test this too?

**Comment by ya4ept** [comment]
> @ya4ept
> can u test language in wx?
> my test:

there have never been any problems in displaying the Russian interface. There is a problem when you receive an error connecting to a non-existent server. Error encoding does not match console encoding

> here after last start update i can close in cross can u test this too?

1) When i close start.exe i get the following error and the wxstart.exe process remains hanging in the task manager:
изображение
2) When i close wxstart.exe i get the following error:
изображение

**Comment by vutung2311** [comment]
How can I help on this one?

**Comment by alisonrag** [comment]
#3611

**Pull request closed without merging**
