### PR TITLE
Update Packet for client 20180704+

### PR DESCRIPTION
**Pull request by sctnightcore**
**Miss**
```
    packet(0x09f7,77); // ZC_PROPERTY_HOMUN_2
   packet(0x0a05,63); // ZC_ACK_ADD_ITEM_RODEX

```
https://github.com/HerculesWS/Hercules/pull/2126

### CODE REVIEW

**Comment by Nipodemos** [comment]
there is conflicts

**Comment by smallvill3** [comment]
Hey guys, im about to test 2018 server client from rAthena, would it be able to bot?

**Comment by sctnightcore** [comment]
@smallvill3  Maybe .

**Comment by AlexandreVitorino** [comment]
20151104a GGamerzRO : 
image
yaaa

**Comment by AlexandreVitorino** [comment]
packet_keys(0x47DA10EB,0x4B922CCF,0x765C5055);
	#elif PACKETVER > 20180307 // Clients after 2018-03-07bRagexeRE do not obfuscate packets anymore
		packet_keys(0x00000000,0x00000000,0x00000000);
	#elif PACKETVER > 20110817
		#error Unsupported packet version.
#endif

**Comment by Nipodemos** [comment]
this can be merged? @sctnightcore

**Comment by sctnightcore** [comment]
@Nipodemos  Noo ~~~

**Pull request closed without merging**
