### PR TITLE
Item renames

### PR DESCRIPTION
**Pull request by Henrybk**
This tries to achieve what was said in #350

### CODE REVIEW

**Comment by farrainbow** [comment]
Need to change kRO ST in the same way as in https://github.com/OpenKore/openkore/pull/375/commits/3d2e7d0a79832676ee89ea3b3230251d20f9dbfa.

**Comment by Henrybk** [comment]
This must be updated since others pull requests were merged

**Comment by Henrybk** [comment]
Updated to master and adapted new changes. Ready to test and merge.

**Comment by Henrybk** [comment]
This should be tested and merged soon as the more time it takes the more commits will have to be made due to bRO updates.

**Comment by Henrybk** [comment]
@flacrasec @farrainbow @allanon @itsrachelfish @emsjustin

**Comment by kaliwanagan** [comment]
@Henrybk we have a few conflicts that need to be addressed

**Comment by Henrybk** [comment]
@kaliwanagan The conflicts have been resolved

**Comment by kaliwanagan** [comment]
Here's hoping nothing breaks :D (we need to start doing a test suite)

**Pull request merged**
