### PR TITLE
revision of the console command "achieve"

### PR DESCRIPTION
**Pull request by ya4ept**
- added description to "help achieve" command
- rewrote the cmdAchieve function like cmdQuest
- replaced "ach_id" with "achievementID" for better code search

### CODE REVIEW

**Review by alisonrag — APPROVED** [review]

**Comment by alisonrag** [comment]
Is the documentation updated in wiki?

**Comment by ya4ept** [comment]
yes
https://openkore.com/wiki/achieve

**Comment by alisonrag** [comment]
nice ;D

**Comment by legokidd** [comment]
@alisonrag  maybe you can make a daily login claim for openkore

**Comment by alisonrag** [comment]
> @alisonrag maybe you can make a daily login claim for openkore

Attendance is implemented, but is not automatic, u can create a macro do claim every day in specific hour

**Comment by sctnightcore** [comment]
> @alisonrag maybe you can make a daily login claim for openkore

it easy to do it

**Pull request merged**
