### PR TITLE
[macroinclude.pl] Rewrited it totaly. The same but better.

### PR DESCRIPTION
**Pull request by Mortimal**

### CODE REVIEW

**Comment by kaliwanagan** [comment]
This looks really interesting, but I'd like @farrainbow or @Henrybk or @lututui to also check this out :)

@SabadyshynV what were the shortcomings of the original code that you were addressing in this PR?

**Comment by Henrybk** [comment]
@SabadyshynV eventMacro already has include command support (although not documented in the wiki)

**Comment by Nipodemos** [comment]
i think it is a good thing to merge, even if is less used

**Comment by lututui** [comment]
This must drop eventMacro support before merging

**Comment by Nipodemos** [comment]
i've pushed a commit that removes eventMacro support
anyone have anything against merging this?

**Pull request merged**
