### PR TITLE
FOR Privater server = add servertype FOR ClIENT 2017

### PR DESCRIPTION
**Pull request by sctnightcore**
# WAIT approved  !!
- [x] 1 = add rev rodex, achievement to Sakexe_0
- [x] 1.1 =add rev rodex, achievement to sT20151104a 
- [x] 2 = add send rodex, achievement to Sakexe_0
- [x] 2.1  = add send rodex, achievement to sT20151104a

- [x] 3.**UPDATE SERVERTYPE FOR CLIENT 2017 XD**

- [x] 3.1 add recvpackets to tables

```
RagexeRE_2017_01_25a: WORK!
RagexeRE_2017_05_17a : WORK! 
RagexeRE_2017_06_07c : dont have client
RagexeRE_2017_06_14b :WORK !

```
@moneyisgod 

//----------------------------------------------//
I want to fix bot for Korea - kRO: Sakray
But i do not ROFL

### CODE REVIEW

**Comment by alisonrag** [comment]
@sctnightcore 
what about this PR?

**Comment by sctnightcore** [comment]
I will add servertype for 2017 client In 2 weeks @alisonrag

**Comment by boom19** [comment]
I hope you could add 2004 classic ragnarok online!

**Comment by sctnightcore** [comment]
@boom19  GEPARD !

**Comment by boom19** [comment]
There is a way right? haha!

**Comment by sctnightcore** [comment]
= = @boom19  openkore dont Support GEPARD !

**Comment by icewafu05** [comment]
hi! is xkore 3 working in RO:Restart? thank you!

**Comment by lututui** [comment]
About 207-06-07c, this is the only one I could find: https://rathena.org/board/topic/106413-kro-full-client-2017-06-07-includes-bgm-rsu/

Didn't kRO have a ftp with all the clients?

**Comment by sctnightcore** [comment]
@lututui  ty sir 
I think to do only in rathena.org/board/forum/99-client-releases/ //unpack only 
If someone requests I made it. XD

**Comment by sctnightcore** [comment]
@alisonrag  @allanon  @lututui  @Henrybk  
reviews pls XD

**Comment by k1nt4r0** [comment]
hi @sctnightcore i trying the client 2017-01-25a but i got this
```
Connect failed, something is wrong with the login settings:
version: 27
master_version: 1
serverType: kRO_RagexeRE_2017_01_25a
```

i active the cryptkeys but still like that

**Comment by sctnightcore** [comment]
```
version: 27 << 
master_version: 1 <<
```

link server?

**Comment by k1nt4r0** [comment]
@sctnightcore [here](https://www.novaragnarok.com/)

**Comment by sctnightcore** [comment]
@k1nt4r0  gepard ?

**Comment by k1nt4r0** [comment]
@sctnightcore no, if gepard it will say
```unknown packet ABCD```

**Comment by sctnightcore** [comment]
well i will check it @k1nt4r0

**Comment by moneyisgod** [comment]
@sctnightcore check if it uses clientHash

**Comment by k1nt4r0** [comment]
@sctnightcore how i should send it to u?

@moneyisgod i try to extract the recvpackets, but always fail so i use the recvpackets from @sctnightcore and i use NEMO client patcher to get the client hash but still cant connected

**Comment by sctnightcore** [comment]
ok XD  @k1nt4r0  @moneyisgod

**Comment by k1nt4r0** [comment]
@sctnightcore ohh, RagnaShield haha
sorry @sctnightcore, cause as i know if the RO use a shield, the logo will appear when start the game XD

**Comment by sctnightcore** [comment]
@k1nt4r0  NP !

**Comment by sctnightcore** [comment]
i will back to fix all rev 2015-2017  on 2 week ty sir

**Pull request closed without merging**
