### PR TITLE
[idRO_RE] Fix network work only x1,x3

### PR DESCRIPTION
**Pull request by sctnightcore**
Issues : #1392

```
[How to use bot with x1]
1.Run client 
2. control/config.txt
    XKore > XKore 1
3. select  server : [Indonesia - idRO: Midgard,Asgard ,Valhalla]
4.Run admin > Openkore 

```

### CODE REVIEW

**Comment by RaynV** [comment]
My first slot character gone / not detected using this version ( Xkore0 )

**Comment by sctnightcore** [comment]
@RaynV x0 ?

**Comment by vodkaskywalker** [comment]
@sctnightcore 
just checked your recvpackets.txt commit. seems all the packets are updated to the newest client but all  of packets' MinLength and ReplayFactor are missing.

received character packet should be something like this
`-099D -1 4 0`
in the newest commit 
`099D -1`

**Comment by sctnightcore** [comment]
How do you use xkore 0? @vodkaskywalker 


I can update the recvpacket if you want.

**Comment by resistz** [comment]
when i opened client after open openkore first, the client ragexe crash, any solution?

**Comment by Razalka** [comment]
Openkore Run as Admin and still "Unable to Inject the Dll"
any help ?

**Comment by sctnightcore** [comment]
@Razalka  RunAdmin

**Comment by Daizengar** [comment]
@sctnightcore already run as administrator but still unable to inject, I use windows
screenshot_1
 10 64bit

**Pull request merged**
