### PR TITLE
FIX Eq in idRO_RE

### PR DESCRIPTION
**Pull request by sctnightcore**
ISSUES : #1299 , #1707

### CODE REVIEW

**Comment by c4c1n6kr3m1** [comment]
my bot is years late, but 0998 worked
may be that guy made a mistake, he didn't show his file.

**Comment by banirizal** [comment]
send_equip 0998
send_equip 00A9

I'm not make an any mistake, i try different packet with 0998 or 00A9, still keep disconnect on idRO renewal.

**Comment by sctnightcore** [comment]
@banirizal  sniff packet from client ! 
Now , i dont have client idRO

**Comment by banirizal** [comment]
@sctnightcore i got 87 01 43 5D 05 00   from smartsniff 
or 98 09 89 00 22 00 00 00  with size 8 on wpe, witch one the right one?

I think 98 09 it's near with 0998 ?

Now IdRO only connect just in Indonesia IP, not for international IP

**Comment by sctnightcore** [comment]
0998 I think @banirizal

**Comment by lututui** [comment]
87 01 43 5D 05 00 is 0187
98 09 89 00 22 00 00 00 is 0998

**Pull request merged**
