### PR TITLE
Fix if block inside while block eventMacro

### PR DESCRIPTION
**Pull request by Henrybk**

### CODE REVIEW

**Comment by Henrybk** [comment]
Have you confirmed it is working @phamtrong204 ?

**Comment by phamtrong204** [comment]
Yes, work like a champion!

**Comment by allanon** [comment]
This works for the `test_wi` macro below, but fails for the `test_ww` macro:
```
macro test_wi {
  $i = 0
  while ($i < 3) {
    log $i
    $j = 0
    if ($j < 3) {
      log $i.$j +
    }
    if ($j > 3) {
      log $i.$j -
    }
    $i++
    pause 0.1
  }
}

macro test_ww {
  $i = 0
  while ($i < 3) {
    log $i
    $j = 0
    while ($j < 3) {
      log $i.$j
      $j++
      pause 0.1
    }
    $i++
    pause 0.1
  }
}
```

**Comment by Henrybk** [comment]
Thanks for pointing that out @allanon 
It should be working after the last commit.

**Comment by allanon** [comment]
Competing implementation, which handles while-in-while as well as if-in-while cases: https://github.com/OpenKore/openkore/pull/1095

**Pull request closed without merging**
