### PR TITLE
[2017-06-07] bRO connection update

### PR DESCRIPTION
**Pull request by lututui**

### CODE REVIEW

**Comment by Henrybk** [comment]
@lututui Would you please resolve the conflicts so it can be merged? Thanks! :P

**Comment by flacrasec** [comment]
Thank you for this work it is working just fine! =)

**Comment by lututui** [comment]
@Henrybk sorry, dun!

**Comment by incicon131** [comment]
A new philippine ragnarok online has been relaunched in Philippines. I think it's KRO official server because it's under gravity and extreme. Can someone help me with servertxt config so that I can bot? It's still on CBT today..may be tom or day after it will be OBT. Here's the website https://www.ragnarokonline.com.ph/

**Comment by salabusab** [comment]
Multiple Objects (4) / 5280 ft / 1609.34
I....can't......make....it...... / 5279 ft 11.75 inches / 1609.34 m

Quitter's finish line. / 5279 ft 11.5 inches / 1609.33 m

as high as I'll go / 5279 ft 8 inches / 1609.24 m

one foot less than a mile / 5279 ft / 1609.04 m

my grandfather's grave/denver / 5274 ft / 1607.52 m

Mount Kenya / 5199 ft / 1584.66 m

one mile tower / 5196 ft 1.125 inches / 1583.77 m

I....can't......make....it...... / 5179 ft 11.75 inches / 1578.86 m

Average Ninja Levitatin height / 5100 ft 7.5 inches / 1554.67 m

Metric Mile / 4921 ft 0.125 inches / 1499.92 m

Halti Fell, Finland / 4343 ft 9.75 inches / 1323.99 m

Lake Tear in the Clouds, highest source of Hudson River / 4293 ft / 1308.51 m

Table Mountain, Cape Town, South Africa / 3562 ft 11.75 inches / 1086 m

Irelands highest mountain - Carrauntoohil / 3405 ft 6.125 inches / 1038 m

One Kilometer / 3280 ft 11 inches / 1000.02 m

Highest tightrope walk Christian Schou, Kjerag Norway / 3280 ft / 999.74 m

this is long / 3277 ft 6.5 inches / 998.99 m

Angel Falls, Venezuela / 3215 ft / 980 m

Scafell Pike, the tallest mountain in England / 3208 ft 7.75 inches / 978 m

worlds tallest tree / 2870 ft 8.75 inches / 875 m

Multiple Objects (2) / 2717 ft / 828.14 m
Burj Al-Arab / 2690 ft 3.5 inches / 820 m

Burj Dubai / 2684 ft / 818.08 m

Multiple Objects (2) / 2683 ft 8.5 inches / 817.99 m
Multiple Objects (2) / 2640 ft / 804.67 m
the distance you fly away when hitted by Chuck Norris / 2478 ft 0.5 inches / 755.31 m

Highest point in Belgium / 2400 ft / 731.52 m

Warsaw Radio Mast / 2120 ft 8.125 inches / 646.38 m

CN Tower, Toronto (ON), Canada / 1815 ft 5 inches / 553.34 m

Ostankino Tower, Moscow / 1762 ft / 537.06 m

Height of World Trade Center (including spire) / 1727 ft / 526.39 m

Taipel 101 Tower, Taiwan / 1670 ft / 509.02 m

Half a kilometer / 1640 ft 0.5 inches / 499.88 m

Mont Blanc highest mountain in Europe / 1578 ft / 480.97 m

Oriental Pearl Tower (Dongfang Mingzhu) Shang Hai / 1499 ft 4.125 inches / 457 m

Petronas Towers, Kuala Lumpur, Malaysia / 1483 ft / 452.02 m

Multiple Objects (2) / 1450 ft / 441.96 m
Shanghai World Financial Center / 1390 ft 0.5 inches / 423.68 m

Philippe Petite's 1974 tightrope walk between the two towers of the World Trade Center Towers / 1368 ft / 416.97 m

One Quarter Mile / 1320 ft / 402.34 m

drag race track / 1318 ft 10.75 inches / 402 m

shortest commercial airstrip (Saba Island) / 1312 ft 4.125 inches / 400 m

Black Mountain in Belfast Northern Ireland / 1275 ft / 388.62 m

distance from earth to moon / 1261 ft / 384.35 m

Empire State Building, New York / 1250 ft / 381 m

TV Tower Riga / 1246 ft 8.5 inches / 380 m

1234 Ft. / 1234 ft / 376.12 m

Fernsehturm Berlin / 1207 ft 4.125 inches / 368 m

Stratosphere Tower, Las Vegas / 1149 ft / 350.22 m

Tallest Bridge / 1122 ft / 341.99 m

USS Ronald Reagan CVN 76 / 1101 ft 2 inches / 335.64 m

Tokyo-Tower / 1092 ft 0.5 inches / 332.85 m

Multiple Objects (2) / 1092 ft / 332.84 m
Auckland Sky Tower / 1076 ft 1.5 inches / 328 m

Eiffel Tower height (including antenna) / 1063 ft / 324 m

Chrysler Building, New York / 1047 ft / 319.13 m

One hundred thousand stacked pound coins / 1033 ft / 314.86 m

Tv Mast - Ligfordrum, Strabane, Co Tyrone, Ireland / 1002 ft 4 inches / 305.51 m

Centrepoint Tower (Sydney) / 1000 ft 7.75 inches / 305 m

six gravity bong rips / 1000 ft 0.25 inches / 304.81 m

Multiple Objects (2) / 984 ft 3.125 inches / 300 m
Eiffel Tower / 982 ft / 299.31 m

Comcast Center / 975 ft / 297.18 m

Highest Concrete Dam - Dixence, Switzerland / 935 ft / 284.99 m

Prudential Tower / 906 ft 9.75 inches / 276.4 m

RMS Titanic / 882 ft 9 inches / 269.06 m

Continuous Bic Biro Line / 880 ft / 268.22 m

Approximate height of one million pixels / 868 ft 0.5 inches / 264.58 m

Rockefeller Center, NYC / 849 ft 8.75 inches / 259 m

USX Tower, Pittsburgh Pa / 841 ft / 256.34 m

Multiple Objects (2) / 800 ft / 243.84 m
Highest bungy jump / 765 ft / 233.17 m

RSA Battle House Tower, Mobile, AL / 745 ft / 227.08 m

Øresundsbron Bridge / 669 ft 3.5 inches / 204 m

Rollerskater Chris Haffey grinds a 666 foot rail. / 666 ft / 203 m

Height of Trump Tower (NY) / 664 ft / 202.39 m

1 Furlong (1/8 mile) / 660 ft / 201.17 m

Darth Vader / 656 ft 2.125 inches / 200 m

Telstra Tower / 640 ft 0.5 inches / 195.08 m

Turning torso, Malmö (Sweden) / 624 ft 8.125 inches / 190.4 m

Euromast Rotterdam, Highest Tower in Holland / 606 ft 11.5 inches / 185 m

Space Needle / 605 ft / 184.4 m

Kaknästornet (including antenna) / 557 ft 8.75 inches / 170 m

Washington Monument / 555 ft / 169.16 m

One tenth of the way there! / 528 ft / 160.93 m

Blackpool Tower / 518 ft / 157.89 m

The Kölner Dom, Cologne, Germany / 516 ft 4.125 inches / 157.38 m

World's Tallest Natural Lighthouse, Mazatlán, México. / 515 ft / 156.97 m

The Kaknäs tower, stockholm / 508 ft 0.5 inches / 154.85 m

Tallest Recorded Tree / 500 ft / 152.4 m

"A Eucalyptus regnans at Mt. Baw Baw, Victoria, Australian, is believed to have measured 143 m (470 ft.)1885. Formerly, another Australian eucalyptus, at Watts River, Victoria. almost certainly had been over 150 m (492 ft.) tall." / 492 ft 1.5 inches / 150 m

Great Pyramid of Giza / 480 ft 11.5 inches / 146.6 m

The largest Sausage the world has ever seen / 473 ft 9 inches / 144.4 m

City-Hochhaus - Highest building in Leipzig, Germany / 467 ft 0.5 inches / 142.35 m

Highest Roller Coaster Kingda Ka / 465 ft / 141.73 m

Kingda Ka, roller coaster, Six Flags, Jackson Township, New Jersey, USA / 456 ft / 138.99 m

Great Pyramid of Giza / 455 ft 4.5 inches / 138.8 m

St Peter's Basilica in the Vatican / 448 ft 0.75 inches / 136.57 m

Stephansdom (Vienna) / 447 ft 6.125 inches / 136.4 m

Tallest unsupported flagpole Ashbagad, Turkmenistan / 436 ft / 132.89 m

Multiple Objects (2) / 420 ft / 128.02 m
Pirelli tower (Pirellone) / 416 ft 8.125 inches / 127 m

The Eiffel Tower / 410 ft 1.125 inches / 125 m

The Spire in Dublin / 397 ft 7.5 inches / 121.2 m

Ushiku Daibutsu Bronze Buddha Statue / 394 ft / 120.09 m

Height of 'The Spike' monument - O'Connell Street, Dublin, Ireland / 393 ft 8.5 inches / 120 m

The Spire of Dublin / 393 ft / 119.79 m

Hyperion, a large california redwood / 379 ft / 115.52 m

Domtower, highest church in the Netherlands / 368 ft 6.125 inches / 112.32 m

Multiple Objects (2) / 368 ft / 112.17 m
Multiple Objects (2) / 367 ft 6 inches / 112.01 m
Domtoren, Utrecht, NL / 367 ft 5.5 inches / 112 m

Multiple Objects (2) / 363 ft / 110.64 m
one trillion dollars in $1000 bills / 357 ft 7.125 inches / 108.99 m

Stockholm City Hall / 347 ft 9.125 inches / 106 m

Berner Münster, Switzerland / 330 ft 0.5 inches / 100.6 m

Campanile San Marco, Venize, Italy / 324 ft 9.5 inches / 99 m

Martini Tower (Groningen, The Netherlands) / 318 ft 2.75 inches / 97 m

Big Ben / 314 ft / 95.71 m

Millennium Force, roller coaster, Cedar Point, Sandusky, Ohio, USA / 310 ft / 94.49 m

UC Berkeley Camponile / 307 ft / 93.57 m

stockholm globe inner height / 278 ft 10.5 inches / 85 m

Capital Tower, Cardiff / 262 ft / 79.86 m

Airbus A380-800 wingspan / 261 ft 10 inches / 79.81 m

Robert E. Lee Seqoia (the largest tree in the world) / 254 ft / 77.42 m

Hallgrímskirkja, tallest church in Iceland / 244 ft / 74.37 m

Great Sphynx of Giza (largest monolith statue in the world) / 241 ft / 73.46 m

Helsinki Stadium Tower / 236 ft 0.125 inches / 71.94 m

Longest stalagmite Zhijin Cave Zhejiang province China / 230 ft / 70.1 m

St. George's Med. School. Jenner Wing / 223 ft 3 inches / 68.05 m

Magnum XL-200, roller coaster, Cedar Point, Sandusky, Ohio, USA / 205 ft / 62.48 m

Scott Monument, Princes Street Gardens in Edinburgh / 200 ft 6 inches / 61.11 m

Height of the Cloverfield monster / 196 ft 11 inches / 60.02 m

Biggest snowman / 196 ft 1.125 inches / 59.77 m

Multiple Objects (2) / 184 ft / 56.08 m
Multiple Objects (2) / 183 ft 8.5 inches / 55.99 m
Tallest Totem Pole / 180 ft 3 inches / 54.94 m

Longest BLT ever / 179 ft 2 inches / 54.61 m

A barrel ride over Niagara Falls / 173 ft / 52.73 m

Piling of Burj Dubai / 164 ft 0.5 inches / 50 m

Niagara Falls (Horseshoe or Canadian Falls) / 158 ft 1.5 inches / 48.2 m

Statue of Liberty / 152 ft 6.5 inches / 46.49 m

Nelson's Column / 151 ft / 46.02 m

The micropop.se flag pole in Sweden / 150 ft / 45.72 m

blanca peak / 143 ft / 43.59 m

Invercargill water tower / 139 ft 5.125 inches / 42.5 m

The Freedom Monument (Latvia, Riga) / 137 ft 9.5 inches / 42 m

Worlds Tallest Snowman / 122 ft / 37.19 m

Rundetaarn - Roundtower Copenhagen / 114 ft 2.125 inches / 34.8 m

statue of liberty / 111 ft / 33.83 m

michael woods fell from / 103 ft 0.125 inches / 31.4 m

Multiple Objects (4) / 100 ft / 30.48 m
Tallest Lego Tower / 96 ft 1 inches / 29.29 m

Tallest Lego Tower Legoland - Windsor, Great Britain / 96 ft / 29.26 m

Brandenburger Gate (Berlin) / 85 ft 0.5 inches / 25.92 m

Height of my disappointment with this / 80 ft 9 inches / 24.61 m

Highest skateboard jump Danny Way / 79 ft / 24.08 m

Multiple Objects (2) / 78 ft 0.75 inches / 23.79 m
World's Longest Pencil / 76 ft / 23.16 m

Worls longest pencil after sharpening / 75 ft 6 inches / 23.01 m

Ocracoke Lighthouse / 75 ft / 22.86 m

Largest wave surfed by Pete Cabrinha Maui Hawaii January 10, 2006 / 72 ft / 21.95 m

King Kong's height (from official movie poster) / 50 ft / 15.24 m

My Apartment / 40 ft 8 inches / 12.4 m

Green MOster (Fenway Park) / 37 ft 2 inches / 11.33 m

Word Record shallow dive in to one foot of water Professor Splash, Dec 15, 2007 / 35 ft / 10.67 m

JAMES BROM / 30 ft 4 inches / 9.25 m

Arcadia University Art Gallery / 30 ft / 9.14 m

Multiple Objects (2) / 25 ft / 7.62 m
Height of the World's Highest Loogie Spit / 22 ft 9 inches / 6.93 m

Tony Utegaard's House / 22 ft / 6.71 m

Men's indoor pole vault record (Sergey Bubka, Ukraine, 1985) / 20 ft 2.125 inches / 6.15 m

King Kong's height (in the jungle) / 19 ft / 5.79 m

Average Height of Male Giraffe / 18 ft / 5.49 m

Average Male Giraffe / 17 ft / 5.18 m

Women's pole vault record / 16 ft 6.75 inches / 5.05 m

Multiple Objects (2) / 16 ft / 4.88 m
Ruler / 12 ft / 3.66 m

Average Carp Rod / 11 ft 9.5 inches / 3.59 m

Marianne & Matt / 11 ft 6 inches / 3.51 m

yahoo's layoff check / 10 ft 10 inches / 3.3 m

Ryan on stilts / 10 ft 6.25 inches / 3.21 m

Multiple Objects (2) / 10 ft / 3.05 m
Robert Pershing Wadlow / 8 ft 11.125 inches / 2.72 m

Shipping container standard / 8 ft 6.125 inches / 2.59 m

World's Tallest Man / 8 ft 5 inches / 2.57 m

Tallest Woman Zeng Jinlian, Hunan, China / 8 ft 1. / 2.48 m

Highest official horse jump with rider / 8 ft 1.25 inches / 2.47 m

High jump world record / 8 ft 0.5 inches / 2.45 m

Average Height of a one story room / 8 ft / 2.44 m

Yao Ming / 7 ft 11 inches / 2.41 m

De-Fen Yao (tallest living woman) / 7 ft 9 inches / 2.36 m

Gheorghe Mureşan / 7 ft 7 inches / 2.31 m

André the Giant / 7 ft 4.5 inches / 2.25 m

Gallery door / 7 ft 3. / 2.22 m

tim duncan / 7 ft / 2.13 m

Multiple Objects (2) / 6 ft 10 inches / 2.08 m
Thomas Koenis / 6 ft 9.75 inches / 2.08 m

Multiple Objects (2) / 6 ft 9 inches / 2.06 m
Kristaps Vilde / 6 ft 7.75 inches / 2.03 m

Multiple Objects (2) / 6 ft 7.5 inches / 2.02 m
Peter Crouch / 6 ft 7 inches / 2.01 m

Average Height of NBA Player / 6 ft 6.75 inches / 2 m

Darth Vader / 6 ft 6.5 inches / 1.99 m

Brad Kaloupek / 6 ft 6.25 inches / 1.99 m

Multiple Objects (3) / 6 ft 6 / 1.98 m
Multiple Objects (2) / 6 ft 5.75 inches / 1.97 m
Multiple Objects (4) / 6 ft 5.5 inches / 1.97 m
Multiple Objects (4) / 6 ft 5 inches / 1.96 m
Multiple Objects (6) / 6 ft 4.75 inches / 1.95 m
Multiple Objects (9) / 6 ft 4.5 inches / 1.94 m
Conan O'Brien / 6 ft 4.25 inches / 1.94 m

Multiple Objects (10) / 6 ft 4 / 1.93 m
Multiple Objects (2) / 6 ft 3.75 inches / 1.92 m
Multiple Objects (6) / 6 ft 3.5 inches / 1.92 m
Multiple Objects (2) / 6 ft 3.25 inches / 1.91 m
Multiple Objects (13) / 6 ft 3 inches / 1.91 m
Multiple Objects (10) / 6 ft 2.75 inches / 1.9 m
Multiple Objects (5) / 6 ft 2.5 inches / 1.89 m
Multiple Objects (4) / 6 ft 2.25 inches / 1.89 m
Multiple Objects (19) / 6 ft 2 inches / 1.88 m
Karl Lind / 6 ft 1.75 inches / 1.87 m

Multiple Objects (6) / 6 ft 1.5 inches / 1.87 m
Andrew Wetzel / 6 ft 1.25 inches / 1.86 m

Multiple Objects (11) / 6 ft 1.125 inches / 1.86 m
Multiple Objects (11) / 6 ft 1 / 1.85 m
Average Height Dutch Men / 6 ft 0.75 inches / 1.85 m

Multiple Objects (7) / 6 ft 0.5 inches / 1.84 m
Multiple Objects (3) / 6 ft 0.25 inches / 1.84 m
Multiple Objects (5) / 6 ft 0.125 inches / 1.83 m
Multiple Objects (21) / 6 ft / 1.83 m
Multiple Objects (4) / 5 ft 11.75 inches / 1.82 m
Multiple Objects (7) / 5 ft 11.5 inches / 1.82 m
Multiple Objects (3) / 5 ft 11.25 inches / 1.81 m
Multiple Objects (4) / 5 ft 11.125 inches / 1.81 m
Multiple Objects (14) / 5 ft 11 inches / 1.8 m
Multiple Objects (16) / 5 ft 10.75 inches / 1.8 m
Multiple Objects (8) / 5 ft 10 / 1.79 m
Multiple Objects (2) / 5 ft 10.25 inches / 1.78 m
Tim / 5 ft 10.125 inches / 1.78 m

Multiple Objects (17) / 5 ft 10 inches / 1.78 m
Multiple Objects (3) / 5 ft 9.75 inches / 1.77 m
Multiple Objects (3) / 5 ft 9.5 inches / 1.77 m
Multiple Objects (4) / 5 ft 9.25 inches / 1.76 m
Multiple Objects (6) / 5 ft 9.125 inches / 1.76 m
Multiple Objects (11) / 5 ft 9 inches / 1.75 m
Multiple Objects (9) / 5 ft 8.75 inches / 1.75 m
Multiple Objects (10) / 5 ft 8.5 inches / 1.74 m
Multiple Objects (2) / 5 ft 8.25 inches / 1.73 m
Mateusz więcław / 5 ft 8.125 inches / 1.73 m

Multiple Objects (13) / 5 ft 8 inches / 1.73 m
Multiple Objects (2) / 5 ft 7.75 inches / 1.72 m
Multiple Objects (5) / 5 ft 7. / 1.71 m
Multiple Objects (3) / 5 ft 7.25 inches / 1.71 m
Multiple Objects (8) / 5 ft 7 inches / 1.7 m
Multiple Objects (8) / 5 ft 6. / 1.7 m
Multiple Objects (6) / 5 ft 6.5 inches / 1.69 m
Chelsea Kent / 5 ft 6.25 inches / 1.68 m

Multiple Objects (4) / 5 ft 6.125 inches / 1.68 m
Multiple Objects (11) / 5 ft 6 / 1.68 m
Multiple Objects (3) / 5 ft 5.75 inches / 1.67 m
Multiple Objects (12) / 5 ft 5.5 inches / 1.66 m
Rico Casanova / 5 ft 5.25 inches / 1.66 m

Multiple Objects (8) / 5 ft 5 inches / 1.65 m
Multiple Objects (2) / 5 ft 4.75 inches / 1.64 m
Multiple Objects (6) / 5 ft 4.5 inches / 1.64 m
Multiple Objects (5) / 5 ft 4. / 1.63 m
Multiple Objects (3) / 5 ft 4.125 inches / 1.63 m
Multiple Objects (9) / 5 ft 4 inches / 1.63 m
Multiple Objects (4) / 5 ft 3.75 inches / 1.62 m
Multiple Objects (6) / 5 ft 3. / 1.61 m
Multiple Objects (9) / 5 ft 3 inches / 1.6 m
Multiple Objects (4) / 5 ft 2.5 inches / 1.59 m
Me / 5 ft 2.125 inches / 1.58 m

Multiple Objects (7) / 5 ft 2 inches / 1.57 m
Multiple Objects (2) / 5 ft 1. / 1.57 m
Multiple Objects (3) / 5 ft 1.5 inches / 1.56 m
Multiple Objects (9) / 5 ft 1.125 inches / 1.55 m
Multiple Objects (4) / 5 ft 1 inches / 1.55 m
KENNETH WEE FROM SINGAPORE / 5 ft 0.5 inches / 1.54 m

Multiple Objects (8) / 5 ft / 1.52 m
Multiple Objects (2) / 4 ft 11.5 inches / 1.51 m
Gianluca Santacroce / 4 ft 11.125 inches / 1.5 m

Chris bush / 4 ft 11 inches / 1.5 m

Amy W (AGE 13) Height / 4 ft 10.25 inches / 1.48 m

Leah - Shortest girl at school / 4 ft 10 inches / 1.47 m

Randi K Babino / 4 ft 9 inches / 1.45 m

World’s longest legs, Svetlana Pankratova / 4 ft 6 / 1.37 m

Marie Wakan / 4 ft 5 inches / 1.35 m

Olivier Taillon / 4 ft 3.125 inches / 1.3 m

Emmanuel Lewis aka Webster / 4 ft 3 inches / 1.3 m

My snowboard / 4 ft 0.75 inches / 1.24 m

DeLorean DMC-12 (Doors closed) / 3 ft 8.75 inches / 1.14 m

residential mailbox post / 3 ft 8 inches / 1.12 m

Eric the Midget of the Howard Stern Show / 3 ft 5 inches / 1.04 m

Multiple Objects (2) / 3 ft 3.125 inches / 99.4 cm
Highest bunny Hop Seth Kimbrough, Orlando, USA / 3 ft 0. / 93.3 cm

Multiple Objects (2) / 3 ft / 91.4 cm
Max Schwerin / 2 ft 10 inches / 86.4 cm

Multiple Objects (3) / 2 ft 5 / 73.7 cm
Manneken Pis (Belgium,Brussels) / 2 ft 0.125 inches / 61.3 cm

NewBornBaby / 1 ft 8.5 inches / 52.1 cm

A3 portrait / 1 ft 4.5 inches / 41.9 cm

Multiple Objects (2) / 1 ft 3 inches / 38.1 cm
plastic water bottle / 1 ft 0.25 inches / 31.1 cm

Multiple Objects (3) / 1 ft / 30.5 cm
Distance light travels in a nanosecond / 11.75 inches / 29.8 cm

Rugby ball length / 11.125 inches / 28.3 cm

Jay's Left Foot / 11 inches / 27.9 cm

statue of the Colonel Sanders / 10.25 inches / 26 cm

Jenn's Size 9 foot / 9.75 inches / 24.8 cm

Multiple Objects (2) / 9 inches / 22.9 cm
A Typical 20 oz (591 mL) bottle / 8.5 inches / 21.6 cm

Evian 75cl Waterbottle / 8.25 inches / 21 cm

8" Floppy Disk / 8 inches / 20.3 cm

Aurélie Fornara's finger! / 7 inches / 17.8 cm

Length of Pierre's pencil / 6.75 inches / 17.1 cm

My pencil / 6.5 inches / 16.5 cm

Multiple Objects (2) / 6 inches / 15.2 cm
50€ Note / 5.5 inches / 14 cm

5.25" Floppy Disk / 5.25 inches / 13.3 cm

Coca-Cola can / 5 inches / 12.7 cm

Multiple Objects (3) / 4.5 inches / 11.4 cm
My tea cup / 4.25 inches / 10.8 cm

Multiple Objects (2) / 4.125 inches / 10.5 cm
Multiple Objects (2) / 3.75 inches / 9.5 cm
Multiple Objects (5) / 3.5 inches / 8.9 cm
Multiple Objects (2) / 3.25 inches / 8.3 cm
Multiple Objects (2) / 3 inches / 7.6 cm
Small BIC Lighter / 2.5 inches / 6.4 cm

gareths finger / 2.25 inches / 5.7 cm

Rubik's cube / 2.125 inches / 5.4 cm

Amy (10 months)'s middle finger / 1.75 inches / 4.4 cm

German Stamp / 1.5 inches / 3.8 cm

Multiple Objects (2) / 1.25 inches / 3.2 cm
Multiple Objects (3) / 0.75 inches / 1.9 cm
Multiple Objects (3) / 0.5 inches / 1.3 cm
Multiple Objects (2) / 0.25 inches / 0.6 cm
One Mile Scroll

Which is highest when stacked, a million dollar bills or a thousand Robin Day Polypropylene Chairs?

The One Mile Scroll transforms virtual space into an actual, physical distance. Take your computer for a scroll. Participate and add heights of things. Please only add the vertical heights. Be sure to check your measurements (with Google or other service). Once submitted entries can only be modified or deleted by site admin.

The site was published to coincide with "Extra Medium" at Arcadia University Art Gallery Philadelphia September 2008. It was assembled by Jeffery Vaska who transformed an unrealized project into an ongoing project - thank you for confirming that the Eiffel Tower is exactly 1224576 pixels high.

~ Daniel Eatock

Scale: 1 inch = 96 pixels

Built with Indexhibit

Submit Object

Name


Imperial    Metric* 

Feet

Inches

Fraction

Submit

Heights are visible as you input them but need to be approved at a later time.

* Converted to imperial measurements.

Popular Destinations

Highest tightrope walk

Petronas Towers

Eifel Tower

Sears Tower

Empire State Building

Longest Bungy Jump

Tallest Redwood Tree

Free dive record

Statue of Liberty

Arcadia Art Gallery

Tallest man

Tallest woman

**Pull request merged**
