### PR TITLE
Updating packet tables and keys for iRO Renewal

### PR DESCRIPTION
**Pull request by delawr0190**
20180816 maintenance.

### CODE REVIEW

**Comment by delawr0190** [comment]
@lobocop Great!  Glad I could help.  :)

**Comment by pointzero2** [comment]
anyone can help me with the timeout issue with kafra storage :D

**Comment by pointzero2** [comment]
image
everytime i talk to kafra this happens

**Comment by c4c1n6kr3m1** [comment]
because new packet , which make recvpacket larger ,@Nipodemos, his tool work only if the size is equal

**Comment by Fadreus** [comment]
in iRO, after this patch there is times when you changed maps, it will disconnected & when you relogging it will give option where to spawn due to map bugged.

Not openkore.

**Comment by Fadreus** [comment]
in iRO, after this patch there is times when you changed maps, it will disconnected & when you relogging it will give option where to spawn due to map bugged.

Not openkore, it's iRO.

**Comment by bunnyy00** [comment]
npppc
@Fadreus I have downloaded the latest version but still have this problem.

**Comment by allanon** [comment]
:+1:

**Pull request merged**
