### PR TITLE
[2018-11-01] iRO ReStart update

### PR DESCRIPTION
**Pull request by alisonrag**
- [ ] QA Review

This pull request was auto-generated by automated-update: https://github.com/alisonrag/automated-openkore-tables-update

### CODE REVIEW

**Comment by KamalAdli** [comment]
tq @alisonrag

**Comment by c4c1n6kr3m1** [comment]
double 0821 on recvpackets

**Comment by paolopaz** [comment]
thanks @alisonrag, does this also work for renewal?

**Comment by sparkker** [comment]
renewal pls :)

**Comment by alisonrag** [comment]
@paolopaz @sparkker @Fadreus 
can some of you give the update datetime of renewall and restart? with gmt, i'm from brazil

**Comment by paolopaz** [comment]
For renewal, it's 3pm - 10pm Brazil time (11am - 6pm PST)

**Comment by alisonrag** [comment]
is restart tuesday and renewall wednesday?

**Comment by paolopaz** [comment]
Renewal is Thursday, @alisonrag, I think restart is Wednesday

**Comment by alisonrag** [comment]
thanks, i will create a cron job to automatic update tables

**Comment by paolopaz** [comment]
Thank you!

**Comment by dezenhando** [comment]
Renewal updates?

**Comment by alisonrag** [comment]
@dezenhando
Already updated in #2474

**Comment by jourlez** [comment]
Updates started today (wednesday) 4 hours and 32 minutes ago (11am - 6pm PST) @alisonrag

**Comment by Fadreus** [comment]
@jourlez Openkore only can be updated after maintenance LOL.
We don't have time machine here.
IDK where Doreamon had gone too.

**Pull request merged**
