### PR TITLE
Updating packet tables and keys for iRO (Chaos and Restart)

### PR DESCRIPTION
**Pull request by delawr0190**
New tables.

### CODE REVIEW

**Comment by delawr0190** [comment]
What server?

I only play renewal and these work fine for me. I’m using these files on master.

**Comment by Fadreus** [comment]
@Rovejoe Use latest version.

**Comment by Rovejoe** [comment]
@delawr0190 iro maybe i should download @Fadreus yeah trying ..

**Comment by delawr0190** [comment]
@alisonrag I generated this last night. Can you confirm that this isn’t working on Restart? I’m unable to test that server.

**Comment by Nipodemos** [comment]
@Fadreus or anyone

if anyone can test and confirm that is working on iRO restart, we'll merge this

**Comment by Fadreus** [comment]
Not playing RE:Start but it can log in & move around.
Suppose to have no problem with old cryptkeys.

**Comment by Rangtasitc** [comment]
I am having trouble with using x-Kore 1 on chaos server, sorry i don't play any other server so i cant test it else where. With your packet updates and a FRESH download Kore works fine as a stand alone bot ( x-kore 0 or x-Kore 2 ) but i use X-Kore 1 as i want to keep an eye on my character. 

Everything is fine until i load into the map server with the RO Client, Kore is conected and trying to move/operate but the RO client window is Frozen. No mobs or npc spawn and after a few sec's ( about 15 sec's ) Kore responds with : **Timeout on Map Server, waiting actions for the Ragnarok Online client**

The RO client is dead , i have to close it Manually at the task bar but kore is still operating fine. 

Has anyone else tryed to use X-Kore 1 with these new Packets? or is the problem just at my end ?

anyway just thought i would let you all know. thanks for your Hard work and dedication , we all greatly appreciate everything you do for the OpenKore Community.

**Comment by Nipodemos** [comment]
i'll merge this because it solve the chaos server problem.

if restart still don't work, i am pretty sure someone will make an issue, then we will know :smile:

**Pull request merged**
