### PR TITLE
update iRO Renewal files

### PR DESCRIPTION
**Pull request by allanon**
- [ ] QA Review

This pull request was auto-generated by patch_iro.pl: https://gist.github.com/allanon/38620af49d250005acbf

### CODE REVIEW

**Comment by zPhotons** [comment]
thanks!

**Comment by ioaltisgithub** [comment]
Thank you so much

**Comment by dezenhando** [comment]
Hey guys, how do i apply this IRO update into my openkore ?

**Comment by f430dew** [comment]
> Thank you! You are a God!

How did you do that? Pleaseeee.

**Pull request merged**
