### PR TITLE
Fix show-stoppers in Wx interface

### PR DESCRIPTION
**Pull request by farrainbow**
- [ ] code review
- [ ] test on Windows
- [ ] test on Linux
- [ ] test on OS X

### CODE REVIEW

**Comment by onepointfivem** [comment]
I can't reproduce the item list error. Inventory list is working fine from View>Inventory menu and from the right console. Also, your src/Interface/Wx/List/ItemList.pm looks a lot different from mine.

**Comment by kaliwanagan** [comment]
@farrainbow i think we have a few conflicts here.

If you need a way to test on osx or linux, i can help out there. just tell me the steps to reproduce.

**Comment by zstyblik** [comment]
I can reproduce the segfault right off the bat on Debian Jessie. This patch actually helped me to beat the segfault at least. Without it, OK wouldn't even start.

**Comment by zstyblik** [comment]
Please, can you at least merge commit for Wx segfault?

**Comment by alisonrag** [comment]
@zstyblik 
this pull have conflict, you can make a new one, post print before and after, this way will be easy to someone approve and merge

**Comment by lututui** [comment]
@alisonrag there's more to this PR than what was merged already

**Comment by ya4ept** [comment]
it looks like this PR is no longer relevant.
"segfault on initialization of Wx interface" request was fixed in #1414

**Pull request closed without merging**
