### PR TITLE
fix rev 20151104a and update st20160203

### PR DESCRIPTION
**Pull request by sctnightcore**
FIX rev 20151104a
20160203 :100: TEST in : http://zirvro.com/
@alisonrag  @lututui  @moneyisgod

### CODE REVIEW

**Comment by sctnightcore** [comment]
#1031

**Comment by alisonrag** [comment]
in my point of view its ok, but i will test later.
are the olds servertypes working or is this just a implementation to 2015 ~ 2016?

**Comment by sctnightcore** [comment]
20151104 work but i cannot run st20160203a idk why haha @alisonrag 
image

**Comment by sctnightcore** [comment]
FIX = many bug WTF @alisonrag

**Pull request closed without merging**
