### PR TITLE
Added configuration for hercules private servers

### PR DESCRIPTION
**Pull request by ervinpm**

### CODE REVIEW

**Comment by Nipodemos** [comment]
Hello!
do you have a screenshot or video of this data working?

**Comment by ervinpm** [comment]
> Hello!
> do you have a screenshot or video of this data working?

Yes, here are a couple of screen captures of login and fight logs. I masked the ipaddress of our hercules server though:

openkore1
openkore2

**Comment by Nipodemos** [comment]
great! I have one more question, it is problably silly but i never messed with hercules or athena so here it goes:

is it possible that some of these values change depending on the configuration made in the server? because if it does, i don't know if it is really worth to keep configs that only work in a specific condition

**Comment by ervinpm** [comment]
I don't think it will, I'm no Hercules or Athena expert too but I have left the settings of hercules server to their default values. At least these configuration will work on them if someone was to have the same default server settings that I did.

**Comment by ya4ept** [comment]
I think that the localhost server is superfluous in our settings

**Comment by ahoyaharr** [comment]
Unfortunately this config is not working for me on my localhost Hercules server which is running all of the default values:

image

**Comment by ervinpm** [comment]
Are you on the latest version?

**Comment by Nipodemos** [comment]
> I think that the localhost server is superfluous in our settings

why?

**Comment by ahoyaharr** [comment]
Hi, sorry for the late follow up -- the config works, but it seems that packet version `20180621` is more popular on Athena, and many people on Hercules use `20180418`, though I do not know the reason. It might be worth it to make a note somewhere even if it is likely to change in the future.

Anyways, good work! I found it helpful and support this being merged.

**Review by sctnightcore — APPROVED** [review]

**Comment by ya4ept** [comment]
> why?

i think very few people use localhost

**Comment by Nipodemos** [comment]
> > why?
> 
> i think very few people use localhost

even so i think is still worth it since it will help begginers by already having it

my only suggestion is to then put a name on these configs to show that is for hercules private servers, as it looks the aethena already changes things and break you configs

**Comment by ya4ept** [comment]
@alisonrag, what do you think about this?

**Comment by alisonrag** [comment]
> @alisonrag, what do you think about this?

i think now need to update the info, cause if i'm not wrong current default clientdate is different

**Comment by ya4ept** [comment]
Who has Hercules private servers?

**Pull request closed without merging**
