### PR TITLE
update iRO Re:Start files

### PR DESCRIPTION
**Pull request by allanon**
- [ ] QA Review

### CODE REVIEW

**Comment by delawr0190** [comment]
What server isn't working, @Rovejoe ?

**Comment by Rovejoe** [comment]
@delawr0190  IRO

**Comment by delawr0190** [comment]
@Rovejoe Restart or Renewal?

**Comment by Rovejoe** [comment]
Renewal

**Comment by delawr0190** [comment]
Let me take a look.  One sec.

**Comment by Rovejoe** [comment]
@delawr0190 tq sir ..

**Comment by sctnightcore** [comment]
U need wait @Rovejoe

**Pull request closed without merging**
