### PR TITLE
add support to cryptkey in xkore 1 and 3

### PR DESCRIPTION
**Pull request by alisonrag**
add support to cryptkey in xkore 1 and 3

xkore 3 in bRO:
xkore bro

xkore 3 in iRO:
xkore iro

xkore 1 in iRO:
xkore 1 iro

### CODE REVIEW

**Comment by Darksin88** [comment]
with Kore3 It disconnects on Restart

and Kore1 gives this message...

**Comment by alisonrag** [comment]
@Darksin88 
did you applyied my full patch?
did you updated your openkore to latest version?
the xkore 1 will only work if you run the  openkore in administrator mode

**Comment by Junezavr** [comment]
But Xkore 2 can don't work !

**Comment by FireflySkye** [comment]
Thanks. It really works (xKore1) !!

But, I have an issue, after a few good solid minutes (around 10~20mins) I got disconnected. I tried in few times using different PC and updated openkore (plus this changes).

disconect

Thank you for your hardwork :D

**Comment by alisonrag** [comment]
@FireflySkye 
send me the console log with debug 1 

0a68 its a shuffled packet, maybe the client spammed this packet and openkore spam also

**Comment by FireflySkye** [comment]
Here 
[console.txt](https://github.com/OpenKore/openkore/files/1443208/console.txt)

**Comment by alisonrag** [comment]
@FireflySkye 
thanks is a sync packet, i'm tryng to figure out why client disconnect after sync

**Comment by MysticFurur0RE** [comment]
my client crash in xkore 1 and dont do anything in xkore3. (ragnarok restart)

**Comment by alisonrag** [comment]
@MysticFurur0RE 
did you applied my full patch?
did you updated your openkore to latest version?
the xkore 1 will only work if you run the openkore in administrator mode

**Comment by Junezavr** [comment]
Xkore 2 can not work

**Comment by FireflySkye** [comment]
I receive those packet whenever I use skills or my homunculus skills

**Comment by alisonrag** [comment]
@FireflySkye 
just need to make openkore skip sync_ex packet, already made a patch, but i will test more

sem titulo

**Comment by FireflySkye** [comment]
That's xKore 3. I'm using xKore 1 since I don't know how to setup xKore 3 >.<

Thank you.

**Comment by thalesaustin** [comment]
Hey Guys, where i can find a tutorial for doing the changes to visual mode? I already tryed everything, but i dont know if im doing right.

Thanks

**Pull request closed without merging**
