### PR TITLE
update iRO Renewal files

### PR DESCRIPTION
**Pull request by allanon**
- [ ] QA Review

This pull request was auto-generated by patch_iro.pl: https://gist.github.com/allanon/38620af49d250005acbf

### CODE REVIEW

**Comment by bunnyy00** [comment]
I have updated all of the above but still

**Comment by bunnyy00** [comment]
[reconnect] Login retry number 2, setting reconnect timeout to 60 seconds.
连接 (128.241.92.162:6800)... 连接完成
Timeout on Account Server, reconnecting. Wait 60 seconds...

**Comment by bunnyy00** [comment]
Hi allanon, i have done all of the above and now working fine, another issue is when i try to click on the map to move the character to a certain place, it didn't move at all, do you have any idea what might went wrong?

**Comment by jomarlorica** [comment]
hi @allanon can you put it on update on tables on your https://github.com/OpenKore/openkore ?? thanks. sorry to bother you. we are not tech like you. thank you

**Comment by jomarlorica** [comment]
can you more it sir @allanon  to the https://github.com/OpenKore/openkore ?? thanks

**Comment by lututui** [comment]
@jomarlorica if you think you're speeding anything up by bumping and tagging allanon, you're wrong

**Comment by plokislokis** [comment]
I was able to login ingame but I'm getting an error "Stuck during route" and my character doesn't move. How can i fix this?

**Comment by jomarlorica** [comment]
sorry @lututui

**Pull request merged**
