### PR TITLE
suppress the output of the sprite_change message

### PR DESCRIPTION
**Pull request by ya4ept**
We don't know what type 7 and 13 are. Type 7 looks like body palette or body color. Type 13 looks like body2

fix https://github.com/OpenKore/openkore/issues/3905

https://github.com/HerculesWS/Hercules/blob/stable/src/map/map.h#L784

```
enum look {
	LOOK_BASE,
	LOOK_HAIR,
	LOOK_WEAPON,
	LOOK_HEAD_BOTTOM,
	LOOK_HEAD_TOP,
	LOOK_HEAD_MID,
	LOOK_HAIR_COLOR,
	LOOK_CLOTHES_COLOR,
	LOOK_SHIELD,
	LOOK_SHOES,
	LOOK_BODY,
	LOOK_FLOOR,
	LOOK_ROBE,
	LOOK_BODY2,

#ifndef LOOK_MAX
	LOOK_MAX
#endif
};
```

### CODE REVIEW

**Comment by dcyxxt** [comment]
tried "fix_sprite_change"，still has the problem

**Comment by ya4ept** [comment]
@dcyxxt  we need new logs

**Comment by dcyxxt** [comment]
> @dcyxxt we need new logs

what should i do？

**Comment by ya4ept** [comment]
https://github.com/OpenKore/openkore/wiki/How-to-collect-logs%3F

**Comment by dcyxxt** [comment]
> @dcyxxt we need new logs

[console_xxxx.txt](https://github.com/user-attachments/files/18212875/console_xxxx.txt)
here it is

**Comment by ya4ept** [comment]
I found a bug, please test again

**Comment by dcyxxt** [comment]
> I found a bug, please test again

fixed!thx

**Review by alisonrag — APPROVED** [review]

**Pull request merged**
