### PR TITLE
More network cleaning

### PR DESCRIPTION
**Pull request by Henrybk**
Only identical or almost identical functions are being moved, needs testing.

### CODE REVIEW

**Comment by farrainbow** [comment]
Were there any non-trivial differences in "almost" identical functions?

**Comment by Henrybk** [comment]
@farrainbow Maybe, I remember having differences like 'exists' vs 'defined' once in a function, but I tested and all results seemed to be equal to before, I will review all of this before even thinking of merging.

**Comment by farrainbow** [comment]
If code is identical then it should be merged ASAP. This kind of thing tends to create conflicts later if left unmerged and is tedious to properly review.

**Comment by farrainbow** [comment]
*Next time*, if possible, group only related changes in commits (commits are quick in git aren't they?) and write more proper commit messages, for example there messages could be at least "Moved func1, func2, func3", that would be good enough.

**Comment by Henrybk** [comment]
The big problem with my last network cleaning commit was that even though all functions were identical both sakray_0 and servertype0 had constants not imported by receive.pm which caused many conflics, that is what I am worried about.

I am on tests week at university, by day 15 I should be free and will be pleased to review this.

If in the meantime anyone wants to review it for me I'd be happy :P

**Comment by allanon** [comment]
:+1:

The code removed and added is identical (sans whitespace and a couple comments) with the exception of `storage_items_nonstackable` and `storage_items_stackable`, which were changed to check the existence of `title` rather than whether it is truthy. The result is only different when `title` is `""`, and probably doesn't result in any actual difference anywhere.

**Comment by Henrybk** [comment]
As soon as this is tested it should be merged.

**Comment by farrainbow** [comment]
Thank you very much for checking @allanon!

**Comment by farrainbow** [comment]
So if we want to merge this we should now collectively resolve conflicts (everyone who has commit access to openkore now has commit access to Henrybk/More-network-cleaning) and merge that, and only after that - tweak and merge other PRs which would conflict.

**Comment by farrainbow** [comment]
Updated to the current `master`.

**Comment by kaliwanagan** [comment]
@Henrybk @farrainbow the currernt PR has merge conflicts. I'm still getting myself re-familiarized with the codebase so I can't really help resolve the conflicts here.

Removing dead and duplicate code is always a good thing :)

**Comment by alisonrag** [comment]
@moneyisgod 
we are doing this step by step 
https://github.com/OpenKore/openkore/pulls?q=is%3Apr+merge+author%3Aalisonrag
https://github.com/OpenKore/openkore/pulls?utf8=%E2%9C%93&q=is%3Apr+move+author%3Aalisonrag+
https://github.com/OpenKore/openkore/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aalisonrag+clean

some packets need update this is why we not merged everything

**Comment by Nipodemos** [comment]
i'll close this pull request, since it's been almost two years that he has been made, and now is obsolete

**Pull request closed without merging**
