### PR TITLE
update iRO Renewal files

### PR DESCRIPTION
**Pull request by allanon**
- [ ] QA Review

This pull request was auto-generated by patch_iro.pl: https://gist.github.com/allanon/38620af49d250005acbf

### CODE REVIEW

**Comment by allanon** [comment]
@sctnightcore Good question! As the description of this pull request suggests, this is automatically generated. For the hat effect file, the (source) lua isn't deployed with the iRO Renewal official client, so I've been pulling it from a github repo instead: https://github.com/OpenKore/openkore/blob/master/tools/patch.pl#L232-L246

Is there a better way to get this data? Or I can just stop trying to maintain this file.

**Comment by sctnightcore** [comment]
@allanon  ok

**Comment by allanon** [comment]
Looks like the repo I was getting that file from doesn't even exist anymore. Have you written a lua program to extract this list from `HatEffectInfo.lub`? If not, I'll see if I can write one.

**Comment by sctnightcore** [comment]
I do not write @allanon 
I do it all by manual XD

**Comment by oleokoong** [comment]
iro remove from grf..

**Comment by allanon** [comment]
Ok, I've removed the hateffect updater for now, so it should no longer attempt to remove your change. Sorry about that! I'll see if I can fix it, preferably by extracting from the actual HatEffectInfo.lub file that comes with the official client.

**Comment by sctnightcore** [comment]
@allanon  Nevermind.
I try as much as possible based kRO.
If you want to edit it. I am not serious.
Lol ♥

**Pull request merged**
