### PR TITLE
fix `repair` command

### PR DESCRIPTION
**Pull request by ya4ept**
Console command `repair` - does not work:
1) after using skill "Weapon Repair" - item numbers are not displayed correctly:
```
ss 108
You are casting Repair Weapon on yourself (Delay: 0ms)
--------Repair List--------
☺  Dagger
---------------------------
```
2) when using the `repair 1` command, nothing happens:
```
repair 1
Item with index: 1 does either not exist in the 'Repair List' or the list is empty.
```
3) `repairAuto` config parameter works, but the message displays an incorrect item name
```
You use Repair Weapon on yourself (Lv: 1)
Inventory Item Removed: Iron (3) x 1
Successfully repaired Unknown #3.
```

This PR corrects the indicated errors.

I also added two new commands:
`repair` - show list of items available for repair
`repair cancel` - cancel repair item

### CODE REVIEW

**Comment by ya4ept** [comment]
I tested on the RMS server.
I have not tested on official servers

this macro will help in tetering:
```
macro repair {
	do conf repairAuto 0
	do c \@item iron
	do c \@item2 13035 1 1 0 1 4147 0 0 0
	do c \@item2 1485 1 1 0 1 4281 0 0 0
	do c \@item2 1804 1 1 0 1 0 4155 0 0
	do c \@item2 13302 1 1 0 1 4117 4043 4157 4043
	do ss 108
	warning input: "repair №" or "repair cancel"
}
macro repair_a {
	do conf repairAuto 1
	do conf repairAuto_list Whip
	do c \@item iron 8
	do c \@item2 13035 1 1 1 1 4147 0 0 0
	do c \@item2 13035 1 1 2 1 0 4281 0 0
	do c \@item2 13035 1 1 3 1 0 0 4155 0
	do c \@item2 13035 1 1 4 1 0 0 0 4117
	do c \@item2 13035 1 1 5 1 0 4117 4043 4157 4043
	do c \@item2 1953 1 1 10 1 4043 0 0 0
	do c \@item2 1953 1 1 9 1 0 4147 0 0
	do c \@item2 1953 1 1 8 1 0 0 4117 0
	do c \@item2 1953 1 1 7 1 4043 4281 0 0
	do c \@item2 1953 1 1 6 1 4043 4281 4043 0
	pause 1
	call skill 5
	pause 2
	do i neq
}

macro skill {
	$i = 0
	while ($i <	$.param[0]) {
		do ss 108
		pause 2
		$i++
	}
}
```

**Comment by ya4ept** [comment]
Updated wiki:
https://openkore.com/index.php/Repair
https://openkore.com/index.php/RepairAuto
https://openkore.com/index.php/RepairAuto_list

**Comment by ya4ept** [comment]
I found a bug when trying to fix other people's items. All items have the same index
```css
sp 108 0
You are casting Repair Weapon on Player prist (0) (Delay: 0ms)
--------------------------------- Repair List ----------------------------------
   # Short name                     Full name
   0 Desert Wind
   0 Desert Wind
   0 Desert Wind
   0 Desert Wind
   0 Battle Fork
--------------------------------------------------------------------------------
```

**Comment by ya4ept** [comment]
now the bot can repair other people's items

**Comment by alisonrag** [comment]
seems ok to me

**Pull request merged**
