### PR TITLE
feat: update tk interface

### PR DESCRIPTION
**Pull request by alisonrag**
image

### CODE REVIEW

**Comment by alisonrag** [comment]
in this version icon is fixed

**Comment by ya4ept** [comment]
1) the portal has the same color as the monster
image

2) I see some artifact from the bottom left:
image

**Comment by alisonrag** [comment]
actors now have colors in list box:
image

image

**Comment by ya4ept** [comment]
added the number of items to the list
image

**Comment by ya4ept** [comment]
added a tab to the list
image

**Review by ya4ept — APPROVED** [review]

**Pull request merged**
