### PR TITLE
Add Shield Spell skill specific buffs

### PR DESCRIPTION
**Pull request by Henrybk**
I tested it in RMS test server without any problems, seems to work fine. The IDs are custom and the info was taken from rathena emulator source code and http://irowiki.org/wiki/Shield_Spell, aswell as ingame testing.

### CODE REVIEW

**Comment by sayd90** [comment]
Está apresentando os seguintes erros no código
```
Global symbol "%hatEffectHandle" requires explicit package name at src/Network/Receive.pm line 3761.
Global symbol "%hatEffectHandle" requires explicit package name at src/Network/Receive.pm line 3762.
Global symbol "%hatEffectName" requires explicit package name at src/Network/Receive.pm line 3763.
Global symbol "%hatEffectName" requires explicit package name at src/Network/Receive.pm line 3763.
Compilation failed in require at C:\Users\sayde\Desktop\openkore\openkore.pl line 60.
BEGIN failed--compilation aborted at C:\Users\sayde\Desktop\openkore\openkore.pl line 60.
```

**Comment by Henrybk** [comment]
@sayd90 Have you updated your openkore? That is a change made by @cydh in #175

**Comment by sayd90** [comment]
work is fine thanks

**Comment by kaliwanagan** [comment]
It's working well, but we would prefer to not use magic numbers in the code :P

**Comment by flacrasec** [comment]
Ok I understand! ^^

**Comment by Nipodemos** [comment]
i'm closing this PR since it will not be merged

**Comment by Fadreus** [comment]
Uh.. why not?
Im planning to use it except that I dont have shield spell yet xD

**Comment by Nipodemos** [comment]
kaliwanagan said it is not cool, so i'm respecting his opinion
and this PR is 1 year and 10 months old :-(

**Pull request closed without merging**
