### PR TITLE
IsNotInCoordinate Condition

### PR DESCRIPTION
**Pull request by Nipodemos**
created this Condition by simply copying the entire IsInCoordinate code and inverting the ValidateCondition 😄 

### IsNotInCoordinate
Description: Checks if the current coordinates **does not match** one of the given ones.

Syntax:
`IsNotInCoordinate <comma separated list of pairs of x and y coordinates>`

It also accepts ranges in place of coordinates. (like 100..200 for x and 50..100 for y)
Example:
```
IsNotInCoordinate 100 150
IsNotInCoordinate 120 100, 115 289, 158 236
IsNotInCoordinate 20..80 200, 50 60, 80 90..150, 100..200 150..200
IsNotInCoordinate 30..35 40..45
```
Set variables:
```
$.IsNotInCoordinateLast => Saves the last coordinate that made IsNotInCoordinate become true
$.IsNotInCoordinateLastMemberIndex => Saves the list index in condition that made IsNotInCoordinate become true
```

### CODE REVIEW

**Comment by moneyisgod** [comment]
Amazing.
Retreat plugin done to macro.

I would think this is amazing.

**Comment by Henrybk** [comment]
Shouldn't `and` assertions be made using more than one line? Like

```
IsNotInCoordinate 100 150
IsNotInCoordinate 120 100
```

**Comment by Nipodemos** [comment]
you mean not to accept more than one pair of coordinates per condition??? @Henrybk

**Comment by Henrybk** [comment]
Yep

**Comment by Nipodemos** [comment]
this makes sense, i will change this today at night when i'm home

**Comment by Nipodemos** [comment]
i turns out that this is much more difficult than i though, so i will close this until i learn how to do

**Pull request closed without merging**
