### PR TITLE
trying to build on windows

### PR DESCRIPTION
**Pull request by ya4ept**
- temporarily deleted build_XSTools.yml and test.yml
- added a new script that configures perl x86
It deletes the folder: `C:/Strawberry/*`
Downloaded strawberry-perl x32 portable
Then unpacks to a folder `C:/Strawberry`

~~Existing problem: XSTools.dll cannot be compiled~~

### CODE REVIEW

**Comment by ya4ept** [comment]
TODO:
- [ ] make a build for perl 5.12 x32
- [ ] add saving artifacts
- [ ] try adding using cache

**Comment by ya4ept** [comment]
library size is very different:
изображение

**Comment by alisonrag** [comment]
can we perform test?

**Comment by ya4ept** [comment]
rebased onto master

**Comment by ya4ept** [comment]
If i run `gmake test` on github actions i get: `$^O='msys'` in unittests.pl
And it tries to rebuild XSTools before testing

If i run `perl unittests.pl` on github actions i get: `$^O='MSWin32'`

**Comment by ya4ept** [comment]
known issues:
- [ ] we cannot use 'gmake test' on windows OS (it tries to rebuild XSTools before testing)
- [ ] I can't pass variables $OS, $PYTHON, $ARCHITECTURE, $PERL to powershell (see XSTools_notes.txt)

**Comment by ya4ept** [comment]
@alisonrag, @sctnightcore, everything is ready for merging, please check.

**Comment by alisonrag** [comment]
checked the tests and seems fine

**Review by alisonrag — APPROVED** [review]

**Pull request merged**
