### PR TITLE
Small fix

### PR DESCRIPTION
**Pull request by ya4ept**
1. config fix:
\- added missing config options ([sellAuto_minDistance](https://openkore.com/wiki/SellAuto_minDistance), [sellAuto_maxDistance](https://openkore.com/wiki/SellAuto_minDistance), [storageAuto_minDistance](https://openkore.com/wiki/StorageAuto_minDistance), [storageAuto_maxDistance](https://openkore.com/wiki/StorageAuto_minDistance))
2. commands fix:
\- added description to commands (autosell, deal, relog)
\- code cleanup
\- fixed command "cmdDebug" (before she could not enable [debug](https://openkore.com/wiki/Debug) level 3+)
\- changed the output of the "store" command (now we show "1,000,000z" instead of "1000000z")
before:
```
----------- Store List (Armor Dealer#prt) ------------
#  Name                    Type                  Price   Amnt
0  Защитник                Armor                  500z   0
1  Круглый щит             Armor                14000z   0
8  Хлопковая рубашка       Armor                   10z   0
------------------------------------------------------
```
after
```
------------------ Store List (Armor Dealer#prt) -------------------
#  Name                    Type                       Price   Amnt
0  Защитник                Armor                       500z   0
1  Круглый щит             Armor                    14,000z   0
8  Хлопковая рубашка       Armor                        10z   0
--------------------------------------------------------------------
``` 
3. Receive.pm fix:
\- fixed a mistake in non-english pets name and "Equip Info"
\- small fix "vender_items_list"
```
---------------------------------- Vender: Лиремка (6) ----------------------------------
#   Name                                      Type                  Amount          Price
0   Зелье концентрации                        Предмет специальный      146           695z
1   Зелье пробуждения                         Предмет специальный       83         1,350z
2   Крылья мухи                               Предмет специальный      654            53z
5   Ящик с поводьями (7 д.)                   Cash Item                  1       540,000z
-----------------------------------------------------------------------------------------
```
\- small fix "npc_market_purchase_result"
```
------------------ Store List (Armor Dealer#pay) -------------------
#  Name                    Type                       Price   Amnt
0  Сандалии                Armor                       400z   0
1  Ботинки                 Armor                     3,500z   0
2  Сапоги                  Armor                    18,000z   0
--------------------------------------------------------------------
```
\- small fix "deal_add_you" (added new status - "192")
\- small fix "buying_store_items_list"
\- fixed "special_item_obtain" (added the message from the msgstringtable.txt)
4. added isvr_disconnect
5. Send.pm fix
\- small fix "sendSellBulk" and "sendBuyBulkMarket"
6. updated cities.txt
7.  shop \ buy fix
\-fixed messages in the same style (price first, then quantity)

Everything is tested on RMS and rRO

### CODE REVIEW

**Comment by alisonrag** [comment]
missing some cities:
https://pro.fandom.com/wiki/Cities,_Towns_and_Places

**Comment by c4c1n6kr3m1** [comment]
Training Grounds N Monster Race Arena listed on cities ? big NO

**Comment by ya4ept** [comment]
> Training Grounds N Monster Race Arena listed on cities ?

yes, but only those locations where there are no monsters

**Comment by ya4ept** [comment]
> 
> 
> missing some cities:
> https://pro.fandom.com/wiki/Cities,_Towns_and_Places

done

**Comment by alisonrag** [comment]
added missing:
lasagna
verus
rock ridge

**Review by alisonrag — APPROVED** [review]

**Comment by alisonrag** [comment]
seems ok to me

**Comment by c4c1n6kr3m1** [comment]
> 
> 
> > Training Grounds N Monster Race Arena listed on cities ?
> 
> yes, but only those locations where there are no monsters

i still remember these maps
new_x-3 normal 
new_x-4 harder
new_x-5 hardest

**Comment by ya4ept** [comment]
> i still remember these maps
> new_x-3 normal
> new_x-4 harder
> new_x-5 hardest

no
 new_1-3 normal
 new_3-3 harder
 new_5-3 hardest

**Pull request merged**
