### PR TITLE
servertybe 2015-2016 

### PR DESCRIPTION
**Pull request by sctnightcore**
Wait to update the Receive and more.
NEED TEST
ty
20131223 by @moneyisgod 

20151104:**WORK**
RagexeRE_2016_02_03 : fix TEST in : http://zirvro.com/

### CODE REVIEW

**Comment by sctnightcore** [comment]
REV
'0A18' => ['map_loaded', 'V a3 x2 v', [qw(syncMapSync coords unknown)]],
'0A37' => ['inventory_item_added', 'a2 v2 C3 a8 V C2 a4 v a25', [qw(ID amount nameID identified broken upgrade cards type_equip type fail expire unknown options)]],
'0A84' => ['guild_info', 'a4 V9 a4 Z24 Z24 Z20', [qw(ID lv conMember maxMember average exp exp_next tax tendency_left_right tendency_down_up emblemID name master castles_string)]],

**Comment by alisonrag** [comment]
congratulations. 
tonsofdamage
Tons of Update*

**Comment by moneyisgod** [comment]
Good. I'll take a look today and review it. Thanks !

**Comment by moneyisgod** [comment]
```
'0A44' => ['party_users_info', 'x2 Z24', [qw(party_name)]], -> 2017 05 17 packet received
'0A43' => ['party_join', 'a4 V v2 C Z24 Z24 Z16 v C2', [qw(ID role x y type name user map lv item_pickup item_share)]], -> 2017 05 17 PACKET RECEIVED
'084B' => ['rodex_write_result', 'C', [qw(fail)]], # 3 -> This is not rodex write result.
'0A84' => ['guild_info', 'a4 V9 a4 Z24 Z24 Z20', [qw(ID lv conMember maxMember average exp exp_next tax tendency_left_right tendency_down_up emblemID name master castles_string)]], -> 2016 08 31 PACKET
'0A37' => ['inventory_item_added', 'a2 v2 C3 a8 V C2 a4 v a25', [qw(ID amount nameID identified broken upgrade cards type_equip type fail expire unknown options)]], -> 2016 10 12
```

0A30 packet is missing.

**Comment by sctnightcore** [comment]
image
Packet Parser: Unknown switch: 0A24
I try it, but  dmg attacking for monsters not show 
idk why

**Comment by sctnightcore** [comment]
I think it should be actor_action, actor_exists, actor_connected, actor_moved, actor_info But it does not exist.

**Comment by alisonrag** [comment]
in this servertype openkore don't receive the actor_action packet?
0A24 are related to achievement system

**Comment by moneyisgod** [comment]
No. 0x2E1 and 0x8C8.
Missing from 2008~2009 sT!

**Comment by sctnightcore** [comment]
@alisonrag  @moneyisgod  ok sir

**Comment by sctnightcore** [comment]
```
<< Received packet:      09FD [93 bytes]
<< Received packet:      09FF [88 bytes] 
<< Received packet:      07FB [25 bytes]
<< Received packet:      0A0C [56 bytes]
<< Received packet:      07FB [25 bytes]
```
I added rev in sT0 to Sakexe_0, it did not work anyway.

**Comment by sctnightcore** [comment]
#1031

**Comment by alisonrag** [comment]
ST0 are not used by sakexe ou regexeRE

**Comment by sctnightcore** [comment]
@acepartacus come here

**Comment by sctnightcore** [comment]
@alisonrag  you can update Sakexe_0 ?  Because Sakexe_0 has not updated for a long time.

**Comment by sctnightcore** [comment]
#1055

**Comment by alisonrag** [comment]
nice work until here.
are more updates coming?

**Comment by sctnightcore** [comment]
@alisonrag  miss packet send and rev for sakexe_0

**Comment by sctnightcore** [comment]
del full update 2 week

**Comment by moneyisgod** [comment]
Hi sctnightcore. I have some list too and i need u Take a look.

**Comment by sctnightcore** [comment]
#1067

**Pull request closed without merging**
