### PR TITLE
[eventMacro] Add condition ShopOpened

### PR DESCRIPTION
**Pull request by Nipodemos**
Tested and working normally

### CODE REVIEW

**Comment by ya4ept** [comment]
need wiki update
http://openkore.com/index.php/EventMacro

**Comment by Nipodemos** [comment]
finally added: [Link to Docs](http://openkore.com/index.php?title=EventMacro&type=revision&diff=4330&oldid=4316)

**Comment by ya4ept** [comment]
@Nipodemos you forgot to create this page: http://openkore.com/index.php/ShopOpened

**Comment by Nipodemos** [comment]
Why make a template copy?
Can't we make a reference of this page instead of the template page?

**Comment by ya4ept** [comment]
its no copy, [see](http://openkore.com/index.php?title=ShopOpened&action=edit)

**Comment by Nipodemos** [comment]
i see, thanks for the information

**Pull request merged**
