### PR TITLE
UP=sT201710 +

### PR DESCRIPTION
**Pull request by sctnightcore**
well -*- 
I'm lonely
```
packet : https://gitlab.com/4144/servergreps/tree/master/
client : http://herc.ws/board/topic/15348-kro-unpacked-clients-releases/
```

```
Peek has a problem since client 201708+.
Now the peek can not pull the packet out of the client. ! 
```
# list 
```
2017-04-12aRagexeRE
2017-04-19bRagexeRE
2017-04-26dRagexeRE
2017-08-23aRagexeRE
2017-08-30bRagexeRE
2017-09-13bRagexeRE
2017-09-20bRagexeRE
2017-10-11aRagexeRE
2017-10-18aRagexeRE
```
**wait recvpacket ! Please wait**

### CODE REVIEW

**Comment by lututui** [comment]
There's no RagexeRE_2017_10_02c in http://herc.ws/board/topic/15348-kro-unpacked-clients-releases/

I'll try to get 2017-09-27b

**Comment by moneyisgod** [comment]
@lututui 

2017-09-27b

i can find more or less 1247 packets. Missing about 100 packets. ! :O if you know how to, tell me.

Hey, @sctnightcore , where's that recvpackets you've told that hercules developer made ?
Post here

**Comment by sctnightcore** [comment]
[recvpackets2017-09-27bRagexeRE (1).txt](https://github.com/OpenKore/openkore/files/1370232/recvpackets2017-09-27bRagexeRE.1.txt)
@moneyisgod  @lututui

**Comment by lututui** [comment]
Sorry, what?

**Comment by cydh** [comment]
mkay time for OOT.
anyone working for New Refine UI?

**Comment by sctnightcore** [comment]
if you have time to make it. @cydh  XD

**Pull request closed without merging**
