### PR TITLE
Translate interface and skillname into vietnamese

### PR DESCRIPTION
**Pull request by tungbach1990**

### CODE REVIEW

**Comment by ya4ept** [comment]
where did you take `skillnametable.txt` ?

**Comment by ya4ept** [comment]
- [ ] you need to translate new files

**Comment by onionzz11** [comment]
> * [ ]  you need to translate new files
 how to fix 
loi

**Comment by alisonrag** [comment]
@tungbach1990 will you add something else, or we can merge it?

**Comment by ya4ept** [comment]
@tungbach1990  what about equiptypes.txt and itemtypes.txt?

**Pull request merged**
