### PR TITLE
Overload array dereferencing for ObjectList

### PR DESCRIPTION
**Pull request by farrainbow**
`@$playersList` is much shorter than `@{$playersList->getItems}` and IMO doesn't hurt readability.

Also, if `$list` is undefined, `@$list` would successfully evaluate to empty array, so in some situations it's not even needed to check if `$list` is defined.

- [ ] QA review
- [ ] code review
- [ ] test AI features

### CODE REVIEW

**Comment by FireflySkye** [comment]
error upon opening a shop
untitled

**Comment by farrainbow** [comment]
@FireflySkye it's not related to this PR, but it's now fixed.

**Comment by Henrybk** [comment]
I like the idea, will test later today.

**Comment by kaliwanagan** [comment]
I'm not sure. I feel it's too magical. Then again I've been away from perl for far too long to comment about idiomatic perlisms :stuck_out_tongue: 

I like the `for instead of `foreach` but the magical `@` might be a bit too much (and being explicit in the var type can be useful for debugging, or for code you want to take a look at a few years from today).

What do you think @farrainbow?

**Pull request merged**
