### PR TITLE
update map of tro

### PR DESCRIPTION
**Pull request by comdevx**
add fields missing.
update maps had multi channel.

### CODE REVIEW

**Comment by ya4ept** [comment]
All our maps are packed in *.GZ archive.
I see a lot of duplicate maps ..

**Comment by Nipodemos** [comment]
there is only one problem with that update (and it is not your fault)

those map files are shared for every server that openkore opens, so the maps that are different in other servers will make openkore confused

To be honest that was already happening for years, but it makes me wonder wheter this will make things worse or better for other servers

the only way was to make a fields folder for each server, but i don't know how to code that

if anyone else has your oppinion, i don't know if this should be merged or not

**Comment by comdevx** [comment]
Ok. I accept everyone's decision.

**Comment by Nipodemos** [comment]
@comdevx, @ya4ept mentioned that there is a lot of duplicate maps, you should take a look at that

**Comment by comdevx** [comment]
Can I have a duplicate sample?

**Comment by comdevx** [comment]
i will remove *.field and merge again.

**Pull request closed without merging**
