### PR TITLE
feat: implement macro detector

### PR DESCRIPTION
**Pull request by alisonrag**
remake of #3566

Add Support to Macro Detection Client Interface

Detection UI:
image

captcha command:
image

thanks to @macabeus (BMP uncompress)

### CODE REVIEW

**Comment by ya4ept** [comment]
https://github.com/HerculesWS/Hercules/pull/3051

**Review by ya4ept — APPROVED** [review]
looks correct

**Comment by ya4ept** [comment]
we need to update the documentation
https://openkore.com/wiki/captcha

**Comment by alisonrag** [comment]
> * [x]   we need to update the documentation
> 
> 
> https://openkore.com/wiki/captcha

updated the above and added the bellow:
https://openkore.com/wiki/Captcha

they are different system

**Comment by CatOnMyLeg** [comment]
What if the captcha is Chinese words?
Because I play in twro. And now they changed to Chinese words.

I can recognize it .  And I try to type in the console :  captcha 出來走走(出來走走 is the answer of the captcha)
The bot will crash.   How should I solve this problem?

**Pull request merged**
