### PR TITLE
feat: add support to AP

### LINKED ISSUE #3888: Can I use AP to decide to use only a certain skill? Like SP
Can I use AP to decide to use only a certain skill?
Like SP

### PR DESCRIPTION
**Pull request by alisonrag**
* added self condition ap

https://irowiki.org/wiki/Activity_Points

image

image

this closes #3888

### CODE REVIEW

**Comment by dcyxxt** [comment]
woooo,need it for very long time

**Comment by ya4ept** [comment]
Corrected the display a bit. It seems to me that AS should be displayed under SP. @alisonrag can you test this?

**Comment by dcyxxt** [comment]
> Corrected the display a bit. It seems to me that AS should be displayed under SP. @alisonrag can you test this?

微信截图_20241215205348

not good

**Comment by alisonrag** [comment]
image
@ya4ept not fixed

**Comment by ya4ept** [comment]
please test again

**Comment by dcyxxt** [comment]
> please test again


its okay

**Comment by ya4ept** [comment]
it looks like you're not using a monospaced font

**Comment by ya4ept** [comment]
The documentation has been updated:
https://openkore.com/wiki/ap

**Comment by dcyxxt** [comment]
> it looks like you're not using a monospaced font

yep,may the chinese problem or chinese system

**Review by ya4ept — APPROVED** [review]

**Pull request merged**
