### PR TITLE
feat: implement statuses command

### PR DESCRIPTION
**Pull request by alisonrag**
statuses command display all character status and time left

image

### CODE REVIEW

**Review by sctnightcore — APPROVED** [review]
LGTM

**Comment by ya4ept** [comment]
do not rush, we can do it better

**Comment by ya4ept** [comment]
Let's add this information to the `s` command, like this:
```
------------------------ Status ------------------------
trima                            HP:      379/379 (100%)
Summoner (Boy)                   SP:          7/51 (13%)
Base: 18                          521/1,400 /49 (37.21%)
Job : 10                            14/2,500 /36 (0.56%)
Zeny: 0                      Weight:    305/2360 (12.9%)
Statuses: 
Hide: -1677932841 seconds left
Hide Delay: 13 seconds left

Spirits/Coins/Amulets: 0

Total Damage: 60             Dmg/sec: 102.49
Total Time spent (sec):      0.59
Last Monster took (sec):     0.59
--------------------------------------------------------
```
or:
```
------------------------ Status ------------------------
trima                            HP:      379/379 (100%)
Summoner (Boy)                   SP:          7/51 (13%)
Base: 18                          521/1,400 /49 (37.21%)
Job : 10                            14/2,500 /36 (0.56%)
Zeny: 0                      Weight:    305/2360 (12.9%)
Statuses: Hide (-1677932841 s), Hide Delay (13 s)

Spirits/Coins/Amulets: 0

Total Damage: 60             Dmg/sec: 102.49
Total Time spent (sec):      0.59
Last Monster took (sec):     0.59
--------------------------------------------------------
```
OR
```
------------------------ Status ------------------------
trima                            HP:      379/379 (100%)
Summoner (Boy)                   SP:          7/51 (13%)
Base: 18                          521/1,400 /49 (37.21%)
Job : 10                            14/2,500 /36 (0.56%)
Zeny: 0                      Weight:    305/2360 (12.9%)

Spirits/Coins/Amulets: 0

Total Damage: 60             Dmg/sec: 102.49
Total Time spent (sec):      0.59
Last Monster took (sec):     0.59
--------------------------------------------------------
Statuses: Hide (-1677932841 s), Hide Delay (13 s)
```

**Comment by ya4ept** [comment]
bug:
image

**Comment by alisonrag** [comment]
> bug: image

fixed at:
https://github.com/OpenKore/openkore/pull/3731/commits/eb0d7cb48184cd4e3490cd95108af182a2266b0e

**Comment by alisonrag** [comment]
cmd 's' output:
image


cmd 'statuses' output:
image

**Comment by ya4ept** [comment]
why do we need a separate "statuses" command?

"- - 1 seconds left" doesn't look good:
```
Statuses:
Hide - -1 seconds left
Hide Delay - -1 seconds left
Sitting - -1 seconds left
```

**Comment by alisonrag** [comment]
image

updated, separator is to make it easy to read

**Pull request merged**
