### PR TITLE
MessageTokenizer.pm, now xkore slicePacket try to read packet's length not only from recvpackets

### PR DESCRIPTION
**Pull request by c4c1n6kr3m1**
this problem will occure on server with CryptKeys + xkore
never test other than iro restart + xkore 2
iro restart
when selling **from client ( selling from client dude, not from bot )** , client will send a ‎compacted packet consists of 00C9+09D4+09D4
it will result dc
**because it is encrypted and 00C9 length from recvpackets is -1** , so bot fail to read 09D4+09D4(encrypted) 

```
ex:
packet 00C9+09D4+09D4 from client is F5 25 08 00 18 00 01 00 E8 2C E8 2C

[Apr 2 18:27:42 2018.34] XKore2 Server: Received packet 00C9 
[Apr 2 18:27:42 2018.34] Packet Parser: Unknown switch: 00C9
[Apr 2 18:27:42 2018.35] whadup
[Apr 2 18:27:42 2018.36] ================================================
<< Sent by RO client:    00C9 [8 bytes]   Apr 2 18:27:42 2018
  0>  C9 00 08 00 18 00 01 00                               ........
[Apr 2 18:27:42 2018.38] Packet Parser: Unknown switch: 00C9
[Apr 2 18:27:42 2018.39] Packet Tokenizer: Unknown outgoing switch: 2CE8
[Apr 2 18:27:42 2018.40] ================================================
<< Outgoing unknown packet [4 bytes]   Apr 2 18:27:42 2018
  0>  E8 2C E8 2C                                           .,.,
[Apr 2 18:27:42 2018.42] Encrypted MID : [00C9]->[25F5] / KEY : [0x253C]->[0x253C]
[Apr 2 18:27:42 2018.42] ================================================
>> Sent packet: 00C9  [Sell] [8 bytes]   Apr 2 18:27:42 2018
  0>  F5 25 08 00 18 00 01 00                               .%......
[Apr 2 18:27:42 2018.43] Encrypted MID : [2CE8]->[09D4] / KEY : [0x253C]->[0x253C]
[Apr 2 18:27:42 2018.44] ================================================
>> Sent packet: 2CE8   [4 bytes]   Apr 2 18:27:42 2018
  0>  D4 09 E8 2C                                           ...,
[Apr 2 18:27:43 2018.14] ================================================


bot pass D4 09 E8 2C to server , than will dc because faill to recognize 2CE8  is encrypted 09D4 
```
should be like this
```
<< Sent by RO client:    00C9 [8 bytes]   Apr 2 19:43:46 2018
  0>  C9 00 08 00 18 00 01 00                               ........
[Apr 2 19:43:46 2018.64] Packet Parser: Unknown switch: 00C9
[Apr 2 19:43:46 2018.65] ================================================
<< Sent by RO client:    09D4 [2 bytes]   Apr 2 19:43:46 2018
  0>  D4 09                                                 ..
[Apr 2 19:43:46 2018.67] Received packet: 09D4 Handler: sell_buy_complete
[Apr 2 19:43:46 2018.68] ================================================
<< Sent by RO client:    09D4 [2 bytes]   Apr 2 19:43:46 2018
  0>  D4 09                                                 ..
[Apr 2 19:43:46 2018.69] Received packet: 09D4 Handler: sell_buy_complete
[Apr 2 19:43:46 2018.70] Encrypted MID : [00C9]->[25F5] / KEY : [0x253C]->[0x253C]
[Apr 2 19:43:46 2018.70] ================================================
>> Sent packet: 00C9  [Sell] [8 bytes]   Apr 2 19:43:46 2018
  0>  F5 25 08 00 18 00 01 00                               .%......
[Apr 2 19:43:46 2018.72] Encrypted MID : [09D4]->[2CE8] / KEY : [0x253C]->[0x253C]
[Apr 2 19:43:46 2018.73] ================================================
>> Sent packet: 09D4   [2 bytes]   Apr 2 19:43:46 2018
  0>  E8 2C                                                 .,
[Apr 2 19:43:46 2018.74] Encrypted MID : [09D4]->[2CE8] / KEY : [0x253C]->[0x253C]
[Apr 2 19:43:46 2018.75] ================================================
>> Sent packet: 09D4   [2 bytes]   Apr 2 19:43:46 2018
  0>  E8 2C                                                 .,
```

### CODE REVIEW

**Comment by sctnightcore** [comment]
```
// packet 0xc9
struct CZ_SELL_ITEM {
  /* this+0x0 */ short index;
  /* this+0x2 */ short count;
};
```
 ```
/// Closes shop (CZ_NPC_TRADE_QUIT).
/// 09d4
void clif_parse_NPCShopClosed(int fd, struct map_session_data *sd) {
	// TODO: State tracking?
	sd->npc_shopid = 0;
}
```

**Comment by alisonrag** [comment]
seems ok to me.

it should work to every packet compacted and with -1 length. it should fix some bugs related to dc like #1882

**Comment by c4c1n6kr3m1** [comment]
i still have limited understanding on openkore , i am not a programmer
but we know that we kicked off from server because sending wrong packet
judge from the picture about xkore on http://openkore.com/index.php/XKore
xkore 2 , the datas actually completely controlled by bot, we block the packet from client if we don't like it, 

what about xkore 1 ? can we blocked datas from client ?
because server with CryptKeys , we need to synchronize the crypt_key between bot and client ( the crypt_key is shifting every sent packet until steady like the example i gave 0x253C )
we can make bot to follow the crypt_key from client, but can client follow crypt_key from bot ?
if xkore 1 can block packet from client, than we can make it clean
if not, i guess xkore 1 always dc no matter what

**Comment by alisonrag** [comment]
@c4c1n6kr3m1 
in the implementation of clientkeys to xkore1 and 3 openkore is saving and calculating in cache the current key, but i think because of this compacted packets openkore was disconecting, xkore 1 and 3 work in the same way, we can filter and block packets from client

**Comment by alisonrag** [comment]
we have a very important avance, months ago we was not able to connect using xkore 1, 2 or 3 using xkore cryptkeys

**Comment by c4c1n6kr3m1** [comment]
@alisonrag 
i mean, block datas from client to server
not from hijacked datas from server to client
if yes, than we can make it clean

**Comment by alisonrag** [comment]
All xkore work the same way, only the method is different all receive data from client decrypt and encrypt with current Key

**Comment by moneyisgod** [comment]
@sctnightcore do you think it can fix it : 

https://github.com/OpenKore/openkore/issues/1866 ?

**Comment by sctnightcore** [comment]
@moneyisgod  nope

**Pull request merged**
