### PR TITLE
fix: update xpmmake

### PR DESCRIPTION
**Pull request by alisonrag**
update xpm map generator

before:
before

after:
after

### CODE REVIEW

**Comment by ya4ept** [comment]
before:
image

after:
image

I don't see water

**Comment by alisonrag** [comment]
should be fixed now, can u test?
image

**Comment by ya4ept** [comment]
nice:
image

image

**Comment by ya4ept** [comment]
I am very happy to see that our artifacts are working!

**Review by ya4ept — APPROVED** [review]

**Pull request merged**
