### PR TITLE
fix iRO Restart

### PR DESCRIPTION
**Pull request by allanon**

### CODE REVIEW

**Comment by ZaskarAlpha** [comment]
thanks @allanon !

**Comment by brylle0714** [comment]
thanks @allanon

**Comment by xxchuckzxc** [comment]
thanks @allanon

**Comment by iRObotzz** [comment]
thank you for fixing this with your programming magic!

**Comment by jomarlorica** [comment]
@allanon iRO Thor Renewal cant connect. anything. everything can you help us?

**Pull request merged**
