### PR TITLE
change wx npc portal dot color

### PR DESCRIPTION
**Pull request by c4c1n6kr3m1**
@Nipodemos ask this on https://github.com/OpenKore/openkore/pull/2429
don't merge until code review by an elder
i don't know what color to use , but i put cyan

### CODE REVIEW

**Comment by Nipodemos** [comment]
oh, that's very nice 😄 
do you have any screenshots of how it is now?

**Comment by c4c1n6kr3m1** [comment]
[[https://images2.imgbox.com/cb/52/fEhj25Pq_o.png|alt=octocat]]
[[https://images2.imgbox.com/75/5f/tlga0GqK_o.png]]

f*

**Comment by c4c1n6kr3m1** [comment]
image2
image2

f*

**Comment by ya4ept** [comment]
Now the point with the NPC has two notation:
1. NPC name
2. portal destination name

Looks very bad:
morocc

**Comment by ya4ept** [comment]
please, see my PR #2966

**Comment by c4c1n6kr3m1** [comment]
i know i miss something heh

**Comment by Nipodemos** [comment]
whaaaaaat
yaept just send a PR to fix the error he pointed at
to me it was just fine

**Comment by c4c1n6kr3m1** [comment]
well , i want to change the parse , which ridiculous reading the portals.txt twice
since yaept already did ...

**Comment by Nipodemos** [comment]
i guess he didn't changed the dot color, but you will problably make another PR on top of his code

**Comment by ya4ept** [comment]
> i guess he didn't changed the dot color, but you will problably make another PR on top of his code
@Nipodemos I applied the current patch (changed color)

**Pull request closed without merging**
