### PR TITLE
[iRO] Unfreeze char after map loaded

### PR DESCRIPTION
**Pull request by sctnightcore**
- [x] iRO:RE
- [x] iRO:ReStart

### CODE REVIEW

**Comment by c4c1n6kr3m1** [comment]
just tested, renewal and restart still use 00A7 for item_use

**Comment by sctnightcore** [comment]
ah = = Test with 00A7 it work :p

**Comment by c4c1n6kr3m1** [comment]
restart does not send 0447 , 
yet?

**Comment by sctnightcore** [comment]
@c4c1n6kr3m1  Can u check it? 

I dont have iRO_Restart client .

**Comment by c4c1n6kr3m1** [comment]
yes. i tested it , restart don't send 0447
it's weird isn'it , may be they put it letter

**Comment by sctnightcore** [comment]
@c4c1n6kr3m1 
Maybe problem is unfreeze char not use item.

**Comment by c4c1n6kr3m1** [comment]
as i said, restart client doesn't send 0447 right now
you shouldn't rush

**Comment by lututui** [comment]
@Fadreus Does this still work (after my change)?

**Pull request merged**
