### PR TITLE
Initial release itemlink solver

### LINKED ISSUE #2477: <ITEML> feature
## ------------------ Openkore Issues Template ------------------
* **Openkore version git**: 4c33ea5bd02630fcc53c1156533c47a240b47960
* **Server**: idRO_Renewal (can be appear in other servers)
* **Bug Report / Feature Request**:
Feature Request
* **Summary**:
Parsing all string inside `<ITEML>somebytestring</ITEML>` from RO client feature: Shift+Left-click.
This message can be appear in public chat or broadcast message

The basic pattern is
`<ITEML>000000000&00(00(00(00(00</ITEML>`
later if the equip is refned, becomes
`<ITEML>000000000%0n&00(00(00(00(00</ITEML>` (added `%0n` before `&00`)
and `(00` will be becomes `(1nn` if there's the card or char_id for forger/item created
then the `&00` is equip location~~, if link the item from equipment window the value becomes `&nn`~~

Example from log

image
image

```
645 Concentration Potion
<ITEML>000000ap&00(00(00(00(00</ITEML>
30 30 30 30 30 30 61 70
26 30 30
28 30 30
28 30 30
28 30 30
28 30 30

656 Awakening Potion
<ITEML>000000aA&00(00(00(00(00</ITEML>
30 30 30 30 30 30 61 41
26 30 30
28 30 30
28 30 30
28 30 30
28 30 30

657 Berserk Potion
<ITEML>000000aB&00(00(00(00(00</ITEML> 
30 30 30 30 30 30 61 42
26 30 6a
28 30 30
28 30 30
28 30 30
28 30 30

15042 White Wing Suit [1] LUK+4:LUK+3:CRIT+5
<ITEML>0000g13UC&00(00(1eF(1eE(1eQ</ITEML>
30 30 30 30 67 31 33 55 43
26 30 30
28 30 30
28 31 65 46
28 31 65 45
28 31 65 51

15042 White Wing Suit [1] Evil Druid Card:Sharp 2:LUK+2:LUK+1
<ITEML>0000g13UC&00(14N(1fH(1eD(1eC</ITEML>
30 30 30 30 67 31 33 55 43
26 30 30
28 31 34 4e
28 31 66 48
28 31 65 44
28 31 65 43

2589 +9 Fallen Angel Wing [1] EA1:EA3:EA1
<ITEML>000041FL%09&03(00(1fW(1fY(1fW</ITEML>
30 30 30 30 34 31 46 4c
25 30 39 # refine +9
26 30 33
28 30 30
28 31 66 57
28 31 66 59
28 31 66 57

1726 +8 Rune Hunter Bow [1] Archer Skeleton Card
<ITEML>0000y1rQ%08&0b(142(00(00(00</ITEML>
30 30 30 30 79 31 72 51
25 30 38 # refine +8
26 30 62
28 31 34 32
28 30 30
28 30 30
28 30 30

2115 +4 Valkyrja's Shield [1] Thara Frog Card
<ITEML>0000w1y7%04&04(13s(00(00(00</ITEML>
30 30 30 30 77 31 79 37
25 30 34 # refine +4
26 30 34
28 31 33 73
28 30 30
28 30 30
28 30 30

20510 Costume Sword Wing
<ITEML>0028815kO&0j(00(00(00(00</ITEML>
30 30 32 38 38 31 35 6b 4f
26 30 6a # from Equip window, costume garment
28 30 30
28 30 30
28 30 30
28 30 30

1746 +7 Elven Bow [1] Archer Skeleton Card
<ITEML>0000y1sa%07&0b(142(00(00(00</ITEML>
30 30 30 30 79 31 73 61
25 30 37 # refine +7
26 30 62 # from Equip window, 2-hand weapon same value
28 31 34 32
28 30 30
28 30 30
28 30 30

19543 Oliver Wolf Hood
<ITEML>000gw155d&dH(00(00(00(00</ITEML>
30 30 30 67 77 31 35 35 64
26 64 48 # from equip window, costume headgear top
28 30 30
28 30 30
28 30 30
28 30 30

20166 Costume Hockey Mask
<ITEML>001B615fg&5q(00(00(00(00</ITEML>
30 30 31 42 36 31 35 66 67
26 35 71 # from equip window, costume headgear mid-bottom
28 30 30
28 30 30
28 30 30
28 30 30
```

### PR DESCRIPTION
**Pull request by cydh**
* Fixed #2477
* Attempts to solve message with `<ITEML>.*</ITEML>` into readable itemname
* Added debug message (if set) to show the raw message
* For hooks, the 'solved' message is the main message string, and the plain text as a separated parameter 'RawMsg' (except parseMsg/addPrivMsgUser as 'rawMsg')
* Thanks to @lututui @exaxia @jchcc

I set function name as `solveMessage` because think there are another client function to link such `<NAVI>, <URL>, <ITEM>, <ITEMLINK>, <INFO>` that mostly used in npc dialog, maybe can be used here (or not, or maybe I missed something xd)
TODO maybe in different function, to make command to replicate client Shift+Click item (inventory, cart, equip window) into `<ITEML>.*</ITEML>` string. such
* `i link <index>`
* `cart link <index>`
* or for evil way (that I currently use now) to generate any item ID into iteml, well, this is dangerous LOL

### CODE REVIEW

**Comment by cydh** [comment]
no one really want to test or review?

**Comment by alisonrag** [comment]
i will test soon in a private server, can you send me a message in discord to remember me tomorrow?

**Comment by cydh** [comment]
ok 12 minutes to tomorrow on my timezone :rofl:

**Comment by alisonrag** [comment]
> ok 12 minutes to tomorrow on my timezone

hahahahah 11 hours until tomorrow in my timezone

**Pull request merged**
