### PR TITLE
Exchange checkLineWalkable for canMove and fix follow sitAuto Idle

### PR DESCRIPTION
**Pull request by Henrybk**
Right now even when openkore is following another player it will activate sitAuto Idle, that is not correct based on our wiki.
This pull fixes that and also fixes some wrong distance checks and walkable line checks (canMove was based on rathena/hercules checks)

### CODE REVIEW

**Comment by alisonrag** [comment]
miss update checkLineWalkable to can move in:
https://github.com/OpenKore/openkore/blob/613bd3e322d18967b761337630b51e5b44a3de07/plugins/needs-review/freeCast/trunk/freeCast.pl#L121

and:
https://github.com/OpenKore/openkore/blob/613bd3e322d18967b761337630b51e5b44a3de07/plugins/needs-review/autowarp/trunk/autowarpn.pl#L119

**Comment by alisonrag** [comment]
also what is the difference between distance and blockDistance?
some places in code still use distance

**Comment by Henrybk** [comment]
Distance is regular euclidean distance, blockDistance is the minimum distance from 2 cells in a grid that allow diagonal movement

Is this image distance is in red and blockDistance is in green

image

**Review by alisonrag — APPROVED** [review]

**Comment by Henrybk** [comment]
Em qua., 3 de mar. de 2021 às 22:57, Alison <notifications@github.com>
escreveu:

**Comment by ya4ept** [comment]
@Henrybk Why did you remove `followCheckLOS` if it is in use in src/AI/CoreLogic.pm:
изображение

**Pull request merged**
