### PR TITLE
Update iRO Re:start files 19/09/2018

### PR DESCRIPTION
**Pull request by PipeDeveloper**
Tested and working

### CODE REVIEW

**Comment by Skye168** [comment]
How did you find new value for shuffle.txt?  I read from the old request but couldn't figure out. Thank you.

**Comment by arkhomr** [comment]
it not ok

**Comment by Limitedzx** [comment]
It works. Thanks you

**Comment by Darkultima** [comment]
I solved as you said but is not working -> Failed to Connect to Server

**Comment by Limitedzx** [comment]
It works. Thanks for contribution.

**Comment by arkhomr** [comment]
it not connect map server

**Comment by anonp26** [comment]
it not connect map server it not ok

**Comment by Zelecktor** [comment]
@arkhomr
@anonp26
@divinenz

Already checked my files and they are fine. All working

captura

**Comment by PipeDeveloper** [comment]
@arkhomr
@anonp26
@divinenz

Already checked my files and they are fine. Working

captura

**Comment by Nipodemos** [comment]
@Fadreus please, can you test for us?

**Comment by ioaltisgithub** [comment]
It's not working on iRo (Renewal server). please

**Comment by Zelecktor** [comment]
@ioaltisgithub
Read the title please, it is for re:start

**Comment by ioaltisgithub** [comment]
@Zelecktor oh, I'm so sorry. Well, there is no update packet for renewal server, right?

**Pull request merged**
