### PR TITLE
[Fix] fix buy when npc is ParaMarket

### LINKED ISSUE #3370: I can't buy an arrow from a new NPC in prontera city, npc prt_in 162 135 clip is not correct, can anyone know, can you tell me?
buyAuto Arrow {
	npc prt_in 162 135
	npc_steps c r0 
	isMarket 0
	standpoint
	distance 9
	price
	minAmount 50
	maxAmount 3000
	batchSize
	disabled 0
	maxBase
	minBase
}

### PR DESCRIPTION
**Pull request by sctnightcore**
close #3370

- [ ] autobuy .
- [x] `buy` command

if we use `buy` command . it working

### CODE REVIEW

**Review by ya4ept — APPROVED** [review]
looks nice

**Comment by alohathdz** [comment]
image
`buyAuto Arrow {
	npc payon_in01 8 132
	npc_steps c r0
	isMarket 0
	distance 5
	minAmount 10
	maxAmount 4000
	zeny >= 4000
}`

not buy item

**Review by sctnightcore — COMMENTED** [review]
https://github.com/OpenKore/openkore/blob/644e361a58ceffa7e8a1fa38df1eb72cefd33b67/src/AI/CoreLogic.pm#L2039-L2040

if _isMarket == 1 
 use b step ?

**Comment by alisonrag** [comment]
@alohathdz 
try this:
```
buyAuto Arrow {
  npc payon_in01 8 132
  npc_steps c r0
  isMarket 1
  distance 5
  minAmount 10
  maxAmount 4000
  zeny >= 4000
}
```

**Comment by voyfmyuh** [comment]
I am currently facing the same problem, I have used the latest openkore, the purchase of arrows will still show Npc did not respond.

My server TWRO

**Pull request merged**
