### PR TITLE
New pathfinding A* algorithm review

### LINKED ISSUE #2546: Bot stucks
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
 
* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

Hi everybody! 
I cant solve my problem, need your help. 
Sometimes bot is trying to catch occupied by monster/player cell and doind strange fast back-forward movements close to that cell. I dont know the reason why.
Do you have any advices how to explain him to check the cell before he wants to go there. And recalculate his route if it needs.

### PR DESCRIPTION
**Pull request by Henrybk**
This is the reviewed and cleaned branch of the pathfinding algorithm changes.

Openkore uses an old A* code for pathfinding, it has a few problems:
```
1 - It is not capable of calculating diagonal movement.
2 - Uses only distance to walls to calculate cells weighting.
3 - Is not capable of dynamic weight changes of cells since the weight is hard coded in distance to walls.
4 - Is not guaranteed to find the shortest paths.
5 - runfromTarget, attackCheckLOS and AttackCanSnipe don't work.
```

This branch fixes a few isses.

Features:
```
1 - Uses new simplified fld2 files
2 - Uses .weight files based on .dist files instead of .dist files, allowing custom static or dynamic weight maps (avoid mvps, non-walking mobs, dangerous map areas)
3 - Correctly uses diagonals, using weight 1.4 that of ortogonal moving
4 - Uses diagonal distance heuristic, which is the most appropriate for ragnarok maps
5 - Is guaranteed to always find the shortest / best path since it does not limit openlist
6- Fixes runfromTarget, attackCheckLOS and AttackCanSnipe
7- Corretly predicts the time to walk a given distance, preventing a few timeouts
```

Edit: Most of the changes were ideas from here: http://forums.openkore.com/viewtopic.php?f=36&t=1350

this pull fixes #2546.

This pull is a continuation of #1684.

The code was based on Sven Konig publications (Father of most of the pathfinding algorithms used today): http://idm-lab.org/publications.html

### CODE REVIEW

**Comment by Xmpeshka** [comment]
Thx - it's works, but in xkore1 i have same microfreezes as at this video https://youtu.be/MWEnuPa0D0U
On rms on xkore2 - all was ok

**Comment by Henrybk** [comment]
@Xmpeshka Thanks for the reply, I have made a lot of changes since you made this video, would you be able to test again in xkore1 to see if it persists?

**Comment by Xmpeshka** [comment]
i downloaded Remake-routing-review today, test it on rms server in xkore 2 - al was ok
then i change servertypes for my server and run in xkore 1 - got microfreezes

**Comment by something990** [comment]
hi what ragnarok can i use this? can i use this on Philippine Ragnarok?

**Comment by Henrybk** [comment]
@Xmpeshka Have you tried increasing this PR route_step? you should still be able to use values as high as 14, I only decreased it for compatibility issues, but 10 should still be very well handled.

**Comment by Xmpeshka** [comment]
I try  route_step 9 - still got freezing
At 10+ - kore don't move

**Comment by Xmpeshka** [comment]
Upd: with PR - 9 - freeses a bit lower, bun 10+ kore can't move (from macro move command)

**Comment by Xmpeshka** [comment]
is it any way randomize route ?- don't use every time best way
because if many bots on a location - all of them going step by step in certain sites of location - it looks like big train of bots )

**Comment by Henrybk** [comment]
@Xmpeshka This is an old problem in pathfinding (example: https://forum.unity.com/threads/navmesh-agent-introduce-noise-into-path.166183/). What should be easy to do is to set an option in in the pathfinding to call to add a bit of noise (randomness) in the calculation, so all paths should look similar but not the same.

**Comment by Xmpeshka** [comment]
If it possible - it will be a good to impiment it there. Wigh noise config key =))
p.s. please take a look at route_step - all values higher then 9 - no movement.

**Comment by Xmpeshka** [comment]
image
Rms test server - route step14

**Comment by Henrybk** [comment]
@Xmpeshka O thanks for the prints. Yeah, there is a check that makes route_step > 10 impossible, I can't change it right now but you can change it yourself in your branch and test it.

On Task::Route, in sub iterate at line 451 change:
`if (blockDistance(\%nextPos, $current_pos) > 10) {`
to:
`if (blockDistance(\%nextPos, $current_pos) > xxxxxxxx) {`
'xxxxxxxx' being the route_step you want to test +1.

**Comment by Xmpeshka** [comment]
thx - it works )

ezgif-1-2c4e2cafd473

**Comment by Xmpeshka** [comment]
another bug:
sometimes kore randomly stand for about 10 secs in clean fild
image
then - works normal some time - then stand again - this bug also have a master-branch - but not so often

**Comment by Henrybk** [comment]
That is just lag, the move packet will be re-sent until the server responds.

**Comment by Xmpeshka** [comment]
> That is just lag, the move packet will be re-sent until the server responds.
if i move directly from client - all is ok, not the lag 
if i print "ai clear" kore starts moving until next stop

**Comment by c4c1n6kr3m1** [comment]
@ Henrybk
is randomize path finish?
is sleepTime affect meetingpoint prediction ?

**Comment by hubertyang88** [comment]
#1735 freeze problem?

**Comment by Xmpeshka** [comment]
No,  screenshot upper, no mapchange or tele, after random time - kore stops in random place on map then after 5-10 secs continue route

**Comment by Xmpeshka** [comment]
got a stuck ) 
image

**Comment by hubertyang88** [comment]
I try to run this version , https://github.com/OpenKore/openkore/blob/cee04dc7bb9d940c7e4dd03fd11f9f080275ad47/

But I get error ,and openkore fail to start , what should I do?
Error message:
Can't call method "closestWalkableSpot" on an undefined value at src/Misc.pm line 3712.

Stack trace:
Can't call method "closestWalkableSpot" on an undefined value at src/Misc.pm line 3712.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x61945fc)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

line of error:
  				my %dest = %{$mapPortals{$map}{$portal}};
* 				my $closest_start = $field->closestWalkableSpot(\%start, 1);
  				my $closest_dest = $field->closestWalkableSpot(\%dest, 1);

**Comment by alisonrag** [comment]
You should use the branch related to this pull
Dont use versions related to master

**Comment by hubertyang88** [comment]
> You should use the branch related to this pull
> Dont use versions related to master
@alisonrag 
How to do that? 
I try to download zip at Remake-routing-review，it seems worse . So I found the link in "Files changed" --> "view file" , there is a link https://github.com/OpenKore/openkore/blob/cee04dc7bb9d940c7e4dd03fd11f9f080275ad47/
and I use DownGit to download ..  What is wrong?

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore/archive/Remake-routing-review.zip

**Comment by hubertyang88** [comment]
@alisonrag 
I try your link , the error remains , and it happened at compiling the portals, So I copy portals and portallos file to avoid this step  , and I get an other error 
It seems some file are missed in the zip file I download...

new error:
Error message:
Undefined subroutine &Utils::makeWeightMap called at src/Field.pm line 645. 
Stack trace:
Undefined subroutine &Utils::makeWeightMap called at src/Field.pm line 645.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x5309b44)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

error
  			my $f;
* 			$self->{weightMap} = Utils::makeWeightMap($self->{dstMap}, $width, $height);
  			if (open($f, ">", $weightFile)) {

**Comment by Xmpeshka** [comment]
i decide test it again ) and got another stuck at 3 different "workers" )
image
when i typed "ai clear" fabre was killed and "worker" continue moving and attacking normaly

**Comment by Henrybk** [comment]
@Xmpeshka Sorry for the late answer. Yes, I was able to identify not one, but a few, bugs in the way my code decides to approach a target while attacking, I am currently testing the fix. Thanks for testing.

**Comment by Xmpeshka** [comment]
When i first tried to run this build on rms server i see that at route_step 7 - bot moves smoothly
but on euro/rro it moves jerky - step 15 solve this problem but got random "afk" (don't know if it was on rms, cause i don't test on rms so long)

Also if bot got agi up on rro/euro with step 15 movement becomes jerking, step 17 - "fix" it, but random afk appears(sometimes it happens a bit w step 15 too) - but not so long as in your build

**Comment by Henrybk** [comment]
@Xmpeshka All the attack bugs should be fixed new, I ran it for about 6 hours with a meele character without any issues, both ranged characters and slaves need more testing though.

**Comment by Xmpeshka** [comment]
got a move bug in 7 min from start on 2 windows
https://youtu.be/riA9gjDTXdk
and loot taking looks strange

**Comment by Henrybk** [comment]
Hello @Xmpeshka, thanks again for testing, I had forgotten to change attackDistance and attackMaxDistance in config.txt to 1, as they should always be for meele characters. Please use route_step 7 as it is the one that best resembles the normal openkore behaviour. I also added a new config.txt key attackUpdateMonsterPos that should fix position lag, please make sure your config.txt is uptodate. Thanks again.

**Comment by Xmpeshka** [comment]
i can't use step 7 - cause it can't move normal ))
https://youtu.be/A1eeHoxDn8I
attackUpdateMonsterPos  was 1 - i took clean new config from this branch

**Comment by Henrybk** [comment]
That is very strange, it seems to be only moving about 3 or 4 cells at a time, can you make a video of the console and character with route_step 7 as you did before? Thanks

**Comment by Xmpeshka** [comment]
https://youtu.be/QJHPwGWcJgs
done

**Comment by Henrybk** [comment]
7280c4f03ba8f01aa5cf876fef39fa31
Seems like the route messages are been filtered, this is how it should look like, with the "Route You" debugs.

**Comment by Xmpeshka** [comment]
https://youtu.be/EhRBD6pVlg8
sorry, my fault - it was set in start macro

**Comment by Henrybk** [comment]
Now the routing algorithm should be a bit more responsive and you should be able to use route_step up to 10 (the max I tested) without issues.

**Comment by Xmpeshka** [comment]
I replacerd all route.pm file and add line in timeouts
Nothing happens ( 
step 7-10 jerky moving
step 14 stays and "smoking"
image

**Comment by Henrybk** [comment]
Well, this has been a wild ride, there were a few reference bugs in route.pm and a line of code was blocking route steps above 13 to work, this last commit *should* fix that. Thanks for your patience.

**Comment by Xmpeshka** [comment]
image
stuck on mapRoute
and same on randomRoute
image

**Comment by Xmpeshka** [comment]
image
image
and after that 
image

it became better - still got stucks on route - but it "self fixes in 3-4 secs"
image

**Comment by Henrybk** [comment]
The code that tried to unstuck was not working, it now works, sometimes the move pair (start cell and destination cell) is just not a valid one, and sending the move packet won't work, I had this happen in new_1-3, moving from 64,139 to 79,138, the server will just ignore the packet, this happens because there is a "Field of view" check that also uses the distance between cells in the server. At the moment I don't know exactly how it works.

**Comment by Xmpeshka** [comment]
image
random route atm,

**Comment by Henrybk** [comment]
Yes, but the timeout key is not doing anything even in the normal openkore master right now, I'll fix it in a minute

**Comment by Xmpeshka** [comment]
and another long stuck at attack 
image

**Comment by Henrybk** [comment]
Now these timeout keys should work:

ai_move_retry 0.25 - The time to wait between move packet sends
ai_move_giveup 1 - The time to wait before giving up the move packet

Maybe now you would have a better experience trying route_step 9~11 instead of 15

**Comment by Xmpeshka** [comment]
ai_move_retry 0.15 + step 9 now looks normal(0.25 at horisontal movement was a little jerky ) thank u

**Comment by Henrybk** [comment]
It is I that must thank you for testing so much of my code and so many times haha

**Comment by Xmpeshka** [comment]
i also have a feature request: 
adjust distance that random walk chose point to move + option don't calc a new route after killing mob before old point wasn't reached. For exaple start from one corner of map and move continiously about 300 cells way, killing mobs during this trip, then calc a new long route...

Now kore sometimes cals route like chaotic random ) and bot runing from point to point in one part of map, not like player wiil.

**Comment by Henrybk** [comment]
I believe that was made that way for a reason, but I don't remember what reason exactly. This can be achieved by using plugins, I have made a in the past plugin that does that actually, but you had to manually insert the desired route, there is also the waypoints plugin, but I never used it. 

But the 2 features you asked could be implemented using config keys with a little code change.

**Comment by Xmpeshka** [comment]
https://youtu.be/FTQpZkJwTqI
a strange "dancing" movement
https://youtu.be/I4VtVQp9roA
overall video, where we can se thar random routes decide where to go very strande, prefer south part of map

**Comment by Henrybk** [comment]
Both videos are set to private

**Comment by Xmpeshka** [comment]
fixed)

**Comment by Henrybk** [comment]
In the first video you are trying to attack a monster that is on the other side of the cliff, which yelds a very long route, this should be prevented by having attackCheckLOS in the config set to 0 (for meele characters). What is your attackCheckLOS setting?

**Comment by Xmpeshka** [comment]
yes - it was 1 ) changed to 0

**Comment by alisonrag** [comment]
> i also have a feature request:
> adjust distance that random walk chose point to move + option don't calc a new route after killing mob before old point wasn't reached. For exaple start from one corner of map and move continiously about 300 cells way, killing mobs during this trip, then calc a new long route...
> 
> Now kore sometimes cals route like chaotic random ) and bot runing from point to point in one part of map, not like player wiil.

u can keep the old route in ai by reverting this pull request:
https://github.com/OpenKore/openkore/pull/2261/files

but openkore will have a issue that when to many monster in screen openkore will move away then back to kill

**Comment by Xmpeshka** [comment]
New bug =) 
image

**Comment by Henrybk** [comment]
That one I have not yet been able to reproduce.

**Comment by Xmpeshka** [comment]
mon_control on fabre 0 and attack other mobs, so bot runing and collect agro fabre

**Comment by Xmpeshka** [comment]
image

**Comment by Henrybk** [comment]
Oh, okay, got it

**Comment by Henrybk** [comment]
That last bug should be fixed by these last commits

**Comment by hubertyang88** [comment]
what environment do this branch need ? I download this link https://github.com/OpenKore/openkore/tree/Remake-routing-review
but can't run . first , I had XSTools problem , I copy XSTools from some older version , and then wxstart.exe will stuck at process maps
can any one fix a manual about how to run this

**Comment by alisonrag** [comment]
> what environment do this branch need ? I download this link https://github.com/OpenKore/openkore/tree/Remake-routing-review
> but can't run . first , I had XSTools problem , I copy XSTools from some older version , and then wxstart.exe will stuck at process maps
> can any one fix a manual about how to run this

i updated the dll's and gitignore, try again now

result:
image

**Comment by M45T3Ryu** [comment]
It is still not opening, I tried with Perl and the wxstart.exe and start.exe

tried

**Comment by alisonrag** [comment]
@M45T3Ryu
This version works only in perl 5.12 32 bits(x86)

Try this http://strawberryperl.com/download/5.12.3.0/strawberry-perl-5.12.3.0.msi

Just need to run in cmd
`cpan install Win32-Console`

Then run openkore.pl

**Comment by M45T3Ryu** [comment]
I found out that it gets stuck on long routes like it just stops doing everything, and does absolutelly nothing

**Comment by alisonrag** [comment]
@M4T3Ryu
Vídeo? How to reproduce? Config? Server? AI sequence? Console debug?

**Comment by hubertyang88** [comment]
@M45T3Ryu 
try to set  
route_step 9

**Comment by alisonrag** [comment]
### Route Attack
- [x] regular attack melee
- [x] regular attack ranged

### Route Skill 
- [x] attack skill slot melee - OK
- [x] attack skill slot ranged - OK
- [x] party skill ranged - OK

### Route Follow 
- [x] follow - OK

### Route Slave
- [ ] mercenary + master attack
- [ ] mercenary only
- [ ] homunuculus + master attack
- [ ] homunuculus only

### Route others
- [x] canSnipe - OK
- [ ] LOS
- [ ] runfromtarget

### Route Teleport
- [x] route_teleport - OK
- [x] teleSearch - OK

### Route
- [x] map route
- [ ] route (issue while trying to move related at https://github.com/OpenKore/openkore/pull/2871#issuecomment-678861090)
- [x] move
- [x] pathfind

**Comment by alisonrag** [comment]
error while randomwalk sometime it stucks near from "objects" / walls / not walkable cells

Log: https://wtools.io/paste-code/b3NI

another stuck print:
image

**Comment by ya4ept** [comment]
@alisonrag don't forget to add a new parameter to the documentation "maxDist" (https://github.com/OpenKore/openkore/pull/2871/commits/be589b167e7eda448329b213aae4be0cf1412260)

**Comment by alisonrag** [comment]
> @alisonrag don't forget to add a new parameter to the documentation "maxDist" ([be589b1](https://github.com/OpenKore/openkore/commit/be589b167e7eda448329b213aae4be0cf1412260))

when everything has been tested and this pull request is ready i will add to documentation.
add now can lead a people to use a no implemented feature
but thanks for remember

**Comment by alisonrag** [comment]
the only thing missing is try to find why sometimes it stuck near to the walls / non walkable cells

the rest seems ok

obs:
using route_step 10 seems like stuck issue not appear for a while

**Comment by alisonrag** [comment]
last commit should fix the route stuck issue

**Review by alisonrag — APPROVED** [review]

**Comment by ya4ept** [comment]
изображение


let's update the documentation

**Comment by alisonrag** [comment]
https://openkore.com/wiki/MaxDist

**Comment by hubertyang88** [comment]
Congratulations! I am gonna try it

**Comment by alisonrag** [comment]
> Congratulations! I am gonna try it
> Just need to download the latest master or still need to download Remake-routing-review?

just download the `master and **dont** use a old `config.txt`

**Comment by hubertyang88** [comment]
something wrong with mon_control.txt
when I set 
1081 0 0 0
kore will leave Yellow Plant alone
but when I set 
黄草 0 0 0  #“Yellow Plant 0 0 0”
kore will attck 1081 , something wrong with chinese name?

**Comment by alisonrag** [comment]
> something wrong with mon_control.txt
> when I set
> 1081 0 0 0
> kore will leave Yellow Plant alone
> but when I set
> 黄草 0 0 0 #“Yellow Plant 0 0 0”
> kore will attck 1081 , something wrong with chinese name?
> 
> this also affect attackSkillSlot when use monsters
> but chinese name of some event monster works , kore didn't read monsters.txt only read new monsters ?

Can u open a issue?

**Comment by ya4ept** [comment]
Please add a description of the new config parameters:
1. attackRouteMaxPathDistance 
2. attackUpdateMonsterPos
3. runFromTarget_maxPathDistance

As well as a description of the new timeouts:
1. ai_attack_route_adjust
2. ai_attack_failedLOS

**Comment by alisonrag** [comment]
> Please add a description of the new config parameters:
> 
> 1. attackRouteMaxPathDistance
> 2. attackUpdateMonsterPos
> 3. runFromTarget_maxPathDistance
> 
> As well as a description of the new timeouts:
> 
> 1. ai_attack_route_adjust
> 2. ai_attack_failedLOS

1. https://openkore.com/wiki/AttackRouteMaxPathDistance
2. https://openkore.com/wiki/AttackUpdateMonsterPos
3. https://openkore.com/wiki/RunFromTarget_maxPathDistance
4. https://openkore.com/wiki/Timeouts.txt#AI_Route

**Comment by ya4ept** [comment]
@Henrybk @alisonrag 
should we replace all `distance ()` calls with `blockDistance ()`?

**Comment by alisonrag** [comment]
> @Henrybk @alisonrag
> should we replace all `distance ()` calls with `blockDistance ()`?

blockdistance seems more like client, but we need to check what happens with this change, how different openkore will act

**Pull request merged**
