### PR TITLE
[InventoryList] itemList more support

### LINKED ISSUE #2983: [iRO] Inventory, Storage, Cart issue
## ------------------ Openkore Issues Template ------------------
* **Openkore version git**: 
https://github.com/OpenKore/openkore/tree/4620b597a8217c338c6ee417f32e3f61ea18930d
* **Server**: 
iRO

* **Bug Report**:

* **Summary**:
issues like:
item list not avaliable after teleport
item name wrong
pickupitems is not working properly
storage with duplicated items

#2943 
#2928 

@ edit
it is caused by a new unpack string in cards, nameID and amount

### PR DESCRIPTION
**Pull request by alisonrag**
this pull fixes #2983, #2998

### CODE REVIEW

**Comment by hubertyang88** [comment]
tested in cRO , it works 
don't forget include cRO where iRO_renewal is

**Comment by Nipodemos** [comment]
iRO is already closed? if is still open, can someone test there?

**Comment by alisonrag** [comment]
> iRO is already closed? if is still open, can someone test there?

its closed until feb, 2020

but in bRO, tRO and cRO work the same way

**Comment by mcpchen** [comment]
CRO is not work 
I download Latest commit 2035f38 Jan 2, 2020
command I “”Inventory is not available“”
Packet Tokenizer: Unkown switch:0B1B
open ALT+E Inventory is empty

**Comment by mcpchen** [comment]
> tested in cRO , it works
> don't forget include cRO where there is iRO_renewal

哥们你好。我下载1月2日的更新包还是报错，物品里面没显示东西。还是有好多封包问题。
方便加QQ2356507或者WX:bet28365交流一下。

**Comment by alisonrag** [comment]
Need to update cRO recvpackets

**Pull request merged**
