### PR TITLE
Add LWP::UserAgent to openkore

### PR DESCRIPTION
**Pull request by sctnightcore**

### CODE REVIEW

**Comment by lututui** [comment]
Why?

**Comment by itsrachelfish** [comment]
I agree. Why? Is there a specific plugin you are using that requires this?

**Comment by alisonrag** [comment]
kRO and ruRO uses authentication based in web token
https://github.com/alisonrag/Openkore-Plugins-Scripts/tree/master/ZeroAuth

**Comment by lututui** [comment]
Package it with the plugin, kore doesn't need it

**Comment by Nipodemos** [comment]
as mentioned, it is better to make a standalone plugin and install this package manually, it's not that hard

**Pull request closed without merging**
