### PR TITLE
Talknpc rework

### PR DESCRIPTION
**Pull request by farrainbow**
This branch is for finishing, testing and merging the better parts of https://github.com/OpenKore/openkore/pull/363.

There should be no subtasks related to routing on anything like that, which would be done separately (https://github.com/OpenKore/openkore/pull/398).

### CODE REVIEW

**Comment by Henrybk** [comment]
Sorry for not talking about this for 2 months hehe.

I guess these changes were tested and they fix many many bugs, it would be good to test them a little more and commit it.

**Comment by Henrybk** [comment]
@farrainbow I found a pretty bad problem, macro plugin will only continue if AI is 'macro' or 'deal', when we push 'NPC' into AI macro that used 'talk' command will get bugged.

**Comment by Henrybk** [comment]
The last commit fixed the 2 bugs I reported yesterday.

**Comment by lututui** [comment]
@Henrybk don't forget to push that backwards compatibility here

**Comment by Henrybk** [comment]
Added backwards compatibility for 'talknpc n' and 'talk no'.

Also updated current master.

**Comment by Henrybk** [comment]
Last commit fixed #247 , but it needs to be tested. Now talknpc will only try to talk to visible npcs, if there are more than 1 npc on the same cell it will always choose the first visible one.

**Comment by flacrasec** [comment]
This is sooo nice it solved many problems fantastic job! =)

**Comment by Henrybk** [comment]
Last commit fixed a bug where npcs who initiate the talk by themselves and have no interaction other than `close` would bug kore.
Also in the last commit added timeouts in timeouts.txt for npc interaction.

**Comment by lututui** [comment]
btw @Henrybk don't forget to add those config.txt and timeouts.txt keys to tables/bRO/control-br

I would do it myself, however I don't have push access like you cool kids. Can I haz? @itsrachelfish

**Comment by s936511** [comment]
Hello I am Taiwan's kou90258.
Use your coding test, after the actual test, in the talk cont / is normal, but after the #Response list of talk resp #, stopped. Does this need other settings?

**Comment by s936511** [comment]
Sale error 
OpenKore version what-will-become-2.1
@ai_seq = sellAuto
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2017_03_22
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/killcountFix/killcountFix.pl (killcountFix; description: fixes killcount quest goals on some servers)
  plugins/macro/avoidSkill.pl (avoidSkill; description: React to skills.)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)

Error message:
Can't locate object method "sendSellComplete" via package "Network::Send::twRO" at src/Network/Send/twRO.pm line 120.

Stack trace:
Can't locate object method "sendSellComplete" via package "Network::Send::twRO" at src/Network/Send/twRO.pm line 120.
 at src/Network/Send/twRO.pm line 120
	Network::Send::twRO::sendSellBulk('Network::Send::twRO=HASH(0x6294d1c)', 'ARRAY(0x460e80c)') called at src/AI/CoreLogic.pm line 1571
	AI::CoreLogic::processAutoSell() called at src/AI/CoreLogic.pm line 142
	AI::CoreLogic::iterate() called at src/functions.pl line 772
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4842d4c)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

In this line when out:
  	
* 	$self->sendSellComplete; #The server won't let us move until we send the sell complete packet. 
  }


for "Network::Send::twRO" at src/Network/Send/twRO.pm line 120.
sub sendSellBulk {
	my $self = shift;
	my $r_array = shift;
	my $sellMsg = "";

	for (my $i = 0; $i < @{$r_array}; $i++) {
		$sellMsg .= pack("v*", $r_array->[$i]{index}, $r_array->[$i]{amount});
		debug "Sent bulk sell: $r_array->[$i]{index} x $r_array->[$i]{amount}\n", "d_sendPacket", 2;
	}

	my $msg = pack("C*", 0xC9, 0x00) . pack("v*", length($sellMsg) + 4) . $sellMsg;
	$self->sendToServer($msg); 
}

OK!

**Comment by kaliwanagan** [comment]
@farrainbow @Henrybk are we still good for merging this?

I don't have a way to test this for now, so you'll have to help me out here :(

**Comment by Henrybk** [comment]
@kaliwanagan Yeah, I would love to see this tested and merged, I just fixed the last known bug.

**Comment by kaliwanagan** [comment]
@Henrybk speaking of testing, can we have some sort of test suite for the macro plugin?

I remember we used to have an openkore official server that bibian ran. We tested all kinds of plugins and and code there.

So for the macro plugin (because it's a whole new framework on top of openkore) maybe we can have a canonical macro that will exercise most of the code?

How about a macro that goes through the novice grounds, routes to prontera, kills porings until it loots a jellopy, and then sells the jellopy to a vendor?

This can be a smoke test for any updates to the macro plugin (or any of its dependencies, like this PR), so we can immediately detect a breaking change.

**Comment by flacrasec** [comment]
With this fix this Pull Request is 100% functional I'am using it about 1 month already and it is perfect.

**Pull request merged**
