### PR TITLE
update iRO Renewal files

### PR DESCRIPTION
**Pull request by allanon**
- [ ] QA Review

This pull request was auto-generated by patch_iro.pl: https://gist.github.com/allanon/38620af49d250005acbf

### CODE REVIEW

**Comment by sctnightcore** [comment]
#1351

**Comment by jomarlorica** [comment]
i dont know how to extract or put it on a file @sctnightcore can you arrange on the whole table folder? @allanon

**Comment by jomarlorica** [comment]
because of new maintenance this #1351 is not available for the renewal new patch. @allanon  @sctnightcore

**Comment by sctnightcore** [comment]
8ded656 @jomarlorica

**Comment by franzhiro12345** [comment]
how to put it what file pls help

**Comment by sctnightcore** [comment]
@franzhiro12345 
wait Merge ! and download new openkore !

**Comment by franzhiro12345** [comment]
okok tyvm hmm.. can you pls notify me if theres a new update/downlaod ty so much..

**Pull request merged**
