### PR TITLE
fixed the unshift function

### PR DESCRIPTION
**Pull request by ya4ept**
```
 macro unshift {
     &unshift(@monsters, Porint)
     &unshift(@monsters, Volf)
     &unshift(@monsters, Maya)
     log The array \@monsters has size @monsters and its members are $monsters[0], $monsters[1] and $monsters[2]
 }
```
if the array is empty then OpenKore gets a fatal error:
image

this patch fixes a bug:
image

### CODE REVIEW

**Comment by ya4ept** [comment]
yes, I have tested other functions. The problem only occurs with this function

> btw, nice idea of make a em command to eventMacro, i wish i had thought that back in the days

use config: [alias_em eventMacro](https://openkore.com/wiki/Alias)

**Comment by alisonrag** [comment]
> yes, I have tested other functions. The problem only occurs with this function
> 
> > btw, nice idea of make a em command to eventMacro, i wish i had thought that back in the days
> 
> use config: [alias_em eventMacro](https://openkore.com/wiki/Alias)

years using and developing openkore and i never see this haahah

**Comment by ya4ept** [comment]
maybe we can fix the original eventMacro command?

**Comment by Nipodemos** [comment]
both `em` and `eventMacro` commands should be official

**Pull request merged**
