### PR TITLE
Poseidon compatibility with bRO

### PR DESCRIPTION
**Pull request by lututui**
Adds missing charblocksizes to poseidon server
Adds bRO_2016-10-11a as a poseidon servertype
Adds '09D0' as a gameguard sync packet

### CODE REVIEW

**Comment by emsjustin** [comment]
Awesome lututui!
With this modifications is possible to use poseidon in bRo servers.
But, this update just respond one client per openkore ...

**Comment by Henrybk** [comment]
Can someone confirm this works?

**Comment by emsjustin** [comment]
This works.
But, need update every week because the bRo client change...

**Comment by lututui** [comment]
Updating the poseidon servertype is not mandatory. You can use older clients, as long as they are charblocksize 124.

**Pull request merged**
