### PR TITLE
[ Update ] Char creation remake

### PR DESCRIPTION
**Pull request by alisonrag**
add new server config key
```
# Character Creation Type
# 1 = 0x0067 - Classic Version , 
# 2 = 0x0970 - Classic Version without attribute, 
# 3 = 0x0A39 - Two Sex Account Version, 
# 4 = 0x0A39 - Doram Version
# the packet is not fixed player can define the type in servers.txt and the packetID in servertype
charCreationType <1|2|3|4>
```

tested in bRO ( this server still use old version 0067)
Dialog:
bro dialog

Confirmation:
bro confirmation

tested in iRO (this server have create_version = 0x0A39 )
Dialog:
iro dialog

Confirmation:
iro confirm

this pull have compatibility with old creation functions

### CODE REVIEW

**Comment by alisonrag** [comment]
i will document in wiki when this pull aproved

**Comment by alisonrag** [comment]
@lututui 
@allanon 
can some of you check?

**Comment by Nipodemos** [comment]
i resolved the conflicts of this branch

**Comment by alisonrag** [comment]
@lututui found some errors in this pull im waiting fir the review to fix

**Comment by alisonrag** [comment]
do not merge this, i need to remake this because a lot of things related to this pull was changed

**Pull request closed without merging**
