### PR TITLE
Add ping packet [0x0b1c] [0x0b1d]

### PR DESCRIPTION
**Pull request by sctnightcore**
```
#if PACKETVER_MAIN_NUM >= 20190227 || PACKETVER_RE_NUM >= 20190220 || PACKETVER_ZERO_NUM >= 20190220
struct PACKET_CZ_PING {
	int16 packetType;
} __attribute__((packed));
DEFINE_PACKET_HEADER(CZ_PING, 0x0b1c);
#endif

#if PACKETVER_MAIN_NUM >= 20190227 || PACKETVER_RE_NUM >= 20190220 || PACKETVER_ZERO_NUM >= 20190220
struct PACKET_ZC_PING {
	int16 packetType;
} __attribute__((packed));
DEFINE_PACKET_HEADER(ZC_PING, 0x0b1d);
#endif

```

### CODE REVIEW

**Review by alisonrag — CHANGES_REQUESTED** [review]
Move sub sendPing to Send.pm
And add it to Servertype0.pm
Also add check for xkore 1/3 because client auto reply, so using the current pull will cause in duplicated ping packet

**Comment by ya4ept** [comment]
@alisonrag  i also think "sub ping" needs to be moved to Receive.pm

**Comment by ya4ept** [comment]
merged after #3390
tested on **CircleRO** (#3389):
```
[CircleRagnarok]
ip 103.52.146.53
port 6900
master_version 12
version 55
serverType kRO_RagexeRE_2020_03_04a
serverEncoding Western
gameGuard 0
addTableFolders kRO/RagexeRE_2020_07_09a;iRO/official;iRO
charBlockSize 155
pinCode 1
charDeleteDateType 1
rankingSystemType 1
private 1
```

**Review by alisonrag — APPROVED** [review]

**Comment by apuk321** [comment]
maaf saya newbie tentang openkore, ada yang bisa bantu saya cara bot di private server ini? saya sudah coba cara di atas karena saya kurang terlalu paham jadinya error. apa bisa di bantu di buatkan openkorenya?
[PlayOdin]
ip 103.52.146.53
port 6900
master_version 12
version 55
serverType kRO_RagexeRE_2018_06_21a
serverEncoding Western
gameGuard 0
addTableFolders eA;kRO/RagexeRE_2018_06_21a;translated/kRO_english;kRO
charBlockSize 155
pinCode 1
charDeleteDateType 1
rankingSystemType 1
private 1
recvpackets recvpackets.txt

**Pull request merged**
