### PR TITLE
sT= RagexeRE_2016_01_06a = WORK !

### PR DESCRIPTION
**Pull request by sctnightcore**
image
WORK!! 

```
[sites.google.com/site/zoneteenroo/home]
ip 43.229.79.46
port 6900
master_version 7
version 56
serverType kRO_RagexeRE_2016_01_06a
serverEncoding Thai
charBlockSize 147
addTableFolders tRO
//recvpackets = https://pastebin.com/iXxeLF8w 
//dont use packet key XD
```

IDTEST:openkore
PASS:openkore

IDTEST:openkore01
PASS:openkore

@alisonrag  @Henrybk  @allanon  @lututui  @Mortimal

### CODE REVIEW

**Comment by Junezavr** [comment]
^^

**Comment by alisonrag** [comment]
@sctnightcore 
do you have something more to update or can we merge this pull?

**Comment by sctnightcore** [comment]
none
@alisonrag

**Comment by alisonrag** [comment]
@sctnightcore
thanks for your contribution <3

**Comment by sctnightcore** [comment]
@alisonrag  ♥

**Comment by allanon** [comment]
Please clean up the commit message when merging. It can usually be simplified to a single line. Thanks!

**Comment by sctnightcore** [comment]
clean ? idk @allanon

**Comment by alisonrag** [comment]
@allanon  thanks for the tip
@sctnightcore  now you can delete the branch

**Comment by sctnightcore** [comment]
@alisonrag  ok sir

**Pull request merged**
