### PR TITLE
[fix] unable to talk to npc and can't drop target

### LINKED ISSUE #3451: OpenKore cannot teleport through an NPC if it is behind a wall
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: last

* **Server**: RMS Renewal Test Server

* **Bug Report / Feature Request**: OpenKore cannot teleport through an NPC if it is behind a wall

* **Summary**: we have the following portal-NPC:
```new_1-4 100 29 moc_ruins 155 44 0 c c c c c r0 c c c c r1 r0 r0 r0 r1 r1 c c r0 c r0 c r0 c r1 c c r0 c r1 c r1 c r1 c c r2 c r2 c r2 c r0 c r2 c r2 c r0 c r1 c c c c c c c c c c r0 c c c c c c c c```
OpenKore cannot calculate the path from **new_1-4** to **moc_ruins** openkore cannot calculate the path from location 1 to location 2 because the NPC is hiding behind the table:
image

Use this macro to check for defect:
```css
macro test {
	do c @warp new_1-4 100 19
	pause 3
	do debug 2
	do move moc_ruins 155 44
	do debug 0
}
```

console logs:
```css
macro test
Map Change: new_1-4.gat (100, 19)
Warped.
NPC Exists: Final Tester#nv1 (100, 29) (ID 110014979) - (0)
Config 'debug' set to 2 (was 0)
Saving control\config.txt...
AI: macro sitAuto sitting | 3
Calculating route to: Morocc Ruins(moc_ruins): 155, 44
You on route to: Morocc Ruins(moc_ruins): 155, 44
CalcMapRoute - initialized.
CalcMapRoute failed.
Cannot calculate a route from new_1-4 (100,19) to moc_ruins (155,44)
Config 'debug' set to 0 (was 2)
```

### LINKED ISSUE #3508: OpenKore cannot attack monsters outside of 200x200 coordinates
* **Openkore version git**: last
* **Server**: all servers (RMS for example)
* **Bug Report**
* **Summary**:

1. Start OpenKore, Enter the command: `c @warp new_1-3`
2. Close OpenKore
3. Start OpenKore again
4. Wait for the attack of any monster at location "new_1-3"
5. Enter the command: `c @warp prt_fild08 320 370`
6. Ttry attacking monsters outside 200x200 coordinates.
You get an error: "Unable to calculate a meetingPosition to target, dropping target"
```css
[2021.08.19 00:53:07.30] Received packet: 0857 Handler: actor_exists
[2021.08.19 00:53:07.32] Monster Exists: Poring (0)
[2021.08.19 00:53:07.33] Received packet: 0087 Handler: character_moves
[2021.08.19 00:53:07.34] You're moving from (314, 364) to (308, 363) - distance 6
[2021.08.19 00:53:07.34] Sent get player info: ID - 84 C7 91 06
[2021.08.19 00:53:07.35] AI: route | 1
[2021.08.19 00:53:07.38] You are now attacking Monster Poring (0)
[2021.08.19 00:53:07.39] Attack You (314 364) - target Monster Poring (0) (300 364) is too far from us to attack, distance is 14, attack maxDistance is 1
[2021.08.19 00:53:07.40] Unable to calculate a meetingPosition to target, dropping target
```
[console.txt](https://github.com/OpenKore/openkore/files/7010469/console.txt)

### PR DESCRIPTION
**Pull request by alisonrag**
this pull fixes #3451
this pull closes #3508

- [x] route to unreachable npc has conflict between closestwalkable and distfromgoal (map route)

### CODE REVIEW

**Comment by ya4ept** [comment]
I have problems calculating the route:
[console.txt](https://github.com/OpenKore/openkore/files/6927931/console.txt)
I will send you a video in private messages

**Comment by jhinovvo** [comment]
so this reguset is finish ?

**Comment by kou90258** [comment]
I'm testing some of the grammar and syntax of the Route and attack.
The following problems are currently found
1. Cross-wall attack.
2. Do not dodge and attack when encountering obstacles.
3 The path shifts but does not attack the nearest monster.
Please check if there is a problem with the attack syntax, thanks.

attack.pm
noMapRoute1

config.txt


test .mp4
https://drive.google.com/file/d/1RCGYIkGQyMopns26d4d6FwnfNmHEIqvK/view?usp=sharing

**Comment by alisonrag** [comment]
@ya4ept @sctnightcore lets move on with this pull.
the master branch still cant kill monster outside of coords and cant talk to npcs behind of wall

i created a new issue #3601 to keep our eyes on it

**Review by ya4ept — APPROVED** [review]
lets go

**Pull request merged**
