### PR TITLE
update iRO Renewal files

### PR DESCRIPTION
**Pull request by allanon**
- [ ] QA Review

This pull request was auto-generated by patch_iro.pl: https://gist.github.com/allanon/38620af49d250005acbf

### CODE REVIEW

**Comment by Rovejoe** [comment]
cant connect .... timeout

**Comment by unicornbaby** [comment]
@allanon lazy :p

**Comment by Nipodemos** [comment]
since is only tables update, we can merge this already?

**Comment by darkcosmo** [comment]
hello my friend how do i add the update in openkore and  or having difficulties

**Comment by Fadreus** [comment]
@darkcosmo #2145

**Pull request merged**
