### PR TITLE
update iRO Re:Start files

### PR DESCRIPTION
**Pull request by allanon**
- [ ] QA Review

### CODE REVIEW

**Comment by zPhotons** [comment]
Working thanks!

**Comment by arkhomr** [comment]
thank you very

**Comment by Nipodemos** [comment]
@Fadreus ping

**Comment by ZaskarAlpha** [comment]
need update again

**Comment by siefer214** [comment]
master allan can u update restart plsss thanks

**Comment by Nipodemos** [comment]
@ZaskarAlpha @siefer214 it is not necessary to ask for update, allanon already know :smile:

**Pull request merged**
