### PR TITLE
New hooks in FileParsers

### PR DESCRIPTION
**Pull request by Henrybk**
This is a request to add 2 new hooks in FileParsers::updatePortalLUT2
and FileParsers::updatePortalLUT. The purpose is to add support for
plugin related custom portal file updating.

### CODE REVIEW

**Comment by Henrybk** [comment]
Here is a plugin example of theses added hooks in use: http://pastebin.com/84X3rjny

They seem to work fine and were tested by me.

**Comment by itsrachelfish** [comment]
@snop222 Did you test these changes in game before merging them?

http://forums.openkore.com/viewtopic.php?f=6&t=211255&p=273514#p273514

**Comment by snop222** [comment]
Ah, Sorry !! Very Sorry !! I think I had a mistake !!
I make wrong merging on main project !!
Could it to be rollbacked ??

I just want to try the "Merge Pull Request".
I will be more careful, before I well understnad the GitHub works !!
Sorry, again !!

PS: But, only the one of these two is my merging, not two !!

**Comment by snop222** [comment]
Sorry !
I think, I do only one "Merge", but merging two "Pull Request" !!

**Comment by allanon** [comment]
I think it's fine to keep this merged. It creates two new hooks which nobody will have been using, and if nobody uses them, the old functionality is maintained.

**Pull request merged**
