### PR TITLE
Support NPC_MERSOL_TYPE

### PR DESCRIPTION
**Pull request by sctnightcore**
Issues : #1890
**OLD**
image

**FIXED**
image

```
merc status
-------------------------------- Slave Status --------------------------------
Name: Mimic                       HP: 6120/6120 (100.00%)
Type: Unknown                     SP:   187/187 (100.00%)
Job:
Level: 51                                   Kills: 0

Atk:  1047     Matk:      204     Hunger:        N/A
Hit:   276     Critical:   37     Faith:           0
Def:    10     Mdef:       40     Accessory:     N/A
Flee:  272     Aspd:      150     Summons:         0
Range:   2     Skill pt:  N/A     Contract End:  May 19 20:2

Statuses:  
------------------------------------------------------------------------------
```
**Test** 
- [x] pServer
- [x] iRO 
- [x] bRO
- [ ]  euRO

### CODE REVIEW

**Comment by alisonrag** [comment]
i have mercenary in bRO, i will test this pull today

**Comment by Fadreus** [comment]
I got the merc in iRO Renewal to test.. Will post result shortly..

**Comment by Nipodemos** [comment]
if test on bRO is working, don't forget please to remove those values in **mconf** of bRO too.

**Comment by Fadreus** [comment]
iRO working just fine..
👍👍👍

**Pull request merged**
