### PR TITLE
fix: update eventmacro item list conditions hooks

### LINKED ISSUE #1215: [eventMacro] Condition InInventory and InInventoryID not workiing correctly
###### Summary: 
InInventory condition is being true when it should not be
###### Affected configuration(s)/ file(s):
eventMacro.txt
InInventory.pm
###### Impact:
one macro that i use, is triggered when it's not supposed to trigger... making the bot go to the wrong place in the wrong time
###### Expected Behavior:
this macro be triggeres only once, when you dont have the item "Emblema do Grupo Valhalla" in inventory
###### Actual Behavior:
Even when this item is on inventory, it keeps triggering, should not do this
image
the item it is on inventory
###### Steps to Reproduce:
```
automacro EdenJoinMoveNpc {
	InInventory "Emblema do Grupo Valhalla" = 0
	InInventoryID 2414 = 0 #novice shoes
	exclusive 1
	BaseLevel >= 12
	ConfigKeyNot EdenMember yes
	NpcNotNear /Lenore|Lime/
	JobIDNot 0 #novice
	call {
		do move moc_para01 &rand(33,35) &rand(25,27) #good position Eden
	}
}

automacro EdenJoinTalkNpc {
	InInventory "Emblema do Grupo Valhalla" = 0
	ConfigKeyNot EdenMember yes
	exclusive 1
	NpcNear /Lenore|Lime/
	call {
		do talk $.NpcNearLastBinId
		do talk resp 1
		do talk resp 0
		do talk text lolol
		do talk text lolol
		do talk resp 4
		do iconf 6219 0 0 0 #Emblema do Grupo Valhalla
		do conf -f EdenMember yes
	}
}
```

also, this is what shows when you check status of the automacro:
```
eventMacro auto EdenJoinMoveNpc
[eventMacro] Printing information about automacro 'EdenJoinMoveNpc'.
Number of conditions: '6'
Has event type condition: 'no'
Number of true conditions: '5'
Number of false conditions: '1'
Is triggered: '0'
----  Parameters   ----
1 - priority: '0'
2 - overrideAI: '0'
3 - disabled: '0'
4 - time: '1506698347'
5 - delay: '0'
6 - orphan: 'terminate'
7 - macro_delay: '1'
8 - run-once: '0'
9 - timeout: '0'
10 - CheckOnAI: 'auto'
11 - repeat: '1'
12 - call: 'tempMacro43'
13 - exclusive: '1'
----  Conditions   ----
1 - InInventoryID: 'true'
2 - InInventoryID: 'true'
3 - BaseLevel: 'true'
4 - ConfigKeyNot: 'true'
5 - JobIDNot: 'true'
6 - NpcNotNear: 'false'
----  AI check states   ----
Check on AI off: 'no'
Check on AI manual: 'no'
Check on AI auto: 'yes'
----  End   ----
```
Notice that in this automacro the only false option is the npcnotNear, because it is already near the bot

and the other automacro:

```
eventMacro auto EdenJoinTalkNpc
[eventMacro] Printing information about automacro 'EdenJoinTalkNpc'.
Number of conditions: '3'
Has event type condition: 'no'
Number of true conditions: '3'
Number of false conditions: '0'
Is triggered: '1'
----  Parameters   ----
1 - priority: '0'
2 - overrideAI: '0'
3 - disabled: '0'
4 - time: '1506697422'
5 - delay: '0'
6 - orphan: 'terminate'
7 - macro_delay: '1'
8 - run-once: '0'
9 - timeout: '0'
10 - CheckOnAI: 'auto'
11 - repeat: '1'
12 - call: 'tempMacro44'
13 - exclusive: '1'
----  Conditions   ----
1 - InInventory: 'true'
2 - ConfigKeyNot: 'true'
3 - NpcNear: 'true'
----  AI check states   ----
Check on AI off: 'no'
Check on AI manual: 'no'
Check on AI auto: 'yes'
----  End   ----
```

@Henrybk you can look this when you have free time plz?

### PR DESCRIPTION
**Pull request by alisonrag**
add support to new item list
fixes #1215

partial fix 3488

### CODE REVIEW

**Comment by alisonrag** [comment]
eventMacro:
```
automacro Wood {
    InInventoryID 909 >= 1
    call wood
}

macro wood {
   log ok
}
```
Result picking from floor:
image

**Comment by alisonrag** [comment]
Result checking when login:
image

**Comment by alisonrag** [comment]
after teleport:
image

**Comment by alisonrag** [comment]
after plugin reload:
image

**Comment by alisonrag** [comment]
after reload eventmacro file:
image

**Comment by ya4ept** [comment]
1) I think not all servers can send "item_list_end" packet
2) I don't see the "item_list_end" hook

**Comment by ya4ept** [comment]
how did it all work? ))))

**Comment by alisonrag** [comment]
> 1. I think not all servers can send "item_list_end" packet
> 2. I don't see the "item_list_end" hook

1.1 -  this update keep the support for old packets
2.1 - updated the hook of item_list_end

just removing map_change hook work fine, the hook was blocking the InInventory and related others

**Comment by alisonrag** [comment]
> how did it all work? ))))
`$self->{is_on_stand_by} = 1;`

was blocking the check, i was talking with Henry in discord and he gave me some tips

**Comment by ya4ept** [comment]
> 2.1 - updated the hook of item_list_end
can you check the macro again?

**Comment by alisonrag** [comment]
> > 2.1 - updated the hook of item_list_end
> 
> can you check the macro again?

yep, in some minutes

**Comment by alisonrag** [comment]
after update:

login with item in inventory:
image

after teleport:
image

login without item in inventory and get from monster:
image

after reload eventMacro:
image

**Comment by alisonrag** [comment]
image

**Comment by alisonrag** [comment]
other test:
image

**Review by ya4ept — APPROVED** [review]

**Pull request merged**
