### PR TITLE
re:start old moc_fild

### PR DESCRIPTION
**Pull request by sctnightcore**
Fix in tables > iRO > RE:RESTART

### CODE REVIEW

**Comment by kaliwanagan** [comment]
@xTriumph looking to get your second opinion on this :) (coz i'm not able to connect to iRO restart at all so I'm not able to check myself)

**Comment by xTriumph** [comment]
@kaliwanagan me too, they've probably blocked my IP range, and i get DC'ed when using proxy or VPN because of the lag. Will test it when i connect.

**Comment by xTriumph** [comment]
Gonna test it now, the servers are back online.

**Comment by sctnightcore** [comment]
If there is free time to come back to fix it. @xTriumph

**Comment by kipme** [comment]
Any updates on this guys? Thanks for all the work you do! @sctnightcore @kaliwanagan @xTriumph

**Comment by sctnightcore** [comment]
I still do not have time @kipme

**Comment by alisonrag** [comment]
what about the portals? will you add more? can i merge the actual portals?

**Comment by sctnightcore** [comment]
It's not perfect yet. I still do not have time to edit it. @alisonrag

**Comment by sctnightcore** [comment]
NEED TEST  
i do not have time to test  T-T

**Comment by sctnightcore** [comment]
NEED TEST  
i do not have time to test  T-T

**Comment by sctnightcore** [comment]
`portalRecord 2`

**Comment by alisonrag** [comment]
@allanon  @Henrybk can anyone of you two test this? i not play in iro server

**Comment by kaliwanagan** [comment]
This is probably already outdated. They keep on moving the portals around.

A better solution is to do just like what @sctnightcore suggested: record the portals and every now and then restart kore so it will compile the new portals detected.

@Henrybk also already added a portal fuzzing routine that guesses where the new portals are. I've been testing the portals for the good part of the day and it does reroute around.

**Comment by kaliwanagan** [comment]
From what I can tell they moved the portals back to their original positions. Can anyone confirm if this PR is still valid?

**Comment by sctnightcore** [comment]
someone confirm pls ? haha

**Comment by sctnightcore** [comment]
#1089

**Comment by haltamimi** [comment]
can somebody help me with this? izlude 197 205 izlu2dun 107 50 150 c r0 portal going to Undersea tunnel. But what happens is that my bot is going to the 3oclock of Izlude map rather than 2oclock which is where the sailor is. Thanks!!!

**Pull request closed without merging**
