### PR TITLE
Renew "\\field\iz_int.fld2.gz" file

### PR DESCRIPTION
**Pull request by andy90498**
Because of "iz_int.fld2.gz" file was too old to use, so I extracted "iz_int.gat" and "iz_int.rsw" from official data.grf to execute script: "fields\tools\gat_to_fld2.pl" and renew file

These files  """""only""" be used in the "twRO-recvpacket" version

thank you.

### CODE REVIEW

**Comment by andy90498** [comment]
Because of 5 files was too old to use
so I extract *.rsw and *.gat from official data.Grf to run "\\fields\tools\gat_to_fld2.pl"

5 files is
\\fields\izlude.fld2.gz
\\fields\izlude_a.fld2.gz
\\fields\izlude_b.fld2.gz
\\fields\izlude_c.fld2.gz
\\fields\izlude_d.fld2.gz

**Comment by andy90498** [comment]
I extract *.gat and *.rsw files about  "iz_ac01" and "iz_ac02" from official data.grf and run the script "\\fields\tools\gat_to_fld2.pl"

10 files is
\\fields\ iz_ac01.fld2.gz
\\fields\ iz_ac01_a.fld2.gz
\\fields\ iz_ac01_b.fld2.gz
\\fields\ iz_ac01_c.fld2.gz
\\fields\ iz_ac01_d.fld2.gz
\\fields\ iz_ac02.fld2.gz
\\fields\ iz_ac02_a.fld2.gz
\\fields\ iz_ac02_b.fld2.gz
\\fields\ iz_ac02_c.fld2.gz
\\fields\ iz_ac02_d.fld2.gz

**Comment by ya4ept** [comment]
I think that we will decide this here: #3481

**Comment by Que999** [comment]
sir i am new here.. can any1 help me to get this server information **https://trinityv2.club/**

**Pull request closed without merging**
