### PR TITLE
[2016-12-01] Connection Files for bRO

### PR DESCRIPTION
**Pull request by lututui**
http://openkorebrasil.org/index.php?/topic/1929-atualiza%C3%A7%C3%A3o-01-12-2016/

### CODE REVIEW

**Comment by flacrasec** [comment]
The poseidon is at the same situation from last week? thx again for the update lututui ^^

**Comment by itsrachelfish** [comment]
@lututui Can you explain what happened with poseidon last week?

I can't read that Openkore Brasil forum page without registering. :(

**Comment by flacrasec** [comment]
since the last update the ragexe.exe of bRO became incompatible with the poseidon the servertype.txt does not work at all, so the solution to use poseidon was to make a copy from the last ragexe.exe that was compatible and keep using it that is how we are using until now, but for any more details @lututui can help more than me.

**Comment by flacrasec** [comment]
ah @itsrachelfish but this is the weekly update, and can be merged, it is working fine!

**Comment by lututui** [comment]
@itsrachelfish basically, bRO's Gameguard updated and any client older than bRO_2016-11-08aRagexe does not answer the query packet. That might be caused by a new answer packet we're not expecting (best scenario) or the packet structure changed completely.

Actually, bRO_2016-11-08aRagexe (or any 2016 client for that matter) works perfectly, and anyone can get their hands on the Ragexe.exe from Lu!G (http://openkorebrasil.org/index.php?/topic/1857-obtendo-o-ragexeexe-do-poseidon-2016-11-08a/).

The best solution would be helping @AlexandreBR3N with emulating GameGuard (#330). If just the answer packet has changed, it's something easy to fix, and I'll be looking into it. Otherwise, people can stick with bRO_2016-11-08aRagexe just fine, at least for now.

At last, this pull request just updates the old boring packets for bRO, nothing to do with Poseidon.

**Comment by AlexandreBR3N** [comment]
[quote]
No packet has actually changed. The problem is that the cryptKey for the packet '09D0' has something extra. I'll open an issue just for this later.
[/quote]

I was seriously thinking in one new param to identify the bot ! :D

**Comment by AlexandreBR3N** [comment]
I was seriously thinking in one new param to identify the bot ! :D 

dwIndex, dwValue1, dwValue2, dwValue3, poseidonIdentification

**Pull request merged**
