### PR TITLE
Initial release for Skill Exchange Item packets.

### LINKED ISSUE #65: Packet handler for Change Material-like skill
Well, if this is solved already, maybe this issue can be ignored.

I'm currently using SVN for r9031 (updated on Feb 28th, 2016)  and the packet handler `0x07E3` and `0x07E4` are still unknown. (Silly me, I just knew that OpenKore has git repo!)
Then, I tried to solve it by this https://gist.github.com/cydh/e1473eb2a242d221e80a42dce4ed7093
By that gist, there is new command to do 'change material', is **cm**.

If it's approved, I can make a new PR later.

### PR DESCRIPTION
**Pull request by cydh**
- [ ] Code review
- [x] QA testing on idRO
- [ ] QA testing on iRO
- Used for Change Material (GN_CHANGEMATERIAL) and Four Spirits Analysis (SO_EL_ANALYSIS)
- Received packet: `'07E3' => ['skill_exchange_item', 'V2', [qw(type val)]], # 8`
- Send packet: `'07E4' => ['item_list_window_selected', 'v V V a*', [qw(len type act itemInfo)]],`
- Global var: `$skillExchangeItem`
- New commands:
  - `cm <itemIndex> <amount>[,<itemIndex> <amount>]`: Used after Change Material casted
  - `analysis <itemIndex> <amount>[,<itemIndex> <amount>]`: Used after Four Spirits Analysis
- Fixed #65

Signed-off-by: Cydh Ramdh cydh@pservero.com

### CODE REVIEW

**Comment by cydh** [comment]
2 my friends use this for exchanging Tsurugi [1] to Steel and Skel-Bone & Orcish Voucher to Alchol. Let's see if they want to visit.

**Comment by Ax3l210817** [comment]
@cydh @itsrachelfish Change Material work for Genetic in idRO 
cm1
cm2
cm3

**Comment by cydh** [comment]
I'll rebase this

**Comment by kaliwanagan** [comment]
@cydh I think you'll need to resolve a few more conflicts.

Then I think we're good to merge :)

**Pull request merged**
