### PR TITLE
[2016-08-02] Connection files for bRO

### PR DESCRIPTION
**Pull request by lututui**
Before: http://i.imgur.com/N7gNiI3.png
After: http://i.imgur.com/hzRfvUN.png

### CODE REVIEW

**Comment by itsrachelfish** [comment]
@emsjustin you play on bRO right? Can you test this? :sweat_smile:

**Comment by flacrasec** [comment]
This is working perfectly I´am using lututui work and following it a quite few months and it is always perfect!

**Comment by itsrachelfish** [comment]
Thank you @flacrasec :+1:

**Comment by xflamerx** [comment]
Oyeah


2016-08-04 14:47 GMT-03:00 Rachel Fish <notifications@github.com>:

**Pull request merged**
