### PR TITLE
Fix OpenKore/openkore#1810

### PR DESCRIPTION
**Pull request by lututui**
What needs to be tested:

# Commands 
 - homun s
 - merc s

# Config
 - homunculus_hp
 - homunculus_sp
 - mercenary_hp
 - mercenary_sp

### CODE REVIEW

**Comment by lututui** [comment]
@lucasca73 @nipodemos

**Comment by exelion99** [comment]
hi is there a bot on phRO Valhalla start of a new journey already? here is the site http://www.playvalhalla.ph/

**Comment by Nipodemos** [comment]
why this was not approved? :thinking:

**Comment by lututui** [comment]
@Nipodemos bc I need someone to test this. I might have missed something

**Comment by lututui** [comment]
#2108

**Pull request closed without merging**
