### PR TITLE
ServerType0.pm,Sakexe_0.pm: Unpack items_stackable type7

### PR DESCRIPTION
**Pull request by c4c1n6kr3m1**
Unpack items_stackable type7

### CODE REVIEW

**Comment by sctnightcore** [comment]
server?

**Comment by c4c1n6kr3m1** [comment]
the old one is absolutely nonsense
the length is not 34 but 40
and broken ?
and upgrade ?
i test this on Private Server

**Comment by alisonrag** [comment]
```
[Jan 06 14:25:37 2020.25] ================================================
<< Received packet:      0B09 - Item List Stackable [175 bytes]   Jan 06 14:25:37 2020
  0>  09 0B AF 00 00 04 00 EC    57 00 00 02 01 00 00 00    ........W.......
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 01 0C    00 7F 18 00 00 03 01 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  00 00 00 00 00 00 00 00    01 0D 00 7E 18 00 00 03    ...........~....
 80>  01 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 96>  00 00 00 00 00 00 00 00    00 00 01 0E 00 24 30 00    .............$0.
112>  00 02 24 00 00 00 00 00    00 00 00 00 00 00 00 00    ..$.............
128>  00 00 00 00 00 00 00 00    00 00 00 00 01 0F 00 23    ...............#
144>  30 00 00 02 04 00 00 00    00 00 00 00 00 00 00 00    0...............
160>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 01       ...............
```
my char have 5 itens
based on this:
size: 175
packet ID: 2
length: 2
type: 1
175 - 2 - 2 - 1 = 170
170 / 5 = 34

so right size is 34

**Comment by alisonrag** [comment]
based o hercules struct:
```
struct NORMALITEM_INFO {
	int16 index;
#if PACKETVER_MAIN_NUM >= 20181121 || PACKETVER_RE_NUM >= 20180704 || PACKETVER_ZERO_NUM >= 20181114
	uint32 ITID;
#else
	uint16 ITID;
#endif
	uint8 type;
#if PACKETVER < 20120925
	uint8 IsIdentified;
#endif
	int16 count;
#if PACKETVER >= 20120925
	uint32 WearState;
#else
	uint16 WearState;
#endif
#if PACKETVER >= 5
	struct EQUIPSLOTINFO slot;
#endif
#if PACKETVER >= 20080102
	int32 HireExpireDate;
#endif
#if PACKETVER >= 20120925
	struct {
		uint8 IsIdentified : 1;
		uint8 PlaceETCTab : 1;
		uint8 SpareBits : 6;
	} Flag;
#endif
}
```

your pull is valid:
```
types => 'a2 V C v V a16 l C',
keys => [qw(ID nameID type amount type_equip cards expire identified)],
```

whe need work better in identified, cause this is a flag to 
```
uint8 IsIdentified : 1;
uint8 PlaceETCTab : 1;
uint8 SpareBits : 6;
```

**Comment by c4c1n6kr3m1** [comment]
i don't know how to read that hercules data
:D
but i guess it's in bits , not bytes :D

**Pull request merged**
