### PR TITLE
add support for new actor packets

### PR DESCRIPTION
**Pull request by allanon**
- [x] Fix private messages
- [x] QA Review (does it work?)

### CODE REVIEW

**Comment by itsrachelfish** [comment]
I am testing this now and saw the following strange messages:

```
You are no longer: UNKNOWN_STATUS_994
You are no longer: UNKNOWN_STATUS_993
```

On the plus side, ragnastats is updating again :smile: http://ragnastats.com/active

**Comment by bradley02** [comment]
so far it seems perfectly.

**Comment by gospelkiru** [comment]
ohhh. it works well...

**Comment by Henrybk** [comment]
@itsrachelfish As with #275 probably  '0984' => 'actor_status_active' was also changed, you may want to test the change I made there

**Comment by gospelkiru** [comment]
and then this happen.... when i use potion in inventory.

Can't call method "usable" on an undefined value at src/Interface/Wx/List/ItemList/Inventory.pm line 177

**Comment by allanon** [comment]
@gospelkiru I can't (easily) run Wx to test, but using a potion doesn't appear to cause problems for me.

**Comment by gospelkiru** [comment]
hahaha. well yeah. its not a prob for me either . ^^ as long as it attk thats ok... :)

**Comment by Jyuchard** [comment]
Works ! I'm going to report about private message but you already updated it the moment i was going to report it. Thanks !

**Comment by bentot13** [comment]
why for me there is an error like this ?

A detailed error report has been saved to errors.txt. Before posting a bug
report, please try out the SVN version first. If you are already using the SVN
version, search the forums first to see if your problem had already been solved,
or has already been reported. If you truly believe you have encountered a bug in
the program, please include the contents of the errors.txt in your bug report,
or we may not be able to help you!

**Comment by dacz2016** [comment]
why my kore attack after 5 attack then its closed

**Comment by butasnacondom** [comment]
hope this page is still open @allanon how can i open the ".pm" file?

**Pull request merged**
