### PR TITLE
Prevent loop when trying to open storage...

### PR DESCRIPTION
**Pull request by lututui**
and failing because we don't have enough zeny

Workaround #2466

### CODE REVIEW

**Comment by cydh** [comment]
Can also add a config maybe to ignore zeny check as long as player has `Storage Free Ticket` (7059), a config maybe.. well or maybe on separated PR, also for Zeny (7060) on 'normal' warp (not airport), rent cart too (7061)

**Comment by c4c1n6kr3m1** [comment]
- all job has NV_BASIC not only novice and high novice 
- doram has different basic skill

**Comment by c4c1n6kr3m1** [comment]
-    doram has different basic skill
-    other job has NV_BASIC not only novice and high novice

**Comment by lututui** [comment]
@cydh Added the storage ticket. 

About the warp thing, I'm pretty sure that already is taken into account: kore won't pick a route if we don't have enough budget to complete it.

About rent cart, is that event a problem? I don't think there's an "auto rent cart" feature

**Comment by Nipodemos** [comment]
@lututui https://www.ragnaplace.com/bRO/item/7061/Vale-Carrinho

as he said, this part should be on another PR

**Pull request merged**
