### PR TITLE
Add client for RagexeRE_2013_12_23 to fix decryption of 'area_spell' packets

### PR DESCRIPTION
**Pull request by kliewkliew**

### CODE REVIEW

**Comment by itsrachelfish** [comment]
@kliewkliew Cool! :+1: 

What server is this for / how were these files generated?

**Comment by kliewkliew** [comment]
I tested these on my own server using the Hercules server emulator. I made these by matching known values (ie. spellcast x-location) to values in the Wireshark hex stream. Then I constructed the decode string by using the offsets of the hex values.

**Comment by ya4ept** [comment]
see:..\Receive\ServerType0.pm:
> '09CA' => ['area_spell_multiple3', 'v a*', [qw(len spellInfo)]], # -1

**Comment by kliewkliew** [comment]
It looks like I was working on an old version. It seems to have been fixed in https://github.com/OpenKore/openkore/commit/8ca404f4e73909f2dd2ab91fa33b62ed9c2935cf

**Comment by Slipxxliose** [comment]
It will only works inside official. private severs will warn about it.

**Pull request closed without merging**
