### PR TITLE
Re:Start Fixed ayo_fild02 access

### PR DESCRIPTION
**Pull request by Onihen**

### CODE REVIEW

**Comment by kaliwanagan** [comment]
Can anyone else verify this?

**Comment by sctnightcore** [comment]
wait ..

**Comment by xTriumph** [comment]
This fixes the wrong use of the tables/portals.txt instead of the Restart/official/portals.txt.
But you need to change the code from iRO/Restart;iRO to iRO/Restart/official;iRO
I tested it with the Link Christmas NPC and it works.
Im looking now if it fixes the ayo_fild02 acess.

**Comment by kaliwanagan** [comment]
will be merged via #776 

thanks @Onihen !!

**Comment by Onihen** [comment]
My bad. I moved portals.txt out of the official folder because I thought that folder was for unmodified tables extracted from the client (based on what was discussed here #25)

**Pull request closed without merging**
