### PR TITLE
iRO Restart update

### PR DESCRIPTION
**Pull request by allanon**

### CODE REVIEW

**Comment by luanfx** [comment]
**Nice**

**Comment by don00000** [comment]
[dist=unknown] Unknown #50490: *Grumble*
Failed to take Resin (0) from (94, 234) to (95, 234)
Disconnected from Map Server, connecting to Account Server in 40 seconds...
Connecting to Account Server...
Connecting (128.241.92.133:6800)... connected
Disconnecting (128.241.92.133:6800)...disconnected
The server has denied your connection for unknown reason (18).

after like 2-3mins my bot is getting disconnected

**Comment by j3553h** [comment]
Disconnected from Map Server, connecting to Account Server in 36 seconds...
Connecting to Account Server...
Connecting (128.241.92.133:6800)... connected
Disconnecting (128.241.92.133:6800)...disconnected
The server has denied your connection for unknown reason (18).
Timeout on Account Server, reconnecting. Wait 46 seconds...
Connecting to Account Server...
[reconnect] Login retry number 2, setting reconnect timeout to 65 seconds.
Connecting (128.241.92.133:6800)... connected
Disconnecting (128.241.92.133:6800)...disconnected
Error: The server still recognizes your last connection

**Comment by luanfx** [comment]
I get DC when I sent rodex (mail).

**Comment by byh519** [comment]
after first d/c I logged in manually to check; it will say it has detected third party hacking tool please dont for fairness etc,.

**Comment by lucasbradok** [comment]
[Sep 27 20:54:45 2017.69] Disconnected from Map Server, connecting to Account Server in 110 seconds...
[Sep 27 20:55:46 2017.84] Relogging in 1 seconds...
[Sep 27 20:55:47 2017.90] Connecting to Account Server...
[Sep 27 20:55:47 2017.91] [randtimeout] Reconnect timeout has been change to 66 second.
[Sep 27 20:55:47 2017.92] Connecting (128.241.92.133:6800)... [Sep 27 20:55:48 2017.15] connected
[Sep 27 20:55:48 2017.46] Disconnecting (128.241.92.133:6800)...[Sep 27 20:55:48 2017.47] disconnected
[Sep 27 20:55:48 2017.47] The server has denied your connection for unknown reason (18).
got a 30 min dc ban

**Comment by kaguluhan** [comment]
Hello master Alladon, i am looking at the problem of getting DC when picking up items. Can you please look into it. Thank you so much for your hard work. :+1:

**Comment by charlesyves** [comment]
Master Alladon, i have same problem here. when pick up an item i get DC. thank you for helping.

**Comment by naresuta** [comment]
hello master Allanon, me too got same problem, when pick up an item getting DC, thank you so much for your hard work, keep spirit.👍👍

**Comment by jonelle1990** [comment]
always dc after picking the item
any updates on this ?

**Comment by browniezzz** [comment]
same here too master allanon. keep failing in getting item then disconnected from the server.

**Pull request merged**
