### PR TITLE
update iRO Renewal files

### PR DESCRIPTION
**Pull request by allanon**
- [ ] QA Review

This pull request was auto-generated by patch_iro.pl: https://gist.github.com/allanon/38620af49d250005acbf

### CODE REVIEW

**Comment by ZaskarAlpha** [comment]
can u update restart too pls..

**Comment by dezenhando** [comment]
Is it updated?because i just downloaded it and it´s not working, not connecting, can someone explain it to me?

**Comment by dezenhando** [comment]
> where i locate this file ?

i am trying to find it to, but through the IRO Update, you can download it, as i just did, but it´s not working

**Comment by zPhotons** [comment]
Working thanks!

**Comment by Ace071418** [comment]
> 
> 
> Working thanks!

how did you make it work?

**Comment by Ace071418** [comment]
Still not working for me.. can someone point me to the right direction please :)

**Comment by Fadreus** [comment]
@Ace071418  W-A-I-T.

**Comment by gudoh** [comment]
I'm not not confident with results but anyone willing to test - https://gist.github.com/gudoh/d73f6695cef3467cf23f75fcd74c6963

At least it seems to work, for now.

**Comment by AusEPower** [comment]
Hi, I have tried to add all the renewal changes to the txt files done by allanon, also updated gudoh txt file and downloaded the new openkore which have the iro renewal update. But it still showing connecting, can anyone please enlighten me. Thank you very much for the help.
image

**Comment by bunnyy00** [comment]
> I'm not confident with results but anyone willing to test - https://gist.github.com/gudoh/d73f6695cef3467cf23f75fcd74c6963
> 
> At least it seems to work, for now.

it works for me too

**Comment by Nipodemos** [comment]
hey guys, there is a command that you can use if you want
github itself provides this command:

- first you need to download openkore, but from the command line.
- to do this, open a git bash on any folder you want, and clone openkore with this command:  
```git clone https://github.com/OpenKore/openkore.git```
- Close the git bash
- This will create a new openkore folder
- enter this folder and open another Git Bash
- type the following command: 
```git checkout -b iro_update origin/iro_update```

that way, you can test the code of allanon, without have to copy and paste everything
If you guys test it and say here that it is working, some developer will approve and make this code go to the official openkore (it is not here yet)

**Comment by kvnprsts** [comment]
can someone like post a guide to update the files? i want to try it myself to update next time

thanks

**Comment by AusEPower** [comment]
> 
> 
> hey guys, there is a command that you can use if you want
> github itself provides this command:
> 
>     * first you need to download openkore, but from the command line.
> 
>     * to do this, open a git bash on any folder you want, and clone openkore with this command:
>       `git clone https://github.com/OpenKore/openkore.git`
> 
>     * Close the git bash
> 
>     * This will create a new openkore folder
> 
>     * enter this folder and open another Git Bash
> 
>     * type the following command:
>       `git checkout -b iro_update origin/iro_update`
> 
> 
> that way, you can test the code of allanon, without have to copy and paste everything
> If you guys test it and say here that it is working, some developer will approve and make this code go to the official openkore (it is not here yet)

I can download the openkore by following your method.
But I still can't get the bot running, before the update I can still use. Is there anything i need to configure for my computer?

**Comment by bunnyy00** [comment]
@AusEPower I just copy paste >_<

**Comment by sparkker** [comment]
> I'm not confident with results but anyone willing to test - https://gist.github.com/gudoh/d73f6695cef3467cf23f75fcd74c6963
> 
> At least it seems to work, for now.

its not work for me :(

**Comment by kira221** [comment]
> > I'm not confident with results but anyone willing to test - https://gist.github.com/gudoh/d73f6695cef3467cf23f75fcd74c6963
> > At least it seems to work, for now.
> 
> its not work for me :(

why?

**Comment by sparkker** [comment]
> > > I'm not confident with results but anyone willing to test - https://gist.github.com/gudoh/d73f6695cef3467cf23f75fcd74c6963
> > > At least it seems to work, for now.
> > 
> > 
> > its not work for me :(
> 
> why?

idk why. I  copy ur file to my \tables\iRO\Renewal but cant run :(

**Comment by sparkker** [comment]
capture

**Comment by gudoh** [comment]
> > > its not work for me :(
> > 
> > why?
> 
> idk why. I copy this file to my \tables\iRO\Renewal but cant run :(

"File" or "files"? There is four files there, and one of them goes to different directory.

**Comment by Zexeta** [comment]
Did they change something that this seems to be taking alot longer this week? Also any chance you can update it for restart as well?

**Comment by kiko3290** [comment]
Anyone made it work in restart?

**Comment by gudoh** [comment]
@Zexeta
I'm pretty new to this stuff so take it take with a grain of salt (that's why updates are really questionable, I don't know technical details well enough to be qualified for that).
They added new packets for recvpackets. It seems it doesn't happen that often, maybe once in a few months. The script which can be used to update files after normal maintenance - extract_recvpackets.pl - it doesn't handle the situation with new packets. I had to compare old and new recvpackets, find which packets were new ones, added them to the same positions to old recvpackets and rerun script. The result is quite functional to my luck.

@kiko3290
I could give it a try but no promises. In that case I need restart version of Ragexe.exe (I deleted restart files some time ago because I don't need them) so I need someone to upload it for me.

**Comment by AusEPower** [comment]
> 
> 
> > > > > its not work for me :(
> > > > 
> > > > 
> > > > why?
> > > 
> > > 
> > > idk why. I copy this file to my \tables\iRO\Renewal but cant run :(
> > 
> > 
> > "File" or "files"? There is four files there, and one of them goes to different directory.
> 
> Big thx now work :)

I also have the same problem, it just keep saying "closing connection to character server". 
I have copied the "recvpackets" from @gudoh to my renewal folder and also updated the txt files from @allanon . I don't know what more I can do >_< Seems like I need a guide for dummies 102.
image

**Comment by Fadreus** [comment]
@itsrachelfish Worked fine with me. #2414 is all the files from him.

**Comment by itsrachelfish** [comment]
@Fadreus My mistake, I only updated the recvpackets.txt file from @gudoh's gist, thank you for creating PR #2414

**Comment by gudoh** [comment]
@poaepoae 

Seems to work (Re:Start) - https://gist.github.com/gudoh/07cbfc14aabaeff9a0c91f7542dfc98a

**Comment by Fadreus** [comment]
@gudoh Make PR for it if it work.

**Comment by bunnyy00** [comment]
it works

**Pull request merged**
