### PR TITLE
add --command command line option

### PR DESCRIPTION
**Pull request by allanon**
- [x] Code review
- [x] QA testing

Add `--command=...` command line option. Useful for completely automated processes like:

```
openkore.pl --command="macro do_something_and_quit"
```

### CODE REVIEW

**Comment by Henrybk** [comment]
Shouldn't this be done with CmdOnLogin plugin? Maybe we could rework it to use commands on more situations during login, like on character screen, on account login, on files load, etc.

**Comment by allanon** [comment]
Hm. For reference, you're talking about: https://github.com/OpenKore/openkore/blob/master/plugins/needs-review/cmdOnLogin/trunk/cmdOnLogin.pl

That plugin requires a config option, and I want to be able to do it via command line. But now that plugins can inject command line options, it should be possible to enhance the plugin.

**Comment by itsrachelfish** [comment]
@allanon Can you give an example of what you're using this for? I'm curious what macro you need to run and then quit the game...

**Comment by allanon** [comment]
Two of them:
1. gramps_and_quit
2. daily_quen_and_quit

The first gets the current Gramps TI quest for the character's level range. It does not attempt to do the quest. This is useful because characters can go into TI as long as they have the current quest, even if they're out of the level range. So I can collect all the quests and go in when I feel like it.

The second runs the Daily Quen quest, which can net some free Enriched Elunium/Oridecon. Useful stuff.

**Comment by itsrachelfish** [comment]
Tested and working. :)

Are there any drawbacks to having this functionality in a plugin like @Henrybk was talking about?

**Pull request merged**
