### PR TITLE
UPDATE SERVERTYPE 2016

### PR DESCRIPTION
**Pull request by sctnightcore**
Thank you : @alisonrag  @moneyisgod   For @Henrybk  will come help.
I will only do this if I have a client.

**I open the server. With my own computer, but can not connect map.
If someone else open the server. It can connect to maps.**

**Status**
```
FIX 20151104a : WORK!
RagexeRE_2016_02_03a : WORK!
2016-12-28aRagexeRE : WORK!


```
BUG  :

### CODE REVIEW

**Comment by sctnightcore** [comment]
@alisonrag  come here

**Comment by sctnightcore** [comment]
If not again I will not do it WTF

**Comment by sctnightcore** [comment]
#1031

**Comment by alisonrag** [comment]
why criptkeys are not defined?

if everyone in rathena/hercules use the same hexes as base, you can define with the values get from peek-master

**Comment by sctnightcore** [comment]
sendCryptKeys 0x3E1411AF,0x7CFA1BDE ,0x6C744497 
I think this would be easier.

**Comment by alisonrag** [comment]
thanks for implement this, now with commented line we need just uncomment if criptkeys are enabled

**Comment by sctnightcore** [comment]
@alisonrag  ty sir

**Comment by sctnightcore** [comment]
image
image
**I added it to it Error I do not know what** @alisonrag  @moneyisgod 


sub achievement_list {

**Comment by alisonrag** [comment]
`use Globals;`

**Comment by sctnightcore** [comment]
```
cannot login to map , I'm looking for the cause of it. And it's possible that Sakexe_0 is too old. 
```
image

**Comment by alisonrag** [comment]
are you using the latest clean version, @Henrybk updated the waitforcharacter in char server
i was with same problem in another server, just redownloaded and try again

**Comment by sctnightcore** [comment]
If this point is fixed. I will update sT2017 @alisonrag  ty sir

**Comment by moneyisgod** [comment]
Which server is u testing?

**Comment by moneyisgod** [comment]
Erase 099D from 2015 because it's defined in 2013 03 20.

**Comment by sctnightcore** [comment]
not work again @moneyisgod

**Comment by sctnightcore** [comment]
@Henrybk  you can updated the waitforcharacter in char server ?

**Comment by sctnightcore** [comment]
complete ! 
@alisonrag  @moneyisgod 
reviews and Merging 
I will be updating the 2017 servertype.

**Comment by alisonrag** [comment]
@allanon @lututui 
any of you want to comment something?
to me this PR is ok.

**Comment by allanon** [comment]
I have no way to test this, but the code looks okay. I'm fine with merging.

**Pull request merged**
