### PR TITLE
[fix] add check to skill lvl in skill use

### LINKED ISSUE #3197: OpenKore does not check the skill level before sending it to the server
* **Openkore version git**: last
* **Server**: any
* **Bug Report / Feature Request**:

Use the config:
```
useSelf_skill First Aid {
	lvl 100
	hp < 100%
	sp > 3
	timeout 30
	disabled 0
	manualAI
}
```
100 (0x0064) skill level is sent to the server:
```
>> Sent packet: 0438   [10 bytes]   Jun 22 17:52:31 2020
  0>  38 04 64 00 8E 00 02 AC    02 00                      8.d.......
```
* **Summary**:
the server accepts such packets without problems, but we should not send them, some security systems can take advantage of this

### PR DESCRIPTION
**Pull request by alisonrag**
this fixes #3197

### CODE REVIEW

**Comment by alisonrag** [comment]
Commands:
image

CoreLogic use_skill:
image

**Comment by ya4ept** [comment]
Stop, don't merge please

**Comment by alisonrag** [comment]
> Stop, don't merge please

u need to approve to i merge it hahah, is up to u i will let this open, if u want to make another pull based in this, or check this before

**Comment by ya4ept** [comment]
I think the "sl" command should be causing an error, not a warning.

**Comment by alisonrag** [comment]
> 1. I think the "ss Heal 100" command should be causing an error, not a warning.
> 2. We should not automatically substitute a level if it is already registered in our config! The level should be set automatically only if it is not specified in the config

so corelogic throw error and disable? and commands error?

**Comment by ya4ept** [comment]
1. console command `ss Heal 100` should throw an error. We must force the user to enter the correct skill number. If the user wants to use the maximum level, then let him not indicate it: `ss Heal`
изображение
2. If the user specified a very high level of skill in the config, then we simply ignore this block:
```
useSelf_skill Heal {
	lvl 100
	sp > 85
	timeout 3
	disabled 0
}
```
The error message can be seen in debug mode:
изображение
If the user wants to use the maximum skill level, then he should not specify it in the config:
```
useSelf_skill Heal {
	sp > 85
	timeout 3
	disabled 0
}
```
изображение

**Comment by ya4ept** [comment]
You should check:
- [ ] console command
- [ ] attackSkillSlot
- [ ] attackComboSlot
- [ ] useSelf_skill
- [ ] useSelf_skill_smartHeal 1
- [ ] partySkill
- [ ] monsterSkill

**Comment by ya4ept** [comment]
I did all the checks

**Comment by Nipodemos** [comment]
it's very nice that you managed to test everything!

**Pull request merged**
