### PR TITLE
Updating packet tables and keys for iRO Renewal

### PR DESCRIPTION
**Pull request by delawr0190**
20180726 maintenance.

### CODE REVIEW

**Comment by Nipodemos** [comment]
anyone can test this please?

**Comment by unicornbaby** [comment]
It's work also

**Comment by delawr0190** [comment]
Thank you for reporting back, @lobocop and @unicornbaby

**Comment by Mooyor** [comment]
Good job.

**Comment by AlexandreVitorino** [comment]
since ro classic is working, edit the openkore readme as delaw as maintaner and change it to bottable .

**Pull request merged**
