### PR TITLE
Fix allow ticket

### PR DESCRIPTION
**Pull request by Henrybk**
For as long as I can remember kore can't handle properly Free Ticket for Kafra Transportation, these days are over because after days I finally found the bug that made it not work.

### CODE REVIEW

**Comment by allanon** [comment]
Good job tracking this down!

**Comment by flacrasec** [comment]
Thank you Henry for the good job! =)

**Comment by and2and2** [comment]
Afaik, iro give restriction for kafra ticket
Only first class or low level , cmiiw
Already accommodate?

**Comment by Henrybk** [comment]
@and2and2 Well, I guess there's nothing we can do about it other than remove allow_ticket from iro portals.txt. Or maybe add a configuration to xConf to conf portals configuration and then redo portals_los.

**Pull request merged**
