### PR TITLE
changes at bRO portals.txt

### PR DESCRIPTION
**Pull request by flacrasec**
Disabled old gef_fild and updated all Eden Officers NPC locations.

### CODE REVIEW

**Comment by orlandomf** [comment]
Valeu,  CALF!
Thanks, bro! It's working

**Comment by ShotGunBP** [comment]
Working, thanks Calf

**Comment by ShotGunBP** [comment]
Working, thanks Calf!

**Comment by flacrasec** [comment]
the gonryun Eden Officer needs correction: gonryun 145 120 moc_para01 31 14 c c r0

**Pull request merged**
