### PR TITLE
Merge pull request #1 from OpenKore/master

### PR DESCRIPTION
**Pull request by snop222**
Synchronize my fork from openkore main repo

### CODE REVIEW

**Comment by snop222** [comment]
Synchronize my fork from openkore main repo

**Comment by ya4ept** [comment]
Why do we need this pull request??

**Comment by itsrachelfish** [comment]
We don't. @snop222 is still confused how git works. @snop222 What is your native language?

**Comment by snop222** [comment]
Chinese Trandition !!

**Pull request closed without merging**
