### PR TITLE
Clean servertype kRO Zero and cRO

### PR DESCRIPTION
**Pull request by alisonrag**
move kRO Zero and cRO packets and parsers to st0, Receive.pm and Send.pm

### CODE REVIEW

**Comment by kopina110** [comment]
. I'm sorry, but would it be possible for me to get an invitation to kro discord?

**Comment by sctnightcore** [comment]
http://openk0re.xyz/
@kopina110

**Comment by kopina110** [comment]
The old kro discord chat room is missing and you need the invite code. :(

**Comment by sctnightcore** [comment]
@kopina110

use forum !

**Pull request merged**
