### PR TITLE
update fields up to kRO July, 2021

### PR DESCRIPTION
**Pull request by alisonrag**
keep in a separated folder old maps:
prontera (is the same, but just in case)
alberta
izlude
payon
morroc

### CODE REVIEW

**Comment by alisonrag** [comment]
> what have you done with these fields?
> image

i just took all maps from kRO and replaced in fields, this maps should be the same and still in openkore

**Comment by alisonrag** [comment]
image

**Comment by alisonrag** [comment]
altered to draft, portals.txt still has 300+ npc portals to review

**Comment by alisonrag** [comment]
reverted unrelated changes made, and now only fields is updated

**Comment by ya4ept** [comment]
> reverted unrelated changes made, and now only fields is updated

why?

**Comment by alisonrag** [comment]
> > reverted unrelated changes made, and now only fields is updated
> 
> why?

Check #3493 and #3494

**Pull request closed without merging**
