### PR TITLE
Wx , the orange dot

### PR DESCRIPTION
**Pull request by c4c1n6kr3m1**
update Wx.pm for the orange dot , the portals
the orange dot nailed on tables\portals.txt 
but not anymore , i think start3 hook is a better place

### CODE REVIEW

**Comment by c4c1n6kr3m1** [comment]
the orange dot bind to tables\portals.txt
try delete or rename your tables\portals.txt and see what happen to the orange dot

**Comment by c4c1n6kr3m1** [comment]
remove your tables\portals.txt and the orange dot gone

**Comment by Fadreus** [comment]
@c4c1n6kr3m1 Any screenshot ?

**Comment by c4c1n6kr3m1** [comment]
i'm too lazy to create ss :D

i'll make it clear
you have localize tables\yourserver\portals.txt
an example , you play bRO , you have tables\bRO\portals.txt
yes your bot will use this one
but...
wx, the orang dot always come from tables\portals.txt
you will realize the buggy orange dot if you play renewal and classic from the same openkore

**Comment by Nipodemos** [comment]
just tested, it is working
image

**Comment by Nipodemos** [comment]
for a possible future, it would be nice do differentiate npcs that can teleport (kafras and so on) from actual portals, 
because on this map, there is no difference

**Pull request merged**
