### PR TITLE
[2016-11-17] Poseidon servertype for bRO

### PR DESCRIPTION
**Pull request by lututui**
http://openkorebrasil.org/index.php?/topic/1855-atualiza%C3%A7%C3%A3o-17-11-2016/

### CODE REVIEW

**Comment by flacrasec** [comment]
purrfect!(if someone played secret of mana will remember thi)s

**Comment by lututui** [comment]
DO NOT MERGE THIS. THERE'S SOMETHING FUNKY HAPPENING

**Comment by itsrachelfish** [comment]
@lututui Woah. What happened?

**Comment by flacrasec** [comment]
this week ragexe was not compatible with poseidon soo we used the ragexe from last week we are hoping that next week it reverts to normal.

**Pull request closed without merging**
