### PR TITLE
iRO Bypass changes

### PR DESCRIPTION
**Pull request by Henrybk**

### CODE REVIEW

**Comment by Henrybk** [comment]
It is working well to connect and play but there may be a few check packets that have not been implemented yep, use of these changes are dangerous, use at your own risk.

**Comment by sctnightcore** [comment]
WORKKK !!

**Comment by kaliwanagan** [comment]
@Henrybk how different is your branch from #957 ? Maybe we should standardize on one branch so we can clean up on that one?

**Comment by Hurancan** [comment]
Is it working for you guys? I tried to but i keep dcing from map server.

**Comment by ihansouza** [comment]
Do u know how to scape from 30 minutes ban?

**Comment by alisonrag** [comment]
download the latest version and use #957

**Pull request closed without merging**
