### PR TITLE
remove unconstructive code

### PR DESCRIPTION
**Pull request by alisonrag**
remove useless code

### CODE REVIEW

**Comment by kaliwanagan** [comment]
Ooooh. But what does it *do* ? :D

**Comment by alisonrag** [comment]
If the software name are XR-Kore or KSMode are set to 1 in config spam hook with "die" in content

**Comment by lututui** [comment]
I find it amusing this is been there for at least 12 years (I couldn't find the commit, that's as far as I went) and no one noticed it/questioned it

**Comment by alisonrag** [comment]
xr-kore are dated in sourceforge from 2006-01-17
the code must been more old.

**Pull request merged**
