### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by sctnightcore**
If it's short, I think people will use it.

### CODE REVIEW

**Comment by Nipodemos** [comment]
this seems very good, shorter, simpler and equally efficient as the old one
maybe better

**Comment by alisonrag** [comment]
i think we should keep:
´´´
-* Before submitting an issue, ensure you are on the latest release
 -* Check if an issue already exists for your request
 -* Please post in English if possible
´´´

**Comment by Fadreus** [comment]
Agree with alison.

I think this is unnecessary
`* **Topic**:` 
Topic = Issue Title

How about put a little note/warning? Such as
-DON'T DELETE THIS. FILL THIS FORM.
-Use this template or your issue will be closed.

**Comment by wei** [comment]
Alternatively, you can use [wei/new-issue](https://github.com/wei/new-issue) : D

**Comment by Nipodemos** [comment]
i must agree that this we/new-issue seems to be a awnsome thing :smile:

**Comment by Nipodemos** [comment]
what do you guys think now? @Fadreus @alisonrag @sctnightcore ??
i've updated

**Comment by alisonrag** [comment]
ok to me

**Pull request merged**
