### PR TITLE
fix 'sitAuto_hp_lower' and 'sit' command for Novice 1-3 job lvl

### PR DESCRIPTION
**Pull request by ya4ept**
1) If a Novice (1-3 job lvl) uses the default setting `sitAuto_hp_lower 40` and its HP is reduced to 40%, then the bot just stops and does nothing.
2) If a Novice (1-3 job lvl) uses `sit`command then the bot just stops and does nothing.

I added _NV_BASIC_ check.

### CODE REVIEW

**Comment by ya4ept** [comment]
see please [src\Task\SitStand.pm (line 99)](https://github.com/OpenKore/openkore/blob/master/src/Task/SitStand.pm#L99)
`	} elsif ($self->{actor}->getSkillLevel(new Skill(handle => 'NV_BASIC')) < 3 && ($self->{actor}{jobID} == 0 || $self->{actor}{jobID} == 161)) {  # Check NV_BASIC skill only for Novice and High Novice`

I think this is an extra condition:
`&& ($self->{actor}{jobID} == 0 || $self->{actor}{jobID} == 161)`

**Comment by Nipodemos** [comment]
testing now

**Comment by ya4ept** [comment]
@Nipodemos  how about my previous comment?

**Comment by Nipodemos** [comment]
i don't know what that piece of code does and why it was not working

**Comment by ya4ept** [comment]
it works, but it seems to me that there are too many unnecessary verification conditions

**Comment by Fadreus** [comment]
Doram cant sit on command.

**Comment by Fadreus** [comment]
Doram cant sit on command.
It still checking for NV_BASIC.

**Pull request merged**
