### PR TITLE
update iRO Renewal files

### PR DESCRIPTION
**Pull request by allanon**
- [ ] QA Review

This pull request was auto-generated by patch_iro.pl: https://gist.github.com/allanon/38620af49d250005acbf

### CODE REVIEW

**Comment by jeffkewjk** [comment]
renewal bot can use yet? sorry im newbie. can u refer me to the update for renewal? my openkore says time out on map server

**Comment by sctnightcore** [comment]
@jeffkewjk  wait !!!

**Comment by bunnyy00** [comment]
@sctnightcore do you know where to locate patch_iro.pl? I have been trying so hard to find this file but failed to locate it.. in openkore file? or in gravity file? or?

**Comment by natsume1st** [comment]
i've added the update for the iro renewal items and items description files but i still get timeout from map server.. hmm are there still any files that i need to update ?

**Comment by bunnyy00** [comment]
@natsume1st they said/, just wait...

**Comment by natsume1st** [comment]
@allanon it works thanks dude :)

**Comment by Rogersx** [comment]
I would greatly appreciate if you can tell me where to find the patch_IRO.pl. I can't find it anywhere. Thank you so much

**Pull request merged**
