### PR TITLE
Add support for RMS Test Server

### PR DESCRIPTION
**Pull request by lututui**
- [x] QA
- [x] Code Review

Adds initial support for RagexeRE_2014_10_22b, based on RMS Test Server. This server used to be supported, and is still listed in servers.txt (entries 20 and 21). recvpackets.txt and cryptKeys were generated by PEEK

RMS Test Server: http://play.ratemyserver.net/ragnarok/

Known issues:
* ~~Picking up items doesn't work every time ('item_take')~~ 5ded68f

### CODE REVIEW

**Comment by lututui** [comment]
The item pickup issue has been solved

**Comment by lututui** [comment]
**Note for anyone who wishes to test**

In order to register, simply put **_M** or **_F** _after_ your desired username upon first login.

Example:
```
username: lututui_F
password: abcd
```

This would create a _female_ account after the username of _lututui_. On future logins, simply remove _M/_F from the login.

Example:
```
username: lututui
password: abcd
```

In this server, most athena commands are available, such as _warp, item, zeny, job, blvl, jlvl_ and many more.

**Comment by flacrasec** [comment]
Just need to review the bug when you create the char lututui, but this is working great! =)

**Comment by lututui** [comment]
@flacrasec I believe that issue has now been solved

**Comment by flacrasec** [comment]
Yes indeed now that is working fine! thank you lututui

**Pull request merged**
