### PR TITLE
Added bRO GMs

### PR DESCRIPTION
**Pull request by flacrasec**
all bRO GMs updated

### CODE REVIEW

**Comment by GuiHeff1999** [comment]
Grato o/'

**Comment by orlandomf** [comment]
Thanks, man!

**Comment by itsrachelfish** [comment]
Hey cool!

**Comment by itsrachelfish** [comment]
Hmm... maybe it would be better if the avoid list was a table file instead of control? Then we could have default avoid lists for each server

**Comment by flacrasec** [comment]
@itsrachelfish hey I was thinking the same when I made this pull request, but unfortunately I lack the knowledge to do that...

**Comment by lututui** [comment]
@flacrasec bRO has a translated control folder. You could put it there! It's in tables/bRO/control-br

**Comment by flacrasec** [comment]
@lututui just this? Sooo its simple after all thank you!

**Comment by flacrasec** [comment]
I will close this. and create a avoid at tables/bRO/control-br thx.

**Pull request closed without merging**
