### PR TITLE
Updating packet tables and keys for iRO Renewal

### PR DESCRIPTION
**Pull request by delawr0190**
20180802 maintenance.

### CODE REVIEW

**Comment by lobocop** [comment]
renewal packets are working! thanks

**Comment by unicornbaby** [comment]
This works thanks

**Comment by Nipodemos** [comment]
if it is working then it will be merged :smiley:

**Comment by Nipodemos** [comment]
thank you @delawr0190 for the update :D

**Comment by delawr0190** [comment]
Thank you!  :)

**Pull request merged**
