### PR TITLE
Build changes

### PR DESCRIPTION
**Pull request by lututui**
### NEEDS TO BE TESTED

# Relates to
* #1688 (We still use scons 2.0.1)

# Tasks
- [x] Fix compiling on mingw32 (Windows)
- [x] Fix compiling on mingw64 (Windows)
- [ ] Fix compiling on cygwin (Windows)
- [x] Autodetect perl version for dll linking (Windows)

# Changes
## Affects all systems (compiling)
* [Replace SCons 2.0.1 with SCons 3.0.1](https://github.com/OpenKore/openkore/pull/2402/commits/2ff33c3d3ff22314c9e28bc4ecb8cc7b4df8d403)

## Affects windows (compiling)
* [Include winsock2.h before windows.h](https://github.com/OpenKore/openkore/pull/2402/commits/d9706854f64f7be5c043bc0d8f4f425d2a43660b)
* [Avoid HASH_FUN_H redefinition](https://github.com/OpenKore/openkore/pull/2402/commits/40a4e2d96b50244b778bbd989a93986bfe9b928f)
* [Fix compilation flags](https://github.com/OpenKore/openkore/pull/2402/commits/9b463b0c20b342e8c3510cb655e422c5ca594fa2)
* [Autodetect perl version](https://github.com/OpenKore/openkore/pull/2402/commits/a2da377db47c13c62f26454c4df7442c5433f4eb)

## Affects all systems (runtime)
* [Update src/deps/](https://github.com/OpenKore/openkore/pull/2402/commits/2ff33c3d3ff22314c9e28bc4ecb8cc7b4df8d403)

### CODE REVIEW

**Comment by alisonrag** [comment]
using this pull i was able to recompile NetRedirect.dll and XSTools.dll

to compile i have instaled:
```
Python - 2.7.1 (x86)
Perl Strawberry - 5.28 (x86)
```
open cmd, go to openkore folder and run:
`gmake`

to new dll version and openkore run in latest perl version we have to
1 - delete openkore\src\deps\Devel
2 - delete openkore\src\deps\Exception
3 - delete the third comparation in file fastutils.xs line 107

**Comment by alisonrag** [comment]
approved, but we really need to be careful about fastutils.xs line 107

**Comment by ya4ept** [comment]
See attempt to compile on OS Lubuntu:
https://pastebin.com/QBnix3UY

```bash
In file included from src/auto/XSTools/utils/mirror-http-reader.cpp:27:0:
src/auto/XSTools/utils/win32/platform.h:2:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
          ^~~~~~~~~~~
compilation terminated.
scons: *** [src/auto/XSTools/utils/mirror-http-reader.o] Error 1
scons: building terminated because of errors.
-e Compilation failed. Please read http://wiki.openkore.com/index.php/How_to_run_OpenKore for help.
```

**Comment by lututui** [comment]
@ya4ept that should be fixed now
@alisonrag I've updated src/deps and removed my incorrect patch to fastutils

**Comment by c4c1n6kr3m1** [comment]
@Henrybk , you can build xstools for https://github.com/OpenKore/openkore/pull/1684 ?

**Comment by lututui** [comment]
Ticked "[Autodetect perl version for dll linking (Windows)](https://github.com/OpenKore/openkore/pull/2402/commits/a2da377db47c13c62f26454c4df7442c5433f4eb)"

**Comment by lututui** [comment]
Ticked "[Fix compiling on mingw64](https://github.com/OpenKore/openkore/pull/2402/commits/63c453339efc3af843b07329f9b90f799fc3e8fa)"

**Pull request merged**
