### PR TITLE
Removed deal action check from processDead sub.

### PR DESCRIPTION
**Pull request by deezar**
Removed "deal" action check from processDead sub. Is that relevant here?

### CODE REVIEW

**Comment by itsrachelfish** [comment]
Maybe this was added by someone who was trying to deal their bot Yggs before they auto-respawn?

**Comment by deezar** [comment]
I'm not sure either. 
But isn't Yggdrasil Leaf only usable if a player isn't dead?
Moreover the processDead should be independent from respawn action. If that's the case it should check just before respawn.
A quick glance what's inside this IF statement has nothing to do with "deal" action.

**Comment by itsrachelfish** [comment]
@deezar I just did a bit of digging into the code history. This change was intentionally added 11 years ago to ensure that dealAuto works even when the player is dead.

https://github.com/OpenKore/openkore/commit/36d1d3cecc0612dd40f380415f5aeeaa0a26e784

Is there a reason that you think this check should be removed?

**Comment by allanon** [comment]
While it's true that dealing an Ygg Leaf _to_ a dead player is useless, dealing an Ygg Leaf _from_ a dead player to a live player would allow the live player to resurrect the dead player.

**Comment by farrainbow** [comment]
It's not the best implementation but the purpose makes sense for me.

**Comment by kaliwanagan** [comment]
I'll be closing this PR for now. I think the original scenario was e.g. a priest that had lots of ygg leafs, following a tank (e.g. a blacksmith or a knight) that only loots. If the priest dies, the priest can deal the tank an ygg leaf so the tank can resurrect the priest.

**Pull request closed without merging**
