### PR TITLE
Fix formatting for NPC talk response choices #271

### PR DESCRIPTION
**Pull request by ChrstphrR**
***Fixed two issues outlined in Ticket #271:***

**Issue A** - Text for the NPC talk response choices were cut off if they
were longer than 36 characters.

**Issue B** - Numeric response codes for the choices need to be right
justified because up to two digit codes (i.e. more than 0-9 choices)
are possible.

Fixed by referencing: http://perldoc.perl.org/perlform.html

ticket:   #271
branch:   talk_response
modified: src/Commands.pm

### CODE REVIEW

**Comment by ChrstphrR** [comment]
Tested changes to formatting on iRO, using the same NPC mentioned in the steps-to-reproduce listed in ticket #271 

- [x] Numeric response codes are now right justified, up to two digits
- [x] Response text length is not restricted to the width of the "Response" header/footer

Please test independently to confirm.

**Comment by itsrachelfish** [comment]
@ChrstphrR Can you provide an example of an NPC that gives more than 9 response options so I can test? Thanks!

**Comment by ChrstphrR** [comment]
Yes, that's the one - but to save anyone searching:   on a renewal server:   payon_in01 5, 134 (Inventor Jaax) tests out both formatting changes in two of the response choice lists it provides.

**Comment by itsrachelfish** [comment]
@ChrstphrR As per my comment in the issue, I think we should keep the left alignment for now to remain consistent with all of the other list commands.

If you really think that all lists should use right alignment, that should be a separate pull request.

Other than that, I tested and confirmed that the truncation issue is now fixed!

**Pull request merged**
