### PR TITLE
update iRO Restart files

### PR DESCRIPTION
**Pull request by allanon**
- [ ] QA Review

This pull request was auto-generated by patch_iro.pl: https://gist.github.com/allanon/38620af49d250005acbf

### CODE REVIEW

**Comment by Rovejoe** [comment]
IRO Renewal updates ?

**Comment by h3h3h31985** [comment]
iro renewal pls

**Comment by loadinghero** [comment]
(iRO RenewaiRO Renewal)
-fix update iRO Renewal files
-fix update iRO Classic files
-----------------------------------------------------------------
Connecting to Map Server...
Connecting (128.241.92.131:4502)... connected
Timeout on Map Server, connecting to Account Server...
Connecting to Account Server...
[reconnect] Login retry number 2, setting reconnect timeout to 63 seconds.
Connecting (128.241.92.162:6800)... connected
Timeout on Account Server, reconnecting. Wait 63 seconds...
------------------------------------------------------------------
pls

**Comment by Fadreus** [comment]
In which dictionary "update" mean "fix"?
Or am I wrong?
I thought it was English, no?

Is this conspiracy?
Some code among Freemason?

**Comment by KamalAdli** [comment]
same like ro restart
help too

**Comment by loadinghero** [comment]
> @allanon

I'm change (update iRO Renewal files) not run.

**Comment by vagetablee** [comment]
@allanon  Thank you.

**Comment by Nipodemos** [comment]
this update unfortunaly doesn't make the openkore work on iro guys :cry:

**Pull request merged**
