### PR TITLE
Updating packet tables and keys for iRO Renewal

### PR DESCRIPTION
**Pull request by delawr0190**
20180809 maintenance.

### CODE REVIEW

**Comment by Nipodemos** [comment]
anyone can test this?

**Comment by Rovejoe** [comment]
@Nipodemos i works ! try it !

**Comment by babyfatz41** [comment]
should i copy this so my open kore works?


i am noob

**Comment by itsrachelfish** [comment]
@delawr0190 Thanks for your help :slightly_smiling_face:

**Pull request merged**
