### PR TITLE
Portals Update - New World / Verus

### PR DESCRIPTION
**Pull request by Fadreus**
## iRO
Added:
- [x] Cat Hand Agent (New world teleporter)
- [x] Midgard Camp
- [x] Dimensional Gap
- [x] Manuk
- [x] El Dicastes
- [x] Splendide
- [x] Verus
- [x] Flame Basin (Entrance only)
- [x] Eclage (Prison not added)

Updated:
- [x] Eden HQ
- [x] Mora

## bRO
- [ ] Cat Hand Agent (New world teleporter)
- [ ] Midgard Camp
- [ ] Dimensional Gap
- [ ] Manuk
- [ ] El Dicastes
- [ ] Splendide
- [x] Verus
- [ ] Flame Basin (Entrance only)
- [ ] Eclage (Prison not added)
- [x] Rock Ridge

Known bugs:
- For some reason openkore unable to calculate route between `verus04` & `ver_tunn`

### CODE REVIEW

**Comment by Fadreus** [comment]
Do other server use Cat Hand Quest to access new world?
I'm not sure to add Cat Hand Agent from Eden HQ -> Mid Camp. :thinking:

**Comment by lututui** [comment]
bRO is the same.

The problem that might arise is trying to shortcut through Cat Hand Agent with a character that didn't do the Cat Hand quest and getting stuck in a loop

**Comment by lututui** [comment]
Mind if I copy/paste this into tables/bRO/portals.txt?

**Comment by Fadreus** [comment]
I assume bRO portal update wouldn't necessary to be in different PR, no? :thinking: 
So I make the initial changes for it or @lututui wanna make it on separate PR?

**Comment by Fadreus** [comment]
Umu.. Dozo dozo..
image
I'll just make the initial changes then.

**Comment by alisonrag** [comment]
nice work here <3

**Pull request merged**
