### PR TITLE
[cRO] 2020-02-27 update

### PR DESCRIPTION
**Pull request by alisonrag**

### CODE REVIEW

**Comment by alisonrag** [comment]
@mcpchen @hubertyang88 can you test it?

**Comment by mcpchen** [comment]
The package you provided should be no problem. Let's test it later. I'm studying ollidbg. Thank you very much.
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"notifications"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年2月28日(星期五) 上午6:16
 收件人:&nbsp;"OpenKore/openkore"<openkore@noreply.github.com&gt;;
 抄送:&nbsp;"阿仙奴-Arsenal"<2356507@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [OpenKore/openkore] [cRO] 2020-02-27 update (#3073)

 

 
@mcpchen @hubertyang88 can you test it?

**Comment by hubertyang88** [comment]
1, \src\Network\Receive\ServerType0.pm  don't need modify , if cRO is add in those line(860 906 925) , itemlist become messy
 2, \src\Network\Receive\cro.pm need add this
 $self->{rodex_read_mail_item_pack} = "v V C3 a16 a4 C a4 a25";
3,vender list is messy , can't enter other vender's shop , buy item from npc is ok
4, cmd pl have minor problem , player's lv is wrong sometimes

**Comment by hubertyang88** [comment]
for verder list this works
$self->{vender_items_list_item_pack} = 'V v2 C V C3 a16 a25';

**Comment by hubertyang88** [comment]
0ADA this is refine msg broadcasted in sever , this is come with new refine UI

**Comment by alisonrag** [comment]
@mcpchen @hubertyang88 
can you send me the  the "system" folder in inside of the Ragnarok folder?
image

**Comment by alisonrag** [comment]
updated as requested by @hubertyang88

**Comment by mcpchen** [comment]
&nbsp;
  Please provide your personal email address

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"notifications"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年2月29日(星期六) 凌晨1:18
 收件人:&nbsp;"OpenKore/openkore"<openkore@noreply.github.com&gt;;
 抄送:&nbsp;"阿仙奴-Arsenal"<2356507@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [OpenKore/openkore] [cRO] 2020-02-27 update (#3073)

 

 
@mcpchen @hubertyang88
can you send me the the "system" folder in inside of the Ragnarok folder?

**Comment by alisonrag** [comment]
> &nbsp; Please provide your personal email address
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"notifications"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月29日(星期六) 凌晨1:18 收件人:&nbsp;"OpenKore/openkore"<openkore@noreply.github.com&gt;; 抄送:&nbsp;"阿仙奴-Arsenal"<2356507@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [OpenKore/openkore] [cRO] 2020-02-27 update (#3073) @mcpchen @hubertyang88 can you send me the the "system" folder in inside of the Ragnarok folder? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

alisonserafim@gmail.com

will be avaliable only for 1 day, please save with yourself

**Comment by mcpchen** [comment]
please check you gmail.
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"notifications"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年2月29日(星期六) 凌晨1:45
 收件人:&nbsp;"OpenKore/openkore"<openkore@noreply.github.com&gt;;
 抄送:&nbsp;"阿仙奴-Arsenal"<2356507@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [OpenKore/openkore] [cRO] 2020-02-27 update (#3073)

 

  
&nbsp; Please provide your personal email address
…
------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"notifications"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月29日(星期六) 凌晨1:18 收件人:&nbsp;"OpenKore/openkore"<openkore@noreply.github.com&gt;; 抄送:&nbsp;"阿仙奴-Arsenal"<2356507@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [OpenKore/openkore] [cRO] 2020-02-27 update (#3073) @mcpchen @hubertyang88 can you send me the the "system" folder in inside of the Ragnarok folder? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
 
alisonserafim@gmail.com
 
will be avaliable only for 1 day, please save with yourself

**Comment by alisonrag** [comment]
updated items*.txt and attendance_rewards

**Pull request merged**
