### PR TITLE
fix: add id check in npc talk close

### PR DESCRIPTION
**Pull request by alisonrag**
fixes: #3713

### CODE REVIEW

**Comment by alisonrag** [comment]
before:
```
Input: autosell
Initiating auto-sell.
Task::TalkNPC::new has been called with sequence 's'.
Talking with NPC Tool Dealer#pay1 (0) at (87,34), ID 7E 78 8E 06
Task::TalkNPC::addSteps has been called with value 'x'.
Task::TalkNPC::addSteps has been called with value 's'.
Sent look: 5
Iteration at Task::TalkNPC, current_talk_step '', next step 'x'.
NPC Tool Dealer#pay1 (0): Initiating the talk
Sent talk: 7E 78 8E 06
<< Received packet:      00B6 - NPC Cancel [ 6 bytes]
Received packet: 00B6 Handler: npc_talk_close
110002986
1: Stage
NPC Tool Dealer#pay1 (0): Done talking
AI: NPC sellAuto | 3
<< Received packet:      00C4 - NPC Buy-Sell [ 6 bytes]
Received packet: 00C4 Handler: npc_store_begin
<< Received packet:      00B6 - NPC Cancel [ 6 bytes]
Received packet: 00B6 Handler: npc_talk_close
110002986   buy_or_sell
NPC Tool Dealer#pay1 (0): Sending talk cancel after NPC has done talking
Sent talk cancel: 7E 78 8E 06
There are still steps to be done but the conversation has already ended (current step: s).
NPC Tool Dealer#pay1 (0): Task::TalkNPC::DESTROY was called
<< Received packet:      00B6 - NPC Cancel [ 6 bytes]
```

after:
image

**Review by LastRoze — APPROVED** [review]

**Review by ya4ept — APPROVED** [review]
It's OK

**Comment by hexhexd** [comment]
FYI TalkNPC becomes broken after seeing debug message "debug "We received an strange 'npc_talk_done', just ignoring it\n", "npc";"
I reverted the change locally and the problem went away. I might do some more digging later.

```
[2023.04.17 16:51:43.50] Talking to NPC at (26, 30) using sequence: r0
[2023.04.17 16:51:43.51] Task::TalkNPC::new has been called with sequence 'r0'.
[2023.04.17 16:51:43.51] Talking with NPC 侍従ベル#ep16_main (0) at (26,30), ID 68 14 00 00
[2023.04.17 16:51:43.52] Task::TalkNPC::addSteps has been called with value 'r0'.
[2023.04.17 16:51:43.53] According to the given NPC instructions, a npc conversation code should be used (r0), but it doesn't exist.
[2023.04.17 16:51:43.54] Using method '0' defined on config key 'npcWrongStepsMethod' to deal with the error.
[2023.04.17 16:51:43.54] Cleaning all remaining conversation steps, please input more steps using commands.
```

**Comment by LastRoze** [comment]
Do you activate the "autoTalkCont 1"?

If not then that might the problem, if you don't have it turned on (1) then you need to define the steps yourself like c r0 c c r0
Make sure to check the npcWrongStepsMethod too, check this Wiki https://openkore.com/wiki/npcWrongStepsMethod

**Comment by hexhexd** [comment]
I have `autoTalkCont 1` and `npcWrongStepsMethod 0`. My issue only happened after applying this commit.

**Comment by alisonrag** [comment]
can u post your config or macro? i will try to replicate

**Comment by hexhexd** [comment]
It's okay, I reverted the change locally so I'm not affected by it. I didn't customize any config for NPCTalk. The above error is triggered by talknpc x y r0 after `We received an strange 'npc_talk_done', just ignoring it\n", "npc";` It might be jRO specific. I'll try to reproduce it in a few days 😀

**Pull request merged**
