### PR TITLE
 Update packet send [kRO:RE]

### PR DESCRIPTION
**Pull request by sctnightcore**

### CODE REVIEW

**Comment by sctnightcore** [comment]
@Nipodemos  
I think kRO:RE use only recvpacket .

**Comment by alisonrag** [comment]
Oficial servers use shuffle instead of define packets manual in servertype(Send)

**Comment by sctnightcore** [comment]
@alisonrag

I think this is better for kRO: RE :p

**Comment by alisonrag** [comment]
why del recpackets?

**Comment by sctnightcore** [comment]
recpackets is old . 
check : http://herc.ws/board/topic/15348-kro-unpacked-clients-releases/

It have many update of packet size .

**Comment by sctnightcore** [comment]
> why del recpackets?

recpackets is old .
check : http://herc.ws/board/topic/15348-kro-unpacked-clients-releases/

It have many update of packet size .

**Comment by alisonrag** [comment]
I disagree with some points of this pull request:
1 - you are just deleting the recvpackets file instead of updating it
2 - you are just deleting the sync file instead of updating it
3 - you are passing the shuffle to manual, practice that has already been discontinued in official server files.

**Comment by sctnightcore** [comment]
> I disagree with some points of this pull request:
> 1 - you are just deleting the recvpackets file instead of updating it
> 2 - you are just deleting the sync file instead of updating it
> 3 - you are passing the shuffle to manual, practice that has already been discontinued in official server files.

Can i say lazy ? asdjalskdjalsd

**Comment by AlexandreVitorino** [comment]
Well man, PEEK already generates the shuffle list + recvpackets.
@alisonrag  About this sync, is this the old sync_ex_request ?

Because they are very easy to find ! 
You'll just need to modify the PEEK output.

**Comment by zPhotons** [comment]
Hello new packets for Renewal-Thor thank you!

**Pull request closed without merging**
