### PR TITLE
renewal crypt keys update

### PR DESCRIPTION
**Pull request by allanon**
Renewal (Chaos) has added crypt keys and packet shuffling.

I'm assuming this applies to Thor as well. Can anybody confirm?

### CODE REVIEW

**Comment by allanon** [comment]
This fixes #1161.

**Comment by sctnightcore** [comment]
I think we should add the iRO-Renewal servertype separately?

**Comment by allanon** [comment]
@sctnightcore Even if we had a separate servertype for iRO Renewal, the crypt keys config is in the `servers.txt` file. I'm just asking if I should set cryptKeys for Thor, or create a different tables directory for Thor (because right now it shares the iRO tables).

I suspect they're the same, because they use the same ragexe.exe. If that's true, the right solution is to add the same cryptKeys to the Thor section in `servers.txt`.

**Comment by sctnightcore** [comment]
@allanon  Thank you for answer

**Comment by shacalif** [comment]
Thanks guys!!, worked after manual update.

**Comment by sctnightcore** [comment]
#1167

**Comment by plokislokis** [comment]
THOR also having the same issue

**Comment by Dr-Chaos** [comment]
Work perfectly for me ! Ty very much for your work !! :)

**Comment by Rovejoe** [comment]
@Dr-Chaos how you do that ? i change manual i access to the map but still " Disconnected  from map server, connecting to account server in 46 second "

**Comment by CartoonShow** [comment]
I done all the step to update but still have a same issue. From THOR Server

**Comment by userix** [comment]
I have also manually downloaded all the updated files and replaced them in the corresponding folders, but still timing out during login.

**Comment by ragnarokfan** [comment]
looking perfect for me on xkore 0, times out on server if xkore 1

**Comment by Rovejoe** [comment]
Any updates for openkore ?

**Comment by Rovejoe** [comment]
@lututui hard to change .. can u give me the fail ?

**Comment by sctnightcore** [comment]
@Rovejoe  download new openkore on github ♥

**Comment by Rovejoe** [comment]
@sctnightcore can u give me link .. sorry im blind now .. xD

**Comment by sctnightcore** [comment]
image
@rovejoe

**Comment by Rovejoe** [comment]
@sctnightcore this openkore already to use  ? anyways, thnks buddy .. (^_^)

**Comment by sctnightcore** [comment]
try with youself ! @Rovejoe

**Pull request merged**
