### PR TITLE
Update scons makefile build

### PR DESCRIPTION
**Pull request by alisonrag**
Updated scons version from 3.0.1 to 3.1.1 (latest)
Added support to python 3.5+
Fixed error in commands: gmake `test `and `doc`

Now build should work with any perl 5.12+ version and with any python 2.7 and 3.5+ version

Todo:
- [x] test in windows (7,8,10)
- [x] test in unix
- [ ] test in mac

Tested with
OS: windows 7 x64
Perl: strawberry perl 5.30 x86
Python: 3.8

Observations:
in windows might be necessary copy powershell.exe from: `C:\WINDOWS\system32\WindowsPowerShell\vX.0` to openkore root folder
this is a bug in Scons + Python 3.5+

credits to @lututui, her latest "build" update made this "pull request" easier to do

### CODE REVIEW

**Comment by alisonrag** [comment]
ubuntu test:
image

**Comment by alisonrag** [comment]
test in windows 10 x64:
image

**Comment by ya4ept** [comment]
Need to fix:
- [ ] "make test" for ubuntu-18.04 + perl 5.12
- [ ] "make test" for ubuntu-20.04 + perl 5.12
- [ ] "make test" for windows-2016 + python 2.7 + perl 5.12
- [ ] "make test" for windows-2016 + python 3 + perl 5.32
- [ ] "make test" for windows-2019 + python 2.7 + perl 5.12
- [ ] "make test" for windows-2019 + python 3 + perl 5.32

**Comment by alisonrag** [comment]
if i'm not wrong these error are related to x64 version, if u can update to compile and use x86 this should work fine.

openkore has a lot of code that give errors whe using x64 version. idk if is possible to update to x64 and keep x86 support

**Comment by ya4ept** [comment]
изображение
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
изображение

i don't understand it...

**Comment by ya4ept** [comment]
are there x32 versions for ubuntu?

**Comment by alisonrag** [comment]
> are there x32 versions for ubuntu?

should be missing something while is installing the python / perl.
using perl 5.32 x64 and python 3.5 x64 i can run make and test without any issue

**Comment by ya4ept** [comment]
this test will run without errors:
- [x] "make test" for [ubuntu-18.04 + perl 5.31.1 x64 + python 3.9.1x64](https://github.com/OpenKore/openkore/pull/3138/checks?check_run_id=1895785923)
- [x] "make test" for [ubuntu-20.04 + perl 5.31.1 x64 + python 3.9.1x64](https://github.com/OpenKore/openkore/pull/3138/checks?check_run_id=1895785935)

Can you try: Ubuntu + perl 5.12 ?

**Comment by ya4ept** [comment]
strawberry ([actions-setup-perl](https://raw.githubusercontent.com/shogo82148/actions-setup-perl/8f960b4d8e71b90c1f031b32d67a6ad107263bde/versions/strawberry.json)) does not contain perl 5.12
I will try to fix it so that we use regular perl 5.12 and last strawberry

**Comment by ya4ept** [comment]
@alisonrag, [see please](https://github.com/OpenKore/openkore/actions/runs/573362494):
изображение

**Comment by alisonrag** [comment]
> @alisonrag, [see please](https://github.com/OpenKore/openkore/actions/runs/573362494):
> изображение

wide character is because of print russian characters while test load items.txt, the console dont have support, the other was there before haha

**Comment by alisonrag** [comment]
3.1.2 is the latest 3.x version, there is some bug fixes and improvements.
scons already has a 4.x version but is not compatible with python 3.4-
to keep the compatibilities let keep this way

**Comment by ya4ept** [comment]
> 
> 
> 3.1.2 is the latest 3.x version, there is some bug fixes and improvements.
> scons already has a 4.x version but is not compatible with python 3.4-
> to keep the compatibilities let keep this way

we use Python 3.9.1in github actions

**Comment by alisonrag** [comment]
> > 3.1.2 is the latest 3.x version, there is some bug fixes and improvements.
> > scons already has a 4.x version but is not compatible with python 3.4-
> > to keep the compatibilities let keep this way
> 
> we use Python 3.9.1 in github actions

do u think is a good idea to drop the support to python 2.7 and 3.4-? 
if yes i can try to update to scons 4.1

**Comment by ya4ept** [comment]
I do not know.. let's make this release first and then think about updating )))

**Review by ya4ept — APPROVED** [review]

**Comment by alisonrag** [comment]
thanks for the help in this pull <3

**Comment by ya4ept** [comment]
hurray, we did it!

**Pull request merged**
