### PR TITLE
RO:RESTART- NEWIP

### PR DESCRIPTION
**Pull request by sctnightcore**
<3
i love you all haha

### CODE REVIEW

**Comment by alphonse9** [comment]
THanks!

**Comment by sctnightcore** [comment]
#723

**Comment by sctnightcore** [comment]
Login Servers:
We are currently adding new hardware for the login process.  

idk

**Comment by wolventear** [comment]
Thanks a lot!!!!

**Comment by Jeffgomz** [comment]
working thanks many dude ^_^

**Comment by Jarlock171** [comment]
Why this is happening? i cant select my character ;-;
image

**Comment by narueponz** [comment]
i need link download

**Pull request merged**
