### PR TITLE
[2018-10-30] iRO ReStart update [DONT MERGE IT]

### PR DESCRIPTION
**Pull request by alisonrag**
- [ ] QA Review

This pull request was auto-generated by automated-update: https://github.com/alisonrag/automated-openkore-tables-update

### CODE REVIEW

**Comment by c4c1n6kr3m1** [comment]
why this pull edit renewal files?

**Comment by alisonrag** [comment]
@c4c1n6kr3m1 
is just a testing, instead of create a lot of pull-request i'm reusing the same

**Comment by alisonrag** [comment]
i will keep this for a while just for testing, please devs dont merge it

**Comment by alisonrag** [comment]
today is iRO update i'm closing to allanon or other people send a new pull-request

**Pull request closed without merging**
