### PR TITLE
added &InventoryType

### PR DESCRIPTION
**Pull request by madalilng**
returns all indexes of items in inventory with matching type as a comma-separated list or -1 if no item of type was found.

item types:
usable,equip,card,etc

sample usage :
macro InventoryType_test {
    $equips = &InventoryType(equip)
    @testEquips = &split(',', $equips )
    $i = 0;
    while ($i <  @testEquips ) {
        log inventory id : $testequips[$i]
        $i++
    }
}

### CODE REVIEW

**Comment by Nipodemos** [comment]
nice !!!

very handy

**Comment by iamtonysoft** [comment]
upvote for this!

**Comment by djkstra** [comment]
cool stuff. upvote!

**Comment by wagpoateh** [comment]
+1

**Comment by lututui** [comment]
Merged and documented
https://openkorebrasilwiki.miraheze.org/w/index.php?title=EventMacro&diff=1807&oldid=1806
http://openkore.com/index.php?title=EventMacro&curid=1052&diff=3905&oldid=3904

**Comment by Henrybk** [comment]
@lututui The keyword returns a comma separated list of items, not an array, maybe it should return an array.

**Comment by lututui** [comment]
Oh! I must have misread the code. I'll update the wiki

**Pull request merged**
