### PR TITLE
Servertype ragexe 2014 10 22b

### PR DESCRIPTION
**Pull request by Henrybk**
This pull request adds support for the servertype Ragexe_20141022b which many private servers use nowadays. I was only able to test it in one or 2 servers but it seemed to work fine.

The servertype was created based on the source code from rAthena.

The recvpacket were generated from a Ragexe_2014-10-22b I diffed myself.

### CODE REVIEW

**Comment by itsrachelfish** [comment]
@Henrybk Do you have any examples of what pservers this pull request can be tested on? Thanks :)

**Comment by Henrybk** [comment]
I could not find the servers I tested at haha.

Well it's working here and the packets aparently are right by this:
https://github.com/brAthena/brAthena/blob/master/src/map/packets.h
And this
https://github.com/rathena/rathena/blob/master/db/packet_db.txt

I guess I will have to find another server.

**Comment by itsrachelfish** [comment]
@Henrybk How is this different from the pull request @lututui created before?

https://github.com/OpenKore/openkore/pull/195

**Comment by Henrybk** [comment]
@itsrachelfish There is a difference between ragexe and ragexeRE, if you try to use this servertype to log into RMS server you won't be able to do it, and if you use #195 code to log into a server diffed with 2014-10-22ragexe hexed you won't be able to also.

**Comment by itsrachelfish** [comment]
Thanks for the clarification! :+1:

**Comment by magimagica** [comment]
I got this message when someone using a skill
Packet Parser: Unknown switch: 09CB

**Comment by m3kgin3er** [comment]
09CB now was fixed using https://github.com/OpenKore/openkore/issues/516

**Comment by a2362998** [comment]
[iRO] Packet Tokenizer: Unknown switch 09DB, 09DD  could someone help me pls  having problem with this

**Comment by m3kgin3er** [comment]
You should be banned of github.

**Comment by magimagica** [comment]
I get Unknown Switch: 09CA from time to time when hunting, not sure because of monster's skill or something else.

**Comment by LoseracK** [comment]
Well the correct way maybe is just to change it inside sT 0

**Comment by Slipxxliose** [comment]
What timestamp you've got?
What sT is u using ?

**Comment by kaliwanagan** [comment]
@Henrybk I'll close this for now. When those servers pop up again then we'll either rework on the new packets, or revisit this PR (if we remember)

**Pull request closed without merging**
