### PR TITLE
add missing partySkill keys

### PR DESCRIPTION
**Pull request by alisonrag**
add missing keys added at #1662
whenPartyMembersNear
whenPartyMembersNearDist

### CODE REVIEW

**Comment by ya4ept** [comment]
> Both are self coditions, therefore can be used in partySkill, useSelfSkill, useSelf_item, buyAuto, etc.

we can add to other blocks too

**Comment by alisonrag** [comment]
added to blocks where i found usefull, do you think need to add to some other?

**Comment by ya4ept** [comment]
What about `attackComboSlot`?

**Comment by alisonrag** [comment]
> What about `attackComboSlot`?

added to attackComboSlot.

**Comment by ya4ept** [comment]
@alisonragб have an idea why we need to check for the total number of people [here](https://github.com/OpenKore/openkore/blob/master/src/Misc.pm#L5050):
```perl 
if ($config{$prefix."_whenPartyMembersNear"}) {
	# Short circuit if there's not enough players nearby, party members or not
	# +1 account for self
	return 0 unless inRange(scalar @{$playersList} + 1, $config{$prefix."_whenPartyMembersNear"});

	# Short circuit if there's not enough players in our party
	return 0 unless inRange(scalar @partyUsersID, $config{$prefix."_whenPartyMembersNear"});
	...
```
I think this is an extra check:
``` perl
return 0 unless inRange(scalar @{$playersList} + 1, $config{$prefix."_whenPartyMembersNear"});
```

**Comment by ya4ept** [comment]
I looked more closely. I think everything is fine:
1. `scalar @{$playersList}` - this shows the number of people around, including the bot itself
2. `scalar @partyUsersID` - this always shows the number of players in the party (online and offline), including the bot itself
This code allows you to understand at an early stage that there are very few players around

**Pull request merged**
