### PR TITLE
kro zero conection files

### PR DESCRIPTION
**Pull request by alisonrag**
update:
* recvpackets
* sync
* shuffle

its possible to play, but is necessary bypass new motp system

### CODE REVIEW

**Comment by jiandan7927** [comment]
sor till unable to log in.because the modification becomes a web login and start.but thanks for the update it

**Comment by alisonrag** [comment]
@jiandan7927 
come here:
https://discord.gg/ENHwTg7

**Comment by cassandra209** [comment]
can i know how to bypass?

**Comment by myjae** [comment]
how to connect client ??

**Comment by sctnightcore** [comment]
@myjae 
https://discord.gg/WzpXp

30 min xD

**Comment by zanyunlong** [comment]
how to connect client ??

**Pull request merged**
