### PR TITLE
update iRO Renewal files

### PR DESCRIPTION
**Pull request by allanon**
- [ ] QA Review

This pull request was auto-generated by patch_iro.pl: https://gist.github.com/allanon/38620af49d250005acbf

### CODE REVIEW

**Comment by hexhexd** [comment]
I'm getting timeout on map server with the newest update.

**Comment by Nipodemos** [comment]
this update did nothing to fix that, so we must wait for another one that does @hexhexd

**Comment by Natasya90** [comment]
@Nipodemos  can u inform us when its fixed?

**Comment by hexhexd** [comment]
> this update did nothing to fix timeout on map server, so we must wait for another one that does @hexhexd

Cool, thanks for the heads up. My JDR is waiting lol

**Comment by Natasya90** [comment]
still not fix? @Nipodemos

**Comment by Nipodemos** [comment]
Sorry, I'm late 😅

**Comment by queen189** [comment]
How to make them not discover me ?? When i used this??

**Pull request merged**
