### PR TITLE
Supports timeout in equipAuto block

### PR DESCRIPTION
**Pull request by hexhexD**

### CODE REVIEW

**Comment by alisonrag** [comment]
i cant find any references to `$ai_v{"equipAuto_$i" . "_time"}`.
Can you show me where it is in use?

**Comment by hexhexD** [comment]
I think it's used here: https://github.com/OpenKore/openkore/blob/9a20e026525700c690fb50f0dc16b53feff48fb8/src/Misc.pm#L4784.

**Comment by hexhexD** [comment]
I have been using this for a while and it's working as intended. @alisonrag

**Review by alisonrag — APPROVED** [review]

**Comment by alisonrag** [comment]
checked the code and timeout key was missing to autoequip nice catch

**Review by ya4ept — APPROVED** [review]

**Comment by hexhexD** [comment]
Thanks for the review guys!

**Pull request merged**
