### PR TITLE
Only prontera is available for geffen non-vip warps

### PR DESCRIPTION
**Pull request by tpysz5n**

### CODE REVIEW

**Comment by alisonrag** [comment]
Server?
bRO still have the portals, also privates

**Comment by tpysz5n** [comment]
Oh so it's server dependent. I was using iRO

**Comment by c4c1n6kr3m1** [comment]
addTableFolders iRO/Renewal;iRO

make portals.txt on iro folder , and so an empty portalsLOS.txt
than let it auto compile or force with command "portals recompile"
and now your bot will use tables\yourserver\portals.txt

**Comment by bookbk** [comment]
> @Fadreus said once that iro was using `tables/portals.txt` instead of the portals on iro folder
> can anyone confirm that?

I confirmed that's true.

**Comment by tpysz5n** [comment]
> 
> 
> addTableFolders iRO/Renewal;iRO
> 
> make portals.txt on iro folder , and so an empty portalsLOS.txt
> than let it auto compile or force with command "portals recompile"
> and now your bot will use tables\yourserver\portals.txt

Thanks. This solves the problem. I'll fix my pull request

**Comment by c4c1n6kr3m1** [comment]
@Nipodemos
that official items&description&quest already list on each file inside folder tables\iRO

!include official/items.txt
!include official/itemsdescriptions.txt
!include official/quests.txt

**Comment by Nipodemos** [comment]
whaaaaaaat
what an odd way of doing this

**Comment by c4c1n6kr3m1** [comment]
don't ask me :dancing_men: 
maybe because old iro has more than 1 server , dunno ...

**Comment by Nipodemos** [comment]
so this pull request can already be merged

**Comment by Nipodemos** [comment]
now i remember, me and fadreus done some changes specific to iRO, but on `tables/portals.txt`
dammit i'm too lazy now to do something

**Comment by alisonrag** [comment]
Now iro have only 1 server, time to remove the files not in use

**Comment by c4c1n6kr3m1** [comment]
iRO will close
so, may be wait till reopen?

**Comment by Nipodemos** [comment]
what do you mean by close?

**Comment by tpysz5n** [comment]
@Nipodemos iRO Chaos and Thor will be down from 12/06/2019 thru 02/03/2020 [for a major update](https://forums.warpportal.com/index.php?/topic/245881-important-announcement-for-iro-10-15-2019/?p=2931072).

**Pull request merged**
