### PR TITLE
iRO Renewal / Re:Start Updates

### PR DESCRIPTION
**Pull request by iamtonysoft**
Need some test and review

### CODE REVIEW

**Comment by bunnyy00** [comment]
still Timeout on Account Server, reconnecting. Wait 124 seconds..., after downloaded the whole new file to test it.

**Comment by sctnightcore** [comment]
@bunnyy00  test with new PR . new recvpacket new sync new shuffle new key

**Comment by bunnyy00** [comment]
@sctnightcore What is PR?

**Comment by leonado8** [comment]
image

@sctnightcore may i ask how to fix this problem?

Thanks

**Comment by sctnightcore** [comment]
@leonado8  check you recvpacket 

if play restart > https://github.com/iamtonysoft/openkore/tree/master/tables/iRO/Restart
if play RE > https://github.com/iamtonysoft/openkore/tree/master/tables/iRO/Renewal

**Comment by leonado8** [comment]
@sctnightcore  Sry i used 3 new files of the link but same timeout account server,sry im newbie here

**Comment by sctnightcore** [comment]
@leonado8  wait Merge !

**Comment by leonado8** [comment]
@sctnightcore okay thanks

**Comment by TDresearch** [comment]
@sctnightcore I tested it, still stuck at map server

**Comment by sctnightcore** [comment]
**IRO : RE  work !** 
image

****IRO : RESTART** WORK** 
image

**Comment by TDresearch** [comment]
In renewal, doesn't work :(

**Comment by iamtonysoft** [comment]
@TDresearch try to download https://github.com/OpenKore/openkore/archive/master.zip

**Comment by leonado8** [comment]
@sctnightcore wow you are so pro,may i ask how you do that,i also need learn to you

**Comment by sctnightcore** [comment]
@leonado8  = = @iamtonysoft  do it  is not me.

**Comment by leonado8** [comment]
@sctnightcore oic then i need learn to him now haha

@iamtonysoft can teach me some skill? thanks

**Comment by sctnightcore** [comment]
@leonado8  
https://github.com/PoringUniverse 
He support eventmarco for iRo:Restart XD

**Comment by TDresearch** [comment]
It's working, tested it. Thanks @sctnightcore

**Comment by leonado8** [comment]
@sctnightcore oic i feel you all also so pro except me T.T

**Comment by sctnightcore** [comment]
@iamtonysoft do it is not me.

**Comment by iamtonysoft** [comment]
@leonado8 
do not learn from me. im noob im just fan of openkore
i just want automated things cause it looks cool, anyway do not make this a chatroom
feel free to join us https://discord.gg/bDmZfdR we are a fans club of openkore

**Comment by leonado8** [comment]
@iamtonysoft how to join discord?

**Pull request merged**
