### PR TITLE
fix: update processtake logic

### LINKED ISSUE #3268: the "itemsTakeGreed" parameter does not work optimally
i am using the following parameters:
```
itemsTakeAuto 1
itemsTakeAuto_new 0
itemsTakeGreed 1
```
at the same time, the bot always comes close to the item ([distance 1 cell](https://github.com/OpenKore/openkore/blob/master/src/AI/CoreLogic.pm#L795))

The Greed skill allows you to collect items at a distance of 2 cells.

See [r6386](https://sourceforge.net/p/openkore/code/6386/)

### PR DESCRIPTION
**Pull request by alisonrag**
fix #3268

### CODE REVIEW

**Comment by ya4ept** [comment]
can you test this functionality on archers?

**Comment by ya4ept** [comment]
- [ ] do not forget to edit the page after the merge

https://openkore.com/wiki/itemsTakeAuto_new

**Comment by alisonrag** [comment]
Regular test with archer:
https://youtu.be/74jOb-yaHqw

Greed Test:
https://youtu.be/TKYhNsI3HrI

**Comment by alisonrag** [comment]
> * [ ]  do not forget to edit the page after the merge
> 
> https://openkore.com/wiki/itemsTakeAuto_new

when someone approve i will remove the page

**Comment by ya4ept** [comment]
no need to delete, we have a special [Category:Deprecated](https://openkore.com/wiki/Category:Deprecated)

**Comment by ya4ept** [comment]
Very often the bot tries to stand on the object itself and then pick it up.
image

**Comment by alisonrag** [comment]
@ya4ept can you test: https://github.com/OpenKore/openkore/pull/3613/commits/11e01b5ade664e261000f07cbb94e469181d06d8 ?
seems solved the issue

**Comment by ya4ept** [comment]
problem solved!

**Review by ya4ept — APPROVED** [review]

**Comment by Henrybk** [comment]
Ran for a few hours with 2 rogues, seems fine and better than before.

**Comment by alisonrag** [comment]
documentation updated

**Pull request merged**
