### PR TITLE
Network cleaning

### PR DESCRIPTION
**Pull request by Henrybk**
Just some network cleaning, I moved some identical functions on Servertype0.pm and sakexe_0.pm to receive.pm

### CODE REVIEW

**Comment by Henrybk** [comment]
Sorry for the loads of commits.

**Comment by itsrachelfish** [comment]
No worries, this needed to be done!

**Comment by zuroba** [comment]
@Henrybk this code it's optimize for openkore ?

**Comment by Henrybk** [comment]
@zuroba It's only network cleaning, which by that I mean deleting duplicated functions.

**Comment by zuroba** [comment]
@Henrybk 

 oh ok thank for explain

openkore can optimize for code to work better

**Comment by Henrybk** [comment]
I guess even though I never got it finished it would be good to merge this, there is a lot of code cleaning here.

**Comment by itsrachelfish** [comment]
@Henrybk I should have time to review these changes over the weekend! Feel free to remind me on IRC in case I forget. :smile:

**Pull request merged**
