### PR TITLE
RO:Restart fix price warp and add some missing warp

### PR DESCRIPTION
**Pull request by phamtrong204**

### CODE REVIEW

**Comment by troymark901** [comment]
mine is working but if my other character dc when he is trying to talk to kafra for warp prontera to payon or pronter to geffen.

**Comment by phamtrong204** [comment]
@troymark901 The dc problem seems unrelated with my edit.
Pls check your openkore version.

screen shot 2017-08-21 at 15 04 59

**Comment by OMGMarshall** [comment]
i also dc talk to npc tools dealer and kapra.. can share me ur file sir.. i also dc when change to other map

**Comment by phamtrong204** [comment]
@OMGMarshall You can use this version at your own risk.
[pls read this comment](https://github.com/OpenKore/openkore/pull/957#issuecomment-323642421)

**Comment by troymark901** [comment]
i just change my timeouts but cannot connect on the game. :( pls help to fix the issue of talking to kafra getting dc

**Comment by phamtrong204** [comment]
@troymark901 It will be better for me when you read other comments. Thanks.

> @OMGMarshall You can use this version at your own risk.
> [pls read this comment](https://github.com/OpenKore/openkore/pull/957#issuecomment-323642421)

**Comment by OMGMarshall** [comment]
gambo
@phamtrong204  keep try to buy red potion..after buy dc

**Comment by kaliwanagan** [comment]
@phamtrong204 merged, and sorry for the spam. Looks like we've got some kids who failed their marshmallow tests on the loose again.

**Pull request merged**
