### PR TITLE
Update slave attack AI

### PR DESCRIPTION
**Pull request by Henrybk**
Adds CheckMonster do slave AI
Moves all slave Attack logic to AI/SlaveAttack (mimic AI/Attack)
Port all recent attack logic updates to slave attack logic (#3629 #3626 #3623 #3620 #3630)
Adds all missing checkSelfCondition relating to homun and merc to config
Adds attackAuto_inLockOnly logic to slaves

Still needs testing

### CODE REVIEW

**Comment by Henrybk** [comment]
If/when #3630 and #3631 get merged I'll be testing this properly

**Comment by Henrybk** [comment]
Openkore - New Slave Attack AI - Character without slave: https://www.youtube.com/watch?v=_BncQy3V8O4

Openkore - New Slave Attack AI - Archer + Fencer Mercenary: https://www.youtube.com/watch?v=38LBlftGn-g

Openkore - New Slave Attack AI - Archer + Archer Mercenary: https://www.youtube.com/watch?v=gmRlkdefvCc

**Review by alisonrag — APPROVED** [review]

**Comment by Henrybk** [comment]
I'll wait for #3634 to be fixed before testing more

**Comment by Henrybk** [comment]
A few videos homunculus and homun + merc using https://github.com/OpenKore/openkore/compare/fix_homun_state

https://www.youtube.com/watch?v=6E0R7Wsr55g
https://www.youtube.com/watch?v=0yyz0jQ7mLw

**Comment by Henrybk** [comment]
Seems to be working well (besides the homunculus state bug, which has nothing to do with these changes)

**Comment by Henrybk** [comment]
Removed these keys for homun and merc as their attack sequence would never trigger during said sequences anyway as they only trigger on these condition

```
 AI::isIdle
 || AI::is(qw(follow sitAuto attack skill_use))
 || ($config{$slave->{configPrefix}.'attackAuto_duringItemsTake'} && AI::is(qw(take items_gather items_take)))
 || ($config{$slave->{configPrefix}.'attackAuto_duringRandomWalk'} && AI::is('route') && AI::args()->{isRandomWalk}))
```

```
attackAuto_notWhile_storageAuto 1
attackAuto_notWhile_buyAuto 1
attackAuto_notWhile_sellAuto 1
```

**Comment by Henrybk** [comment]
I guess that's it for new features. I'll do a few 1-99 runs using merc, homun and none in a test server and if things go well I'll merge it

**Comment by Henrybk** [comment]
This paired with #3635 seems to be working well, found no bugs using it for the last 2 days

**Comment by ya4ept** [comment]
@Henrybk please add to documentation:
https://openkore.com/wiki/homunculus_resting
https://openkore.com/wiki/timeouts.txt:
* ai_homunculus_check_monster_auto 
* ai_mercenary_check_monster_auto

**Pull request merged**
