### PR TITLE
Updating packet tables and keys for iRO Restart

### PR DESCRIPTION
**Pull request by delawr0190**
20180801 maintenance.

### CODE REVIEW

**Comment by delawr0190** [comment]
I created this PR because I ended up with something different.  On his commit 1 week ago, all of the files were updated.  We seem to be identifying 0AF1 differently, and that was a problem that I believe existed 1 week ago.

If @allanon fixed his script and these are correctly auto-generated again, I can stop doing PRs.  But we still ended up with something different, so that's why I created this one.

**Comment by Nipodemos** [comment]
i understand, i didn't compare before saying this, so maybe his PR may not work yet
for now let's wait for someone to test, because i don't play on iRO :frowning_woman:

**Comment by delawr0190** [comment]
Just trying to help.  Let me know!  :)

**Comment by marielyn** [comment]
THank you Restart is working!!

**Comment by delawr0190** [comment]
Happy to hear!  @marielyn

**Comment by c4c1n6kr3m1** [comment]
you identified 0AF1 as 0821?

**Comment by Zelecktor** [comment]
delawr0190 I sent you an e-mail :)

**Comment by axangel** [comment]
Updated all the files. Restart still isn't working. "Timeout on map server..."

**Comment by marielyn** [comment]
@axangel i dont think its merged, you will need to update each file manually

**Comment by axangel** [comment]
@marielyn i did. i updated recvpackets, server, sync and shuffle - just like @sctnightcore revised

**Comment by axangel** [comment]
@marielyn that be much appreciated. how though? i've been taught not to give email addresses in forums lol.

**Comment by delawr0190** [comment]
@Rovejoe 

See https://github.com/OpenKore/openkore/pull/2222

**Comment by Rovejoe** [comment]
@delawr0190 aww so fst , ty so much ^^

**Comment by allnamesareunavailable** [comment]
Any update on the iRO Restart update?

**Comment by delawr0190** [comment]
This pull request should include the fixes.  I think that it's stuck because the feedback in here is mixed:  one person said it worked and the other said it wasn't working and never came back to update this thread.

**Comment by allnamesareunavailable** [comment]
Can someone just teach us how to update the recvpackets and stuff after every maintenance. That would help reduce the wait :)

**Comment by axangel** [comment]
@delawr0190 it should but for me it didn't work. I've updated everything as @sctnightcore revised but it still says timeout on map server.

**Comment by Fadreus** [comment]
image

If anyone have problem to log in, watch this video
https://www.youtube.com/watch?v=RhXg4tvIft4

**Comment by delawr0190** [comment]
@axangel 

What files are you updating?  Specifically, where are the files in your openkore folder?

You may either be updating the wrong server, or maybe you put them into the wrong folder and it's still pulling the old tables.

Also, I'd download a new version of OpenKore and update the tables in that version.

**Comment by axangel** [comment]
I did download the new OpenKore and updated the tables there

I also double checked everything is as @sctnightcore revised

server.txt in tables folder
recvpackets.txt, shuffle.txt and sync.txt in iRO->Restart folder

**Comment by delawr0190** [comment]
@scnightcore referenced a different pull request. Not my changes.

Can you try the tables here?  https://github.com/OpenKore/openkore/commit/eb5a8650793340adaa8d4d599800e9a5e01a30c7

**Comment by sctnightcore** [comment]
I'm lazy yo test.

**Comment by Fadreus** [comment]
Just merge this.

**Comment by arfelgabani** [comment]
Any update on the iRO Restart update? ill download all the file but it always disconnect.. time out on map server..

**Comment by Nipodemos** [comment]
okay, with a print i can trust, merging

**Pull request merged**
