### PR TITLE
compiled start.exe using perl version 5.22.1

### PR DESCRIPTION
**Pull request by ya4ept**
> https://www.activestate.com/blog/faqs/what-is-the-status-of-perl-dev-kit-and-activeperl-pro-studio/
> ActiveState will not be updating PDK to work with versions of ActivePerl newer than 5.22.

Trying to compile openkore to use perl 5.22
We need:
- [x] compile start.exe
- [ ] compile wxstart.exe
- [x] compile XSTools.dll
- [x] compile NetRedirect.dll
- [ ] change logo ??
- [ ] change dll version number?

I use:
- Windows 10 x32
- ActivePerl-5.22.1.2201-MSWin32-x86-64int-299574
- ActiveState.Perl.Dev.Kit.Pro.v9.5.1.300018.x86

Unresolved issues:
1. XSTools.dll and NetRedirect.dll compiled with ActivePerl-5.22 - not working. We can compile them using Strawberry Perl.
2. Compiled wxstart.exe - does not work

### CODE REVIEW

**Comment by ya4ept** [comment]
XSTools.dll size decreased by 2 times - is this normal?

**Comment by Nipodemos** [comment]
i'm very happy to see this finnaly coming.
unfortunaly i'm not the one to review your PR, i don't have enough knowledge
but i'm looking foward to this

**Comment by sctnightcore** [comment]
if rebuild .dll with ActivePerl-5.22.1.2201-MSWin32-x64-299574
https://pastebin.com/R2FrvmbK
got error

**Comment by Henrybk** [comment]
On Windows 10 64bit using Python 2.7.15 32bit and strawberry-perl-5.22.1.3-32bit I am able to use your provided start.exe and openkore.pl (with your dlls) without errors. If I try to compile the dlls openkore.pl won't start.
With everything else the same except using strawberry-perl-5.28.0.1-32bit I can compile the dlls and use them normally.

**Comment by Henrybk** [comment]
Using (again) Windows 10 64bit using Python 2.7.15 32bit but now with ActivePerl-5.22.1.2201-MSWin32-x86-64int-299574 and installing MinGW using CPAN (version 4.6.3) I was able to compile the dlls and run openkore with them.
But your dlls won't work in this system.

**Comment by Nipodemos** [comment]
@ya4ept don't give up!!
what's is still needed for you to keep going?

**Comment by alisonrag** [comment]
> @ya4ept don't give up!!
> what's is still needed for you to keep going?

as a conversation with Klab wx is not a suported lib, they not updated to the latest version, i think is better we find another interface and remake based on a new one

**Pull request merged**
