### PR TITLE
update iRO Classic and Renewal files

### PR DESCRIPTION
**Pull request by allanon**
- [x] QA Review

This pull request was auto-generated by patch_iro.pl: https://gist.github.com/allanon/38620af49d250005acbf

### CODE REVIEW

**Comment by sctnightcore** [comment]
#1208

**Comment by allanon** [comment]
This should fix #1210.

**Comment by Bilmola** [comment]
@allanon Thk

**Comment by lowkeeme** [comment]
Works perfectly fine! High-five, @allanon! Thank you so much for the updates.

**Comment by jomarlorica** [comment]
HI @allanon i cant run it. can you update your whole openkore edition? like this link you https://github.com/OpenKore/openkore

for us to easy download and run it. we dont know how to fix the  patchiro.pl sorry were not a programmer lol

**Comment by lowkeeme** [comment]
Everyone, here are the clarified steps. Take note to use Notepad++ for you to see the lines properly.

@jomarlorica, here are the steps:

Go to this link: 
Click #1209 and look for: Click iRO renewal crypt keys.

If you can't look for it, you may go directly straight to this link: https://github.com/OpenKore/openkore/pull/1209/commits/b3e4b7df861bcef7272a4ef29c6805dda685212f

-You will see there that there are information about crypt keys.

-Go to your Openkore folder and look for this:
Your Openkore folder/tables/iRO/ and look for recvpackets.txt.
Your Openkore folder/tables/iRO/ and look for shuffle.txt.
Your Openkore folder/tables/iRO/ and look for sync.txt
Your Openkore folder/tables/ and look for servers.txt.

Open the said files using Notepad++ for you to open the files properly and again, view each files from the website for you to copy them properly. You will see there's a **VIEW** button on each files. 

That should work.

**Comment by Vespertine32** [comment]
Working perfectly fine now, thanks @allanon

**Comment by ChrstphrR** [comment]
Not working for me:  charBlockSize is 145 in the master branch, and 144 for Renewal  and Sakray
When testing the iro_update branch, I'm getting truncated character records -- only one of the two is shown, with a missing first letter in the name.

Simply editing the charBlockSize to 145 as they are in master seems to just dump Kore right out, with an error message of  "Unknown charBlockSize: 145 at src/Network/Receive.pm line 253."

Also, the server records for iRO aren't named in a sane way -- we're still referencing Ymir/Yggdrasl/Valkyrie as the displayed description of the Renewal server, when that 3:1 server merge happened years ago, and the server name is just "Chaos" now.

**Comment by riyuno828** [comment]
Thanks @allanon & lowkeeme  i have zero knowledge on programming but i mange to do it...

**Comment by allanon** [comment]
Oops, should've merged this last week.

**Pull request merged**
