### PR TITLE
update iRO Classic and Renewal files

### PR DESCRIPTION
**Pull request by allanon**
- [ ] QA Review

This pull request was auto-generated by patch_iro.pl: https://gist.github.com/allanon/38620af49d250005acbf

### CODE REVIEW

**Comment by Akk69** [comment]
iRO: Renewal needs an update too xD

**Comment by khalimwu** [comment]
I got the files for renewal but im not authorized for committing.


[servers.txt]((https://github.com/OpenKore/openkore/files/1645146/servers.txt
[shuffle.txt](https://github.com/OpenKore/openkore/files/1645151/shuffle.txt)
[sync.txt](https://github.com/OpenKore/openkore/files/1645152/sync.txt)
[recvpackets.txt](https://github.com/OpenKore/openkore/files/1645153/recvpackets.txt)


)

**Comment by natsume1st** [comment]
@khalimwu how do you get sendcryptkeys, shuffle, and sync. if i may know ? is there a guide ? i cant seem to find it :(

**Comment by ropedope** [comment]
@khalimwu can't seem to get to character select with your files on renewal

**Comment by sctnightcore** [comment]
@ropedope wait 
@khalimwu wait 
@Akk69 wait

**Pull request merged**
