### PR TITLE
#RO:RE old moc_fild

### PR DESCRIPTION
**Pull request by sctnightcore**

### CODE REVIEW

**Comment by xTriumph** [comment]
I think its better to add this to the Restart tables folder than the portals.txt generic.
But first we need to fix the wrong path for the folder in the servers.txt.

**Comment by kaliwanagan** [comment]
@xTriumph thanks, the servers.txt has been fixed in #776 

@sctnightcore once that pr is merged, can you redo the portals.txt changes you're doing inside the iro restart portals.txt instead?

**Comment by kaliwanagan** [comment]
@sctnightcore ping?

**Comment by sctnightcore** [comment]
No merged. @kaliwanagan  
i will fix in tables RE:START 
ty

**Pull request closed without merging**
