### PR TITLE
Added support for Refine UI

### PR DESCRIPTION
**Pull request by cydh**
* **Related Issue:** #1349 
* **Descriptions:**
  * Added command `refineui select [item_index]`
  * Added command `refineui refine [item_index] [material_id] [catalyst_toggle]`
  * References:
    * https://github.com/rathena/rathena/pull/2494
    * https://github.com/cydh/rathena/pull/9 (I use this for testing)
  * Tested using rAthena's PACKETVER 20161207

PS:
* Allow edits from maintainers is checked.
* Suggestions for improvement are welcome, but don't expect I reply it quickly.
* or, devs can **merge** this to main repo and maintain it themselves (do not copy-paste, it's different!)

### CODE REVIEW

**Comment by cydh** [comment]
the `$self->{packet_list}` ?

**Comment by sctnightcore** [comment]
```
https://github.com/OpenKore/openkore/blob/master/src/Network/Send/kRO/Sakexe_0.pm
https://github.com/OpenKore/openkore/blob/master/src/Network/Receive/kRO/Sakexe_0.pm
```
Pserver qw it  not servertype0 ♥

**Comment by alisonrag** [comment]
@sctnightcore 
do you have some server with  this system?
can i test it on this server?

**Comment by moneyisgod** [comment]
thanks @cydh

**Pull request merged**
