### PR TITLE
vRO support

### PR DESCRIPTION
**Pull request by ya4ept**
vRO contains nProtect protection, but it doesn't work yet
Known issues:
- [ ] need to extract recvpackets.txt
- [x] understand how the `password` is encrypted (VTCGame.exe)
  they use usual md5
- [x] understand how the `client_id` crypted (VTCGame.exe)
  always `2aa32a67b771fcab4fd501273ef8b744`
- [x] understand how the `client_secret` crypted (VTCGame.exe)
  always `9ecf8255d241f5e702714734e3a93afb`
- [x] write a script that will receive a `accessToken` and a `billingAccessToken`

image

image

### CODE REVIEW

**Comment by chumlacklx** [comment]
image
what is this fault sir ? still can't connect :(

**Comment by ClarkNguyen** [comment]
@ya4ept Ragexe.exe packed by Themida/Winlicense v3.0, need someone who can unpack it and extract recvpackets

**Comment by ya4ept** [comment]
> Password encrypted using md5 (VTCGame.exe)

thanks 😆

**Comment by chrislong93** [comment]
> > Password encrypted using md5 (VTCGame.exe)
> 
> thanks 😆

Sir, does it mean you have successfully connected to the vRO server but not bot-able yet, due to lack of recvpackets?

**Comment by ya4ept** [comment]
It just means that we now know how to encrypt the password
Stop the flood please. You can flood in this thread #3440

**Comment by ya4ept** [comment]
@ClarkNguyen do you know how `client_id` and `client_secret` are encrypted?
we need these two values, they cannot be random characters

**Comment by nqtoan86** [comment]
> @ClarkNguyen do you know how `client_id` and `client_secret` are encrypted?
> we need these two values, they cannot be random characters

client_id = 2aa32a67b771fcab4fd501273ef8b744
client_secret = 9ecf8255d241f5e702714734e3a93afb

These 2 variables are fixed

**Comment by nqtoan86** [comment]
@ya4ept write a script that will receive a accessToken and a billingAccessToken check image bellow. Edit file src/Network/Send/vRO.pm

`my $ua = LWP::UserAgent->new();
	my $res = $ua->post('https://apisdk.vtcgame.vn/sdk/login',{'username'=>$username,'password'=>md5_hex($password),'client_id'=>'2aa32a67b771fcab4fd501273ef8b744','client_secret'=>'9ecf8255d241f5e702714734e3a93afb','grant_type'=>'password','authen_type'=>0,'device_type'=>1});
	my $json = from_json($res->decoded_content());
	$accessToken = $json->{info}->{accessToken};
	$billingAccessToken = $json->{info}->{billingAccessToken};
	Log::message($accessToken." - ".$billingAccessToken);`

**Comment by ya4ept** [comment]
all is ready!
just add to sys.txt:
```
loadPlugins_list macro,profiles,breakTime,raiseStat,raiseSkill,map,reconnect,eventMacro,item_weight_recorder,xconf,vRO_auth
```

**Comment by onionzz11** [comment]
The server has denied your connection for unknown reason (243).

**Comment by ya4ept** [comment]
set up `debug 1` and show more info

**Comment by onionzz11** [comment]
Untitled

**Comment by ya4ept** [comment]
what about **sys.txt** ? 😈

**Comment by onionzz11** [comment]
> what about **sys.txt** ? 
> [#3453 (comment)](https://github.com/OpenKore/openkore/pull/3453#issuecomment-877698057)

[sys.txt](https://github.com/OpenKore/openkore/files/6796075/sys.txt)

**Comment by onionzz11** [comment]
> what about **sys.txt** ? 
> [#3453 (comment)](https://github.com/OpenKore/openkore/pull/3453#issuecomment-877698057)
###### Localization settings ######
locale

###### Localization compatibility ######
# Enable to make Kore compatible with old 2.0 configs.
locale_compat 0

###### Wx interface settings ######
wxHideConsole 1


###### Bus system settings ######
# Whether to enable the bus system.
bus 0

# If you want to connect to an already running bus server on a different
# computer, specify the host and port here.
bus_server_host
bus_server_port
bus_userAgent


###### Vx interface settings ######
panelTwo_domains publicchat, pm, guildchat, partychat, pm/sent, list, info, selfchat, schat, error, warning
panelOne_lineLimit 900
panelTwo_lineLimit 100
panelFont Verdana
menuFont Lucida Console
sbarFont Arial
panelOne_height 8
panelOne_width 60
panelOne_side top
panelOne_fontsize 8
panelTwo_height 4
panelTwo_width 40
panelTwo_side bottom
panelTwo_fontsize 8


###### Plugin settings ######
# loadPlugins <0|1|2|3>
#   this option controls loading of plugins at startup or when the "plugin load all" command is used.
#   0 : do not load plugins
#   1 : load all plugins
#   2 : only load plugins that are listed in loadPlugins_list
#   3 : load all plugins except those listed in skipPlugins_list
loadPlugins 2

# loadPlugins_list <list>
#   if loadPlugins is set to 2, this comma-separated list of plugin names (filename without the extension)
#   specifies which plugin files to load at startup or when the "plugin load all" command is used.
loadPlugins_list macro,profiles,breakTime,raiseStat,raiseSkill,map,reconnect,eventMacro,item_weight_recorder,xconf

# skipPlugins_list <list>
#   if loadPlugins is set to 3, this comma-separated list of plugin names (filename without the extension)
#   specifies which plugin files to skip at startup or when the "plugin load all" command is used.
skipPlugins_list

###### Miscellaneous ######
sendAnonymousStatisticReport 0

**Comment by onionzz11** [comment]
> what about **sys.txt** ? 
> [#3453 (comment)](https://github.com/OpenKore/openkore/pull/3453#issuecomment-877698057)

> `###### Localization settings ######
locale

###### Localization compatibility ######
# Enable to make Kore compatible with old 2.0 configs.
locale_compat 0

###### Wx interface settings ######
wxHideConsole 1


###### Bus system settings ######
# Whether to enable the bus system.
bus 0

# If you want to connect to an already running bus server on a different
# computer, specify the host and port here.
bus_server_host
bus_server_port
bus_userAgent


###### Vx interface settings ######
panelTwo_domains publicchat, pm, guildchat, partychat, pm/sent, list, info, selfchat, schat, error, warning
panelOne_lineLimit 900
panelTwo_lineLimit 100
panelFont Verdana
menuFont Lucida Console
sbarFont Arial
panelOne_height 8
panelOne_width 60
panelOne_side top
panelOne_fontsize 8
panelTwo_height 4
panelTwo_width 40
panelTwo_side bottom
panelTwo_fontsize 8


###### Plugin settings ######
# loadPlugins <0|1|2|3>
#   this option controls loading of plugins at startup or when the "plugin load all" command is used.
#   0 : do not load plugins
#   1 : load all plugins
#   2 : only load plugins that are listed in loadPlugins_list
#   3 : load all plugins except those listed in skipPlugins_list
loadPlugins 2

# loadPlugins_list <list>
#   if loadPlugins is set to 2, this comma-separated list of plugin names (filename without the extension)
#   specifies which plugin files to load at startup or when the "plugin load all" command is used.
loadPlugins_list macro,profiles,breakTime,raiseStat,raiseSkill,map,reconnect,eventMacro,item_weight_recorder,xconf

# skipPlugins_list <list>
#   if loadPlugins is set to 3, this comma-separated list of plugin names (filename without the extension)
#   specifies which plugin files to skip at startup or when the "plugin load all" command is used.
skipPlugins_list

###### Miscellaneous ######
sendAnonymousStatisticReport `0`

**Comment by onionzz11** [comment]
> what about **sys.txt** ? 
> [#3453 (comment)](https://github.com/OpenKore/openkore/pull/3453#issuecomment-877698057)

[sys.txt](https://github.com/OpenKore/openkore/files/6796082/sys.txt)

**Comment by ya4ept** [comment]
image

**Review by alisonrag — APPROVED** [review]

**Comment by onionzz11** [comment]
OpenKore version what-will-become-2.1
Network state = 1
Network handler = Network::DirectConnection
Revision: ctime:2021_07_11
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
don't forget to add vRO_auth plugin to sys.txt
https://openkore.com/wiki/loadPlugins_list

Stack trace:
don't forget to add vRO_auth plugin to sys.txt
https://openkore.com/wiki/loadPlugins_list
 at src/Interface/Wx.pm line 164
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x54cbe94)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

**Comment by onionzz11** [comment]
loi
disconnected after 3-5monsters :(

**Comment by Link8x** [comment]
Please! Anyop

> loi
> disconnected after 3-5monsters :(

Please! Anyone can fix that problem? I stuck 2 days agi for now. Please help me....!

**Comment by Listenning2524** [comment]
image
Someone can help me what happen of this, how I can fix this problem? pls :(

**Comment by zlBeo** [comment]
Please help me ! 
I have a problem : Disconnected from Map Server, connecting to Account Server in 41 seconds... Sever : Vro

**Pull request merged**
