### PR TITLE
update iRO Renewal files

### PR DESCRIPTION
**Pull request by allanon**
- [x] QA Review

This pull request was auto-generated by patch_iro.pl: https://gist.github.com/allanon/38620af49d250005acbf

### CODE REVIEW

**Comment by bunnyy00** [comment]
hi allanon, where is patch_iro.pl located?

**Comment by sctnightcore** [comment]
@bunnyy00  iRO

**Comment by bunnyy00** [comment]
just paste in openkore/tables/iRO ?

**Comment by bunnyy00** [comment]
@sctnightcore  i still have no idea where to put the patch_iRO.pl file...

**Comment by jomarlorica** [comment]
can i request for whole file of this @allanon ? heheh sorry noob at editing on program. maybe the whole table files only

**Pull request merged**
